// flow-typed signature: f3bcc82800b3c67d5f33555143af10c2
// flow-typed version: <<STUB>>/@kiwicom/browserslist-config_v^1.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@kiwicom/browserslist-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@kiwicom/browserslist-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@kiwicom/browserslist-config/index' {
  declare module.exports: $Exports<'@kiwicom/browserslist-config'>;
}
declare module '@kiwicom/browserslist-config/index.js' {
  declare module.exports: $Exports<'@kiwicom/browserslist-config'>;
}
