// @flow
const colors = {
	brand: {
		light: "#9cdad3",
		lightHover: "#80cfc6",
		lightActive: "#73cac0",
		normal: "#00a991",
		normalHover: "#009882",
		normalActive: "#008f7b",
		dark: "#00826f"
	},
	white: {
		normal: "#fff"
	},
	cloud: {
		light: "#f5f7f9",
		lightHover: "#e5eaef",
		lightActive: "#d6dee6",
		normal: "#e8edf1",
		normalHover: "#d9e1e8",
		normalActive: "#cad5df"
	},
	ink: {
		lighter: "#bac7d5",
		light: "#7f91a8",
		normal: "#46515e",
		normalHover: "#3f4854",
		normalActive: "#38404b",
		dark: "#171b1e"
	},
	orange: {
		light: "#fcf1cd",
		lightHover: "#faeab7",
		lightActive: "#f9e4a1",
		normal: "#f9971e",
		normalHover: "#f48a06",
		normalActive: "#e68206",
		dark: "#a93610"
	},
	red: {
		light: "#fae8e8",
		lightHover: "#f5d4d4",
		lightActive: "#f1c0c0",
		normal: "#d21c1c",
		normalHover: "#bd1919",
		normalActive: "#b21717",
		dark: "#650808"
	},
	green: {
		light: "#e7f3e8",
		lightHover: "#d7ebd8",
		lightActive: "#c7e3c9",
		normal: "#46B655",
		normalHover: "#42ac50",
		normalActive: "#3fa34c",
		dark: "#065d12"
	},
	blue: {
		light: "#e0f6ff",
		lightHover: "#c8effe",
		lightActive: "#b0e8fe",
		normal: "#0176D2",
		normalHover: "#006abd",
		normalActive: "#0064b2",
		dark: "#07405c"
	},
	social: {
		facebook: "#3b5998",
		facebookHover: "#385490",
		facebookActive: "#354f88"
	}
};


const defaultTokens = {
	// category:Color palette
	// description: Use these tokens as a fallback when you need specific color. It's always preferred to use less abstract design tokens. Don't use Hover and Active shades as base colors.
	paletteBrandLight: colors.brand.light,
	paletteBrandLightHover: colors.brand.lightHover,
	paletteBrandLightActive: colors.brand.lightActive,
	paletteBrandNormal: colors.brand.normal,
	paletteBrandNormalHover: colors.brand.normalHover,
	paletteBrandNormalActive: colors.brand.normalActive,
	paletteBrandDark: colors.brand.dark,
	paletteWhite: colors.white.normal,
	paletteCloudLight: colors.brand.light,
	paletteCloudLightHover: colors.brand.lightHover,
	paletteCloudLightActive: colors.brand.lightActive,
	paletteCloudNormal: colors.brand.normal,
	paletteCloudNormalHover: colors.brand.normalHover,
	paletteCloudNormalActive: colors.brand.normalActive,
	paletteInkLighter: colors.ink.lighter,
	paletteInkLight: colors.ink.light,
	paletteInkNormal: colors.ink.normal,
	paletteInkNormalHover: colors.ink.normalHover,
	paletteInkNormalActive: colors.ink.normalActive,
	paletteInkDark: colors.ink.dark,
	paletteOrangeLight: colors.orange.light,
	paletteOrangeLightHover: colors.orange.lightHover,
	paletteOrangeLightActive: colors.orange.lightActive,
	paletteOrangeNormal: colors.orange.normal,
	paletteOrangeNormalHover: colors.orange.normalHover,
	paletteOrangeNormalActive: colors.orange.normalActive,
	paletteOrangeDark: colors.orange.dark,
	paletteRedLight: colors.red.light,
	paletteRedLightHover: colors.red.lightHover,
	paletteRedLightActive: colors.red.lightActive,
	paletteRedNormal: colors.red.normal,
	paletteRedNormalHover: colors.red.normalHover,
	paletteRedNormalActive: colors.red.normalActive,
	paletteRedDark: colors.red.dark,
	paletteGreenLight: colors.green.light,
	paletteGreenLightHover: colors.green.lightHover,
	paletteGreenLightActive: colors.green.lightActive,
	paletteGreenNormal: colors.green.normal,
	paletteGreenNormalHover: colors.green.normalHover,
	paletteGreenNormalActive: colors.green.normalActive,
	paletteGreenDark: colors.green.dark,
	paletteBlueLight: colors.blue.light,
	paletteBlueLightHover: colors.blue.lightHover,
	paletteBlueLightActive: colors.blue.lightActive,
	paletteBlueNormal: colors.blue.normal,
	paletteBlueNormalHover: colors.blue.normalHover,
	paletteBlueNormalActive: colors.blue.normalActive,
	paletteBlueDark: colors.blue.dark,
	paletteSocialFacebook: colors.social.facebook,
	paletteSocialFacebookHover: colors.social.facebookHover,
	paletteSocialFacebookActive: colors.social.facebookActive,
	// category:Colors
	// description:Use these tokens for text or icon colors. Don't use these for borders and background colors.
	colorTextInfo: colors.blue.normal,
	colorTextPrimary: colors.ink.normal,
	colorTextSecondary: colors.ink.light,
	colorTextAttention: colors.ink.dark,
	colorTextError: colors.red.normal,
	colorIconPrimary: colors.ink.normal,
	colorIconSecondary: colors.ink.light,
	colorIconAttention: colors.ink.dark,
	colorIconTerciary: colors.ink.lighter,
	colorHeading: colors.ink.dark,
	colorLinkPrimary: colors.brand.normal,
	colorLinkSecondary: colors.ink.dark,
	colorAlertIconSuccess: colors.green.normal,
	colorTextAlertSuccess: colors.green.dark,
	colorAlertIconInfo: colors.blue.normal,
	colorTextAlertInfo: colors.blue.dark,
	colorAlertIconWarning: colors.orange.normal,
	colorTextAlertWarning: colors.orange.dark,
	colorAlertIconCritical: colors.red.normal,
	colorTextAlertCritical: colors.red.dark,
	colorTextButtonPrimary: colors.white.normal,
	colorIconButtonPrimary: colors.white.normal,
	colorTextButtonPrimaryBordered: colors.brand.normal,
	colorIconButtonPrimaryBordered: colors.brand.normal,
	colorTextButtonSecondary: colors.ink.normal,
	colorIconButtonSecondary: colors.ink.normal,
	colorTextButtonSecondaryBordered: colors.ink.normal,
	colorIconButtonSecondaryBordered: colors.ink.normal,
	colorTextButtonLink: colors.ink.normal,
	colorIconButtonLink: colors.ink.normal,
	colorTextButtonLinkBordered: colors.ink.normal,
	colorIconButtonLinkBordered: colors.ink.normal,
	colorTextButtonFacebook: colors.white.normal,
	colorIconButtonFacebook: colors.white.normal,
	colorTextButtonFacebookBordered: colors.social.facebook,
	colorIconButtonFacebookBordered: colors.social.facebook,
	colorTextButtonGoogle: colors.white.normal,
	colorIconButtonGoogle: colors.white.normal,
	colorTextButtonGoogleBordered: colors.ink.normal,
	colorIconButtonGoogleBordered: colors.ink.normal,
	colorTextButtonInfo: colors.white.normal,
	colorIconButtonInfo: colors.white.normal,
	colorTextButtonInfoBordered: colors.blue.normal,
	colorIconButtonInfoBordered: colors.blue.normal,
	colorTextButtonSuccess: colors.white.normal,
	colorIconButtonSuccess: colors.white.normal,
	colorTextButtonSuccessBordered: colors.green.normal,
	colorIconButtonSuccessBordered: colors.green.normal,
	colorTextButtonWarning: colors.white.normal,
	colorIconButtonWarning: colors.white.normal,
	colorTextButtonWarningBordered: colors.orange.normal,
	colorIconButtonWarningBordered: colors.orange.normal,
	colorTextButtonCritical: colors.white.normal,
	colorIconButtonCritical: colors.white.normal,
	colorTextButtonCriticalBordered: colors.red.normal,
	colorIconButtonCriticalBordered: colors.red.normal,
	colorTextInput: colors.ink.normal,
	colorTextInputDisabled: colors.ink.lighter,
	colorIconInput: colors.ink.lighter,
	colorPlaceholderInput: colors.ink.lighter,
	colorLabelForm: colors.ink.normal,
	colorLabelFormFilled: colors.ink.light,
	colorIconCheckbox: colors.brand.normal,
	colorIconCheckboxDisabled: colors.ink.lighter,
	colorIconRadioButton: colors.brand.normal,
	colorIconRadioButtonDisabled: colors.ink.lighter,
	// category:Font family
	// description:
	fontFamily:
		'"Roboto", -apple-system, ".SFNSText-Regular", "San Francisco", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif',
	// category:Background colors
	// description:Use these tokens for background colors only. Do not use these for border colors or text colors.
	backgroundBody: colors.cloud.light,
	backgroundModal: colors.white.normal,
	backgroundSection: colors.white.normal,
	backgroundCarrierLogo: colors.white.normal,
	backgroundButtonPrimary: colors.brand.normal,
	backgroundButtonSecondary: colors.cloud.normal,
	backgroundButtonLink: "rgba(0,0,0,0)",
	backgroundButtonBordered: "rgba(0,0,0,0)",
	backgroundButtonFacebook: colors.social.facebook,
	backgroundButtonGoogle: colors.ink.normal,
	backgroundButtonInfo: colors.blue.normal,
	backgroundButtonSuccess: colors.green.normal,
	backgroundButtonWarning: colors.orange.normal,
	backgroundButtonCritical: colors.red.normal,
	backgroundButtonLinkHover: colors.cloud.normal,
	backgroundInput: colors.white.normal,
	backgroundInputDisabled: colors.cloud.normal,
	backgroundAlertSuccess: colors.green.light,
	backgroundAlertInfo: colors.blue.light,
	backgroundAlertWarning: colors.orange.light,
	backgroundAlertCritical: colors.red.light,
	// category:Font size
	// description:Use these sizing tokens for font sizes.
	fontSizeHeadingDisplay: "40px",
	fontSizeHeadingLarge: "28px",
	fontSizeHeadingMedium: "22px",
	fontSizeHeadingSmall: "16px",
	fontSizeTextNormal: "14px",
	fontSizeTextLarge: "16px",
	fontSizeTextSmall: "12px",
	fontSizeMessage: "14px",
	fontSizeButtonLarge: "16px",
	fontSizeButtonNormal: "14px",
	fontSizeButtonSmall: "12px",
	fontSizeInputNormal: "16px",
	fontSizeInputSmall: "14px",
	fontSizeLabelForm: "14px",
	fontSizeMessageForm: "12px",
	// category:Border radius
	// description:Use radius tokens to change the border-radius size (rounded corners).
	/** use only for square */
	borderRadiusCircle: "50%",
	/** use for all basic elements like buttons, inputs, content containers */
	borderRadiusNormal: "3px",
	/** use for big elements like modal and large buttons */
	borderRadiusLarge: "6px",
	/** use for smaller elements like tags */
	borderRadiusSmall: "2px",
	// category:Z Index
	// description:Use layers to show depth of page.
	zIndexDefault: "1",
	zIndexSticky: "100",
	zIndexModalOverlay: "800",
	zIndexModal: "825",
	zIndexOnTheTop: "900",
	// category:Size (width, height)
	// description:
	widthIconSmall: "16px",
	heightIconSmall: "16px",
	widthIconMedium: "24px",
	heightIconMedium: "24px",
	widthIconLarge: "32px",
	heightIconLarge: "32px",
	heightInputNormal: "44px",
	heightInputLarge: "52px",
	heightInputSmall: "32px",
	widthButtonMinimal: "180px",
	heightButtonNormal: "44px",
	heightButtonLarge: "52px",
	heightButtonSmall: "32px",
	heightRadioButton: "20px",
	widthRadioButton: "20px",
	heightCheckbox: "20px",
	widthCheckbox: "20px",
	// category:Border color
	// description:
	borderColorInput: colors.ink.lighter,
	borderColorInputFocus: colors.blue.normal,
	borderColorInputError: colors.red.normal,
	borderColorInputErrorFocus: colors.red.normal,
	borderColorTableCell: colors.ink.lighter,
	borderColorSection: colors.cloud.normal,
	borderColorModal: colors.cloud.normal,
	borderColorButtonPrimaryBordered: colors.brand.normal,
	borderColorButtonSecondaryBordered: colors.ink.normal,
	borderColorButtonLinkBordered: "transparent",
	borderColorButtonFacebookBordered: colors.social.facebook,
	borderColorButtonGoogleBordered: colors.ink.normal,
	borderColorButtonInfoBordered: colors.blue.normal,
	borderColorButtonSuccessBordered: colors.green.normal,
	borderColorButtonWarningBordered: colors.orange.normal,
	borderColorButtonCriticalBordered: colors.red.normal,
	// category:Border style
	// description:
	borderStyleSection: "solid",
	borderWidthSection: "1px",
	borderStyleInput: "solid",
	borderWidthInput: "1px",
	// category:Opacity
	// description:
	opacityOverlay: "0.8",
	opacityButtonDisabled: "0.3",
	opacityRadioButtonDisabled: "0.5",
	opacityCheckboxDisabled: "0.5",
	// category:Font weight
	// description:Use this for setting basic font weights.
	fontWeightNormal: "400",
	fontWeightMedium: "500",
	fontWeightBold: "700",
	fontWeightLinks: "500",
	// category:Spacing
	// description:Use this for setting spacings for elements.
	paddingAlert: "16px",
	paddingAlertWithIcon: "12px",
	paddingButtonSmall: "12px",
	paddingButtonNormal: "16px",
	paddingButtonLarge: "28px",
	paddingInputSmall: "12px",
	paddingInputNormal: "16px",
	paddingButtonSmallWithIcon: "8px",
	paddingButtonNormalWithIcon: "8px",
	paddingButtonLargeWithIcon: "12px",
	marginButtonIconSmall: "8px",
	marginButtonIconNormal: "12px",
	marginButtonIconLarge: "16px",
	spaceXXSmall: "4px",
	spaceXSmall: "8px",
	spaceSmall: "12px",
	spaceMedium: "16px",
	spaceLarge: "24px",
	spaceXLarge: "32px",
	spaceXXLarge: "40px",
	spaceXXXLarge: "52px",
	// category:Duration
	// description:Use this for setting the speed of animation or transition.
	durationFast: "0.2s",
	durationNormal: "0.3s",
	durationSlow: "0.4s",
	// category:Modifier
	// description:Use this for values for transform property, etc.
	modifierDarkenHover: 0.05,
	modifierDarkenActive: 0.1,
	modifierDarkenButtonLink: 0.05,
	modifierScaleButtonActive: 0.9,
	// category:Line height
	// description:
	lineHeightText: "1.4",
	lineHeightHeading: "1.2",
	// category:Text decoration
	// description:
	textDecorationLinkPrimary: "none",
	textDecorationLinkPrimaryHover: "underline",
	textDecorationLinkSecondary: "underline",
	textDecorationLinkSecondaryHover: "underline",
	// category:Box shadow
	// description:
	boxShadowInputFocus: "0px 0px 3px 1px rgba(1,118,210,0.3)",
	boxShadowInputErrorFocus: "0px 0px 3px 1px rgba(210,28,28,0.3)",
};

module.exports = defaultTokens;
