extends: substitution
message: "Feel free to use '%s' instead of '%s'."
link: 'https://orbit.kiwi/content/technical-content/language/#use-contractions'
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  are not: aren't
  cannot: can't
  could not: couldn't
  did not: didn't
  do not: don't
  does not: doesn't
  has not: hasn't
  have not: haven't
  is not: isn't
  it is: it's
  should not: shouldn't
  that is: that's
  they are: they're
  was not: wasn't
  we are: we're
  were not: weren't
  what is: what's
  when is: when's
  where is: where's
  will not: won't
  you are: you're
