// flow-typed signature: a3f5ac6dd042f343038b48bb6ba6c738
// flow-typed version: <<STUB>>/@types/styled-components_v^5.1.4/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/styled-components'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/styled-components' {
  declare module.exports: any;
}
