// flow-typed signature: 6c9229d6d8f7114745dfec30fbe41763
// flow-typed version: <<STUB>>/@typescript-eslint/eslint-plugin_v^4.9.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@typescript-eslint/eslint-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@typescript-eslint/eslint-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@typescript-eslint/eslint-plugin/dist/configs/all' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/configs/base' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/configs/recommended-requiring-type-checking' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/configs/recommended' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/array-type' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/await-thenable' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/ban-ts-comment' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/ban-tslint-comment' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/ban-types' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/brace-style' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/class-literal-property-style' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/comma-dangle' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/comma-spacing' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/consistent-indexed-object-style' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/consistent-type-assertions' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/consistent-type-definitions' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/consistent-type-imports' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/default-param-last' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/dot-notation' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/explicit-function-return-type' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/explicit-member-accessibility' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/explicit-module-boundary-types' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/func-call-spacing' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/BinarySearchTree' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/OffsetStorage' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/TokenInfo' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/indent' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/init-declarations' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/keyword-spacing' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/lines-between-class-members' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/member-delimiter-style' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/member-ordering' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/method-signature-style' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/enums' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/format' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/parse-options' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/schema' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/shared' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/types' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/validator' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-array-constructor' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-base-to-string' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-confusing-non-null-assertion' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-confusing-void-expression' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-dupe-class-members' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-duplicate-imports' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-dynamic-delete' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-empty-function' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-empty-interface' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-explicit-any' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-extra-non-null-assertion' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-extra-parens' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-extra-semi' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-extraneous-class' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-floating-promises' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-for-in-array' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-implicit-any-catch' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-implied-eval' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-inferrable-types' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-invalid-this' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-invalid-void-type' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-loop-func' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-loss-of-precision' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-magic-numbers' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-misused-new' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-misused-promises' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-namespace' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-non-null-asserted-optional-chain' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-non-null-assertion' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-parameter-properties' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-redeclare' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-require-imports' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-shadow' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-this-alias' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-throw-literal' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-type-alias' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-boolean-literal-compare' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-condition' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-qualifier' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-type-arguments' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-type-assertion' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-type-constraint' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-assignment' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-call' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-member-access' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-return' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unused-expressions' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars-experimental' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-use-before-define' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-useless-constructor' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/no-var-requires' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/non-nullable-type-assertion-style' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/object-curly-spacing' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-as-const' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-enum-initializers' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-for-of' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-function-type' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-includes' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-literal-enum-member' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-namespace-keyword' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-nullish-coalescing' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-optional-chain' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-readonly-parameter-types' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-readonly' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-reduce-type-parameter' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-regexp-exec' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-string-starts-ends-with' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-ts-expect-error' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/promise-function-async' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/quotes' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/require-array-sort-compare' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/require-await' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/restrict-plus-operands' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/restrict-template-expressions' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/return-await' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/semi' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/sort-type-union-intersection-members' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/space-before-function-paren' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/space-infix-ops' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/strict-boolean-expressions' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/switch-exhaustiveness-check' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/triple-slash-reference' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/type-annotation-spacing' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/typedef' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/unbound-method' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/rules/unified-signatures' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/astUtils' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/collectUnusedVariables' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/createRule' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/explicitReturnTypeUtils' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/getFunctionHeadLoc' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/getWrappingFixer' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/misc' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/nullThrows' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/objectIterators' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/propertyTypes' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/requiresQuoting' {
  declare module.exports: any;
}

declare module '@typescript-eslint/eslint-plugin/dist/util/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@typescript-eslint/eslint-plugin/dist/configs/all.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/configs/all'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/configs/base.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/configs/base'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/configs/eslint-recommended'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/configs/recommended-requiring-type-checking.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/configs/recommended-requiring-type-checking'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/configs/recommended.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/configs/recommended'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/index' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/index.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/array-type.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/array-type'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/await-thenable.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/await-thenable'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/ban-ts-comment.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/ban-ts-comment'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/ban-tslint-comment.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/ban-tslint-comment'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/ban-types.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/ban-types'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/brace-style.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/brace-style'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/class-literal-property-style.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/class-literal-property-style'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/comma-dangle.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/comma-dangle'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/comma-spacing.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/comma-spacing'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/consistent-indexed-object-style.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/consistent-indexed-object-style'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/consistent-type-assertions.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/consistent-type-assertions'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/consistent-type-definitions.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/consistent-type-definitions'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/consistent-type-imports.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/consistent-type-imports'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/default-param-last.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/default-param-last'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/dot-notation.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/dot-notation'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/explicit-function-return-type.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/explicit-function-return-type'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/explicit-member-accessibility.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/explicit-member-accessibility'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/explicit-module-boundary-types.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/explicit-module-boundary-types'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/func-call-spacing.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/func-call-spacing'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/BinarySearchTree.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/BinarySearchTree'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/index' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/index.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/OffsetStorage.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/OffsetStorage'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/TokenInfo.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/indent-new-do-not-use/TokenInfo'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/indent.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/indent'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/index' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/index.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/init-declarations.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/init-declarations'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/keyword-spacing.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/keyword-spacing'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/lines-between-class-members.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/lines-between-class-members'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/member-delimiter-style.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/member-delimiter-style'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/member-ordering.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/member-ordering'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/method-signature-style.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/method-signature-style'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/enums.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/enums'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/format.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/format'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/index' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/index.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/parse-options.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/parse-options'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/schema.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/schema'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/shared.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/shared'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/types.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/types'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/validator.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/naming-convention-utils/validator'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/naming-convention.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/naming-convention'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-array-constructor.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-array-constructor'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-base-to-string.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-base-to-string'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-confusing-non-null-assertion.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-confusing-non-null-assertion'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-confusing-void-expression.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-confusing-void-expression'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-dupe-class-members.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-dupe-class-members'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-duplicate-imports.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-duplicate-imports'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-dynamic-delete.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-dynamic-delete'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-empty-function.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-empty-function'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-empty-interface.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-empty-interface'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-explicit-any.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-explicit-any'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-extra-non-null-assertion.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-extra-non-null-assertion'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-extra-parens.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-extra-parens'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-extra-semi.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-extra-semi'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-extraneous-class.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-extraneous-class'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-floating-promises.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-floating-promises'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-for-in-array.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-for-in-array'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-implicit-any-catch.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-implicit-any-catch'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-implied-eval.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-implied-eval'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-inferrable-types.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-inferrable-types'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-invalid-this.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-invalid-this'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-invalid-void-type.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-invalid-void-type'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-loop-func.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-loop-func'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-loss-of-precision.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-loss-of-precision'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-magic-numbers.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-magic-numbers'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-misused-new.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-misused-new'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-misused-promises.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-misused-promises'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-namespace.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-namespace'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-non-null-asserted-optional-chain.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-non-null-asserted-optional-chain'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-non-null-assertion.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-non-null-assertion'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-parameter-properties.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-parameter-properties'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-redeclare.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-redeclare'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-require-imports.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-require-imports'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-shadow.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-shadow'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-this-alias.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-this-alias'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-throw-literal.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-throw-literal'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-type-alias.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-type-alias'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-boolean-literal-compare.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-boolean-literal-compare'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-condition.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-condition'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-qualifier.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-qualifier'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-type-arguments.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-type-arguments'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-type-assertion.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-type-assertion'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-type-constraint.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unnecessary-type-constraint'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-assignment.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-assignment'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-call.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-call'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-member-access.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-member-access'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-return.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unsafe-return'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unused-expressions.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unused-expressions'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars-experimental.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars-experimental'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-unused-vars'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-use-before-define.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-use-before-define'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-useless-constructor.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-useless-constructor'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/no-var-requires.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/no-var-requires'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/non-nullable-type-assertion-style.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/non-nullable-type-assertion-style'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/object-curly-spacing.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/object-curly-spacing'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-as-const.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-as-const'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-enum-initializers.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-enum-initializers'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-for-of.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-for-of'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-function-type.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-function-type'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-includes.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-includes'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-literal-enum-member.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-literal-enum-member'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-namespace-keyword.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-namespace-keyword'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-nullish-coalescing.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-nullish-coalescing'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-optional-chain.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-optional-chain'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-readonly-parameter-types.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-readonly-parameter-types'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-readonly.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-readonly'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-reduce-type-parameter.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-reduce-type-parameter'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-regexp-exec.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-regexp-exec'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-string-starts-ends-with.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-string-starts-ends-with'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/prefer-ts-expect-error.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/prefer-ts-expect-error'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/promise-function-async.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/promise-function-async'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/quotes.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/quotes'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/require-array-sort-compare.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/require-array-sort-compare'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/require-await.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/require-await'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/restrict-plus-operands.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/restrict-plus-operands'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/restrict-template-expressions.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/restrict-template-expressions'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/return-await.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/return-await'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/semi.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/semi'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/sort-type-union-intersection-members.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/sort-type-union-intersection-members'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/space-before-function-paren.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/space-before-function-paren'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/space-infix-ops.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/space-infix-ops'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/strict-boolean-expressions.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/strict-boolean-expressions'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/switch-exhaustiveness-check.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/switch-exhaustiveness-check'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/triple-slash-reference.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/triple-slash-reference'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/type-annotation-spacing.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/type-annotation-spacing'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/typedef.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/typedef'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/unbound-method.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/unbound-method'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/rules/unified-signatures.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/rules/unified-signatures'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/astUtils.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/astUtils'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/collectUnusedVariables.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/collectUnusedVariables'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/createRule.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/createRule'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/explicitReturnTypeUtils.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/explicitReturnTypeUtils'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/getFunctionHeadLoc.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/getFunctionHeadLoc'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/getWrappingFixer.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/getWrappingFixer'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/index' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/index.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/isTypeReadonly'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/misc.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/misc'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/nullThrows.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/nullThrows'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/objectIterators.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/objectIterators'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/propertyTypes.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/propertyTypes'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/requiresQuoting.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/requiresQuoting'>;
}
declare module '@typescript-eslint/eslint-plugin/dist/util/types.js' {
  declare module.exports: $Exports<'@typescript-eslint/eslint-plugin/dist/util/types'>;
}
