// flow-typed signature: ffbad9d4cacc669da500c8265b74db16
// flow-typed version: <<STUB>>/@typescript-eslint/parser_v^4.15.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@typescript-eslint/parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@typescript-eslint/parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@typescript-eslint/parser/dist' {
  declare module.exports: any;
}

declare module '@typescript-eslint/parser/dist/parser' {
  declare module.exports: any;
}

// Filename aliases
declare module '@typescript-eslint/parser/dist/index' {
  declare module.exports: $Exports<'@typescript-eslint/parser/dist'>;
}
declare module '@typescript-eslint/parser/dist/index.js' {
  declare module.exports: $Exports<'@typescript-eslint/parser/dist'>;
}
declare module '@typescript-eslint/parser/dist/parser.js' {
  declare module.exports: $Exports<'@typescript-eslint/parser/dist/parser'>;
}
