// flow-typed signature: b5cdb841a688c1c49e734fe48d2461bf
// flow-typed version: <<STUB>>/@emotion/core_v^11.0.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@emotion/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@emotion/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@emotion/core/dist/emotion-core.cjs.dev' {
  declare module.exports: any;
}

declare module '@emotion/core/dist/emotion-core.cjs' {
  declare module.exports: any;
}

declare module '@emotion/core/dist/emotion-core.cjs.prod' {
  declare module.exports: any;
}

declare module '@emotion/core/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@emotion/core/dist/emotion-core.cjs.dev.js' {
  declare module.exports: $Exports<'@emotion/core/dist/emotion-core.cjs.dev'>;
}
declare module '@emotion/core/dist/emotion-core.cjs.js' {
  declare module.exports: $Exports<'@emotion/core/dist/emotion-core.cjs'>;
}
declare module '@emotion/core/dist/emotion-core.cjs.prod.js' {
  declare module.exports: $Exports<'@emotion/core/dist/emotion-core.cjs.prod'>;
}
declare module '@emotion/core/src/index' {
  declare module.exports: $Exports<'@emotion/core/src'>;
}
declare module '@emotion/core/src/index.js' {
  declare module.exports: $Exports<'@emotion/core/src'>;
}
