// flow-typed signature: b5415d0bc24b2fde64b4d18b93d73400
// flow-typed version: <<STUB>>/@octokit/rest_v^18.0.14/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@octokit/rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@octokit/rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@octokit/rest/dist-node' {
  declare module.exports: any;
}

declare module '@octokit/rest/dist-src' {
  declare module.exports: any;
}

declare module '@octokit/rest/dist-src/version' {
  declare module.exports: any;
}

declare module '@octokit/rest/dist-web' {
  declare module.exports: any;
}

// Filename aliases
declare module '@octokit/rest/dist-node/index' {
  declare module.exports: $Exports<'@octokit/rest/dist-node'>;
}
declare module '@octokit/rest/dist-node/index.js' {
  declare module.exports: $Exports<'@octokit/rest/dist-node'>;
}
declare module '@octokit/rest/dist-src/index' {
  declare module.exports: $Exports<'@octokit/rest/dist-src'>;
}
declare module '@octokit/rest/dist-src/index.js' {
  declare module.exports: $Exports<'@octokit/rest/dist-src'>;
}
declare module '@octokit/rest/dist-src/version.js' {
  declare module.exports: $Exports<'@octokit/rest/dist-src/version'>;
}
declare module '@octokit/rest/dist-web/index' {
  declare module.exports: $Exports<'@octokit/rest/dist-web'>;
}
declare module '@octokit/rest/dist-web/index.js' {
  declare module.exports: $Exports<'@octokit/rest/dist-web'>;
}
