// flow-typed signature: 0d5b518e4dbb5d1b44dfd60fa381d524
// flow-typed version: <<STUB>>/babel-plugin-require-context-hook_v^1.0.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-require-context-hook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-require-context-hook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-require-context-hook/register' {
  declare module.exports: any;
}

declare module 'babel-plugin-require-context-hook/test/a/a' {
  declare module.exports: any;
}

declare module 'babel-plugin-require-context-hook/test/a/b/b' {
  declare module.exports: any;
}

declare module 'babel-plugin-require-context-hook/test/a/no' {
  declare module.exports: any;
}

declare module 'babel-plugin-require-context-hook/test/run' {
  declare module.exports: any;
}

declare module 'babel-plugin-require-context-hook/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-require-context-hook/index' {
  declare module.exports: $Exports<'babel-plugin-require-context-hook'>;
}
declare module 'babel-plugin-require-context-hook/index.js' {
  declare module.exports: $Exports<'babel-plugin-require-context-hook'>;
}
declare module 'babel-plugin-require-context-hook/register.js' {
  declare module.exports: $Exports<'babel-plugin-require-context-hook/register'>;
}
declare module 'babel-plugin-require-context-hook/test/a/a.js' {
  declare module.exports: $Exports<'babel-plugin-require-context-hook/test/a/a'>;
}
declare module 'babel-plugin-require-context-hook/test/a/b/b.js' {
  declare module.exports: $Exports<'babel-plugin-require-context-hook/test/a/b/b'>;
}
declare module 'babel-plugin-require-context-hook/test/a/no.jsx' {
  declare module.exports: $Exports<'babel-plugin-require-context-hook/test/a/no'>;
}
declare module 'babel-plugin-require-context-hook/test/run.js' {
  declare module.exports: $Exports<'babel-plugin-require-context-hook/test/run'>;
}
declare module 'babel-plugin-require-context-hook/test/test.js' {
  declare module.exports: $Exports<'babel-plugin-require-context-hook/test/test'>;
}
