// flow-typed signature: f8d77fda43ab832b2281e471e1c3ffdf
// flow-typed version: <<STUB>>/camelcase_v^6.1.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'camelcase'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'camelcase' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'camelcase/index' {
  declare module.exports: $Exports<'camelcase'>;
}
declare module 'camelcase/index.js' {
  declare module.exports: $Exports<'camelcase'>;
}
