// flow-typed signature: 293b97aebca3110e908b2d9b27ef0c76
// flow-typed version: <<STUB>>/caniuse-db_v^1.0.30001185/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-db' {
  declare module.exports: any;
}
