// flow-typed signature: b3766708b0d87f94f7c0d6b28cee1c98
// flow-typed version: <<STUB>>/caniuse-db_v^1.0.30001185/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'caniuse-db'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'caniuse-db' {
  declare module.exports: any;
}
