// flow-typed signature: 0a8213f09f8964950b4780402d96dbe5
// flow-typed version: <<STUB>>/capitalize_v^2.0.3/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'capitalize'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'capitalize' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'capitalize/index' {
  declare module.exports: $Exports<'capitalize'>;
}
declare module 'capitalize/index.js' {
  declare module.exports: $Exports<'capitalize'>;
}
