// flow-typed signature: adf999530400d535d8e7a70b646126df
// flow-typed version: <<STUB>>/check-links_v^1.1.8/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'check-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'check-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'check-links/lib/check-link' {
  declare module.exports: any;
}

declare module 'check-links/test/check-link.test' {
  declare module.exports: any;
}

declare module 'check-links/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'check-links/index' {
  declare module.exports: $Exports<'check-links'>;
}
declare module 'check-links/index.js' {
  declare module.exports: $Exports<'check-links'>;
}
declare module 'check-links/lib/check-link.js' {
  declare module.exports: $Exports<'check-links/lib/check-link'>;
}
declare module 'check-links/test/check-link.test.js' {
  declare module.exports: $Exports<'check-links/test/check-link.test'>;
}
declare module 'check-links/test/index.test.js' {
  declare module.exports: $Exports<'check-links/test/index.test'>;
}
