// flow-typed signature: 331868e08273142eee2c14e85afbb92f
// flow-typed version: <<STUB>>/conventional-changelog_v^3.1.24/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'conventional-changelog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'conventional-changelog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'conventional-changelog/index' {
  declare module.exports: $Exports<'conventional-changelog'>;
}
declare module 'conventional-changelog/index.js' {
  declare module.exports: $Exports<'conventional-changelog'>;
}
