// flow-typed signature: ebdb21c548cea320280e4e58213ec28c
// flow-typed version: <<STUB>>/eslint-plugin-mdx_v^1.8.2/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-mdx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-mdx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-mdx/lib/cjs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/cjs.min' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/configs/base' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/configs/code-blocks' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/configs/helpers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/configs' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/configs/overrides' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/configs/recommended' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/es2015' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/es2015.min' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/esm' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/esm.min' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/processors/helpers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/processors' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/processors/markdown' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/processors/options' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/processors/remark' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/processors/types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/rules/helpers' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/rules' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/rules/no-jsx-html-comments' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/rules/no-unused-expressions' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/rules/remark' {
  declare module.exports: any;
}

declare module 'eslint-plugin-mdx/lib/rules/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-mdx/lib/cjs.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/cjs'>;
}
declare module 'eslint-plugin-mdx/lib/cjs.min.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/cjs.min'>;
}
declare module 'eslint-plugin-mdx/lib/configs/base.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/configs/base'>;
}
declare module 'eslint-plugin-mdx/lib/configs/code-blocks.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/configs/code-blocks'>;
}
declare module 'eslint-plugin-mdx/lib/configs/helpers.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/configs/helpers'>;
}
declare module 'eslint-plugin-mdx/lib/configs/index' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/configs'>;
}
declare module 'eslint-plugin-mdx/lib/configs/index.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/configs'>;
}
declare module 'eslint-plugin-mdx/lib/configs/overrides.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/configs/overrides'>;
}
declare module 'eslint-plugin-mdx/lib/configs/recommended.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/configs/recommended'>;
}
declare module 'eslint-plugin-mdx/lib/es2015.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/es2015'>;
}
declare module 'eslint-plugin-mdx/lib/es2015.min.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/es2015.min'>;
}
declare module 'eslint-plugin-mdx/lib/esm.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/esm'>;
}
declare module 'eslint-plugin-mdx/lib/esm.min.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/esm.min'>;
}
declare module 'eslint-plugin-mdx/lib/index' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib'>;
}
declare module 'eslint-plugin-mdx/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib'>;
}
declare module 'eslint-plugin-mdx/lib/processors/helpers.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/processors/helpers'>;
}
declare module 'eslint-plugin-mdx/lib/processors/index' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/processors'>;
}
declare module 'eslint-plugin-mdx/lib/processors/index.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/processors'>;
}
declare module 'eslint-plugin-mdx/lib/processors/markdown.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/processors/markdown'>;
}
declare module 'eslint-plugin-mdx/lib/processors/options.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/processors/options'>;
}
declare module 'eslint-plugin-mdx/lib/processors/remark.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/processors/remark'>;
}
declare module 'eslint-plugin-mdx/lib/processors/types.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/processors/types'>;
}
declare module 'eslint-plugin-mdx/lib/rules/helpers.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/rules/helpers'>;
}
declare module 'eslint-plugin-mdx/lib/rules/index' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/rules'>;
}
declare module 'eslint-plugin-mdx/lib/rules/index.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/rules'>;
}
declare module 'eslint-plugin-mdx/lib/rules/no-jsx-html-comments.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/rules/no-jsx-html-comments'>;
}
declare module 'eslint-plugin-mdx/lib/rules/no-unused-expressions.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/rules/no-unused-expressions'>;
}
declare module 'eslint-plugin-mdx/lib/rules/remark.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/rules/remark'>;
}
declare module 'eslint-plugin-mdx/lib/rules/types.js' {
  declare module.exports: $Exports<'eslint-plugin-mdx/lib/rules/types'>;
}
