// flow-typed signature: de8c8eef26d9cc62f43dcae50f59496a
// flow-typed version: <<STUB>>/eslint-import-resolver-alias_v^1.1.2/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-import-resolver-alias'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-import-resolver-alias' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-import-resolver-alias/core' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-import-resolver-alias/core.js' {
  declare module.exports: $Exports<'eslint-import-resolver-alias/core'>;
}
declare module 'eslint-import-resolver-alias/index' {
  declare module.exports: $Exports<'eslint-import-resolver-alias'>;
}
declare module 'eslint-import-resolver-alias/index.js' {
  declare module.exports: $Exports<'eslint-import-resolver-alias'>;
}
