// flow-typed signature: 92c9c7796c1c47ce6698bf6403458a22
// flow-typed version: <<STUB>>/loki_v^0.27.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loki'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loki' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loki/configure-react-native' {
  declare module.exports: any;
}

declare module 'loki/configure-react' {
  declare module.exports: any;
}

declare module 'loki/configure-vue' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loki/configure-react-native.js' {
  declare module.exports: $Exports<'loki/configure-react-native'>;
}
declare module 'loki/configure-react.js' {
  declare module.exports: $Exports<'loki/configure-react'>;
}
declare module 'loki/configure-vue.js' {
  declare module.exports: $Exports<'loki/configure-vue'>;
}
