// flow-typed signature: f334d42273a4a3a0119f6ee8f0e39b10
// flow-typed version: <<STUB>>/make-runnable_v^1.3.8/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'make-runnable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'make-runnable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'make-runnable/custom' {
  declare module.exports: any;
}

declare module 'make-runnable/engine' {
  declare module.exports: any;
}

declare module 'make-runnable/test/test_module_no_output_frame' {
  declare module.exports: any;
}

declare module 'make-runnable/test/test' {
  declare module.exports: any;
}

declare module 'make-runnable/test/testModules/basic' {
  declare module.exports: any;
}

declare module 'make-runnable/test/testModules/noOutputFrame' {
  declare module.exports: any;
}

declare module 'make-runnable/utils/mergeObjects' {
  declare module.exports: any;
}

// Filename aliases
declare module 'make-runnable/custom.js' {
  declare module.exports: $Exports<'make-runnable/custom'>;
}
declare module 'make-runnable/engine.js' {
  declare module.exports: $Exports<'make-runnable/engine'>;
}
declare module 'make-runnable/index' {
  declare module.exports: $Exports<'make-runnable'>;
}
declare module 'make-runnable/index.js' {
  declare module.exports: $Exports<'make-runnable'>;
}
declare module 'make-runnable/test/test_module_no_output_frame.js' {
  declare module.exports: $Exports<'make-runnable/test/test_module_no_output_frame'>;
}
declare module 'make-runnable/test/test.js' {
  declare module.exports: $Exports<'make-runnable/test/test'>;
}
declare module 'make-runnable/test/testModules/basic.js' {
  declare module.exports: $Exports<'make-runnable/test/testModules/basic'>;
}
declare module 'make-runnable/test/testModules/noOutputFrame.js' {
  declare module.exports: $Exports<'make-runnable/test/testModules/noOutputFrame'>;
}
declare module 'make-runnable/utils/mergeObjects.js' {
  declare module.exports: $Exports<'make-runnable/utils/mergeObjects'>;
}
