// flow-typed signature: 6af63bd35a9937e89f65c43364e10802
// flow-typed version: <<STUB>>/markdown-magic_v^1.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-magic'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-magic' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-magic/cli-utils' {
  declare module.exports: any;
}

declare module 'markdown-magic/cli' {
  declare module.exports: any;
}

declare module 'markdown-magic/examples/basic-usage' {
  declare module.exports: any;
}

declare module 'markdown-magic/examples/generate-readme' {
  declare module.exports: any;
}

declare module 'markdown-magic/examples/plugin-example' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/processFile' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/transforms/code' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/transforms' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/transforms/remote' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/transforms/toc' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/updateContents' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/regex' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/remoteRequest' {
  declare module.exports: any;
}

declare module 'markdown-magic/lib/utils/sortOrder' {
  declare module.exports: any;
}

declare module 'markdown-magic/markdown.config' {
  declare module.exports: any;
}

declare module 'markdown-magic/test/fixtures/local-code-file' {
  declare module.exports: any;
}

declare module 'markdown-magic/test/main.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-magic/cli-utils.js' {
  declare module.exports: $Exports<'markdown-magic/cli-utils'>;
}
declare module 'markdown-magic/cli.js' {
  declare module.exports: $Exports<'markdown-magic/cli'>;
}
declare module 'markdown-magic/examples/basic-usage.js' {
  declare module.exports: $Exports<'markdown-magic/examples/basic-usage'>;
}
declare module 'markdown-magic/examples/generate-readme.js' {
  declare module.exports: $Exports<'markdown-magic/examples/generate-readme'>;
}
declare module 'markdown-magic/examples/plugin-example.js' {
  declare module.exports: $Exports<'markdown-magic/examples/plugin-example'>;
}
declare module 'markdown-magic/index' {
  declare module.exports: $Exports<'markdown-magic'>;
}
declare module 'markdown-magic/index.js' {
  declare module.exports: $Exports<'markdown-magic'>;
}
declare module 'markdown-magic/lib/processFile.js' {
  declare module.exports: $Exports<'markdown-magic/lib/processFile'>;
}
declare module 'markdown-magic/lib/transforms/code.js' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms/code'>;
}
declare module 'markdown-magic/lib/transforms/index' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms'>;
}
declare module 'markdown-magic/lib/transforms/index.js' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms'>;
}
declare module 'markdown-magic/lib/transforms/remote.js' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms/remote'>;
}
declare module 'markdown-magic/lib/transforms/toc.js' {
  declare module.exports: $Exports<'markdown-magic/lib/transforms/toc'>;
}
declare module 'markdown-magic/lib/updateContents.js' {
  declare module.exports: $Exports<'markdown-magic/lib/updateContents'>;
}
declare module 'markdown-magic/lib/utils/regex.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/regex'>;
}
declare module 'markdown-magic/lib/utils/remoteRequest.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/remoteRequest'>;
}
declare module 'markdown-magic/lib/utils/sortOrder.js' {
  declare module.exports: $Exports<'markdown-magic/lib/utils/sortOrder'>;
}
declare module 'markdown-magic/markdown.config.js' {
  declare module.exports: $Exports<'markdown-magic/markdown.config'>;
}
declare module 'markdown-magic/test/fixtures/local-code-file.js' {
  declare module.exports: $Exports<'markdown-magic/test/fixtures/local-code-file'>;
}
declare module 'markdown-magic/test/main.test.js' {
  declare module.exports: $Exports<'markdown-magic/test/main.test'>;
}
