// flow-typed signature: 305d322f60d1ff0aacc7a04ca2868fcb
// flow-typed version: <<STUB>>/markdown-chalk_v^2.1.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-chalk'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'markdown-chalk' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'markdown-chalk/bin' {
  declare module.exports: any;
}

declare module 'markdown-chalk/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'markdown-chalk/bin/index' {
  declare module.exports: $Exports<'markdown-chalk/bin'>;
}
declare module 'markdown-chalk/bin/index.js' {
  declare module.exports: $Exports<'markdown-chalk/bin'>;
}
declare module 'markdown-chalk/test/test.js' {
  declare module.exports: $Exports<'markdown-chalk/test/test'>;
}
