// flow-typed signature: 1daef48c1b61aa99f1002dd27c158dcc
// flow-typed version: <<STUB>>/memfs_v^3.2.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'memfs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'memfs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'memfs/lib/constants' {
  declare module.exports: any;
}

declare module 'memfs/lib/Dirent' {
  declare module.exports: any;
}

declare module 'memfs/lib/encoding' {
  declare module.exports: any;
}

declare module 'memfs/lib/getBigInt' {
  declare module.exports: any;
}

declare module 'memfs/lib' {
  declare module.exports: any;
}

declare module 'memfs/lib/internal/buffer' {
  declare module.exports: any;
}

declare module 'memfs/lib/internal/errors' {
  declare module.exports: any;
}

declare module 'memfs/lib/node' {
  declare module.exports: any;
}

declare module 'memfs/lib/process' {
  declare module.exports: any;
}

declare module 'memfs/lib/promises' {
  declare module.exports: any;
}

declare module 'memfs/lib/setImmediate' {
  declare module.exports: any;
}

declare module 'memfs/lib/setTimeoutUnref' {
  declare module.exports: any;
}

declare module 'memfs/lib/Stats' {
  declare module.exports: any;
}

declare module 'memfs/lib/volume-localstorage' {
  declare module.exports: any;
}

declare module 'memfs/lib/volume' {
  declare module.exports: any;
}

// Filename aliases
declare module 'memfs/lib/constants.js' {
  declare module.exports: $Exports<'memfs/lib/constants'>;
}
declare module 'memfs/lib/Dirent.js' {
  declare module.exports: $Exports<'memfs/lib/Dirent'>;
}
declare module 'memfs/lib/encoding.js' {
  declare module.exports: $Exports<'memfs/lib/encoding'>;
}
declare module 'memfs/lib/getBigInt.js' {
  declare module.exports: $Exports<'memfs/lib/getBigInt'>;
}
declare module 'memfs/lib/index' {
  declare module.exports: $Exports<'memfs/lib'>;
}
declare module 'memfs/lib/index.js' {
  declare module.exports: $Exports<'memfs/lib'>;
}
declare module 'memfs/lib/internal/buffer.js' {
  declare module.exports: $Exports<'memfs/lib/internal/buffer'>;
}
declare module 'memfs/lib/internal/errors.js' {
  declare module.exports: $Exports<'memfs/lib/internal/errors'>;
}
declare module 'memfs/lib/node.js' {
  declare module.exports: $Exports<'memfs/lib/node'>;
}
declare module 'memfs/lib/process.js' {
  declare module.exports: $Exports<'memfs/lib/process'>;
}
declare module 'memfs/lib/promises.js' {
  declare module.exports: $Exports<'memfs/lib/promises'>;
}
declare module 'memfs/lib/setImmediate.js' {
  declare module.exports: $Exports<'memfs/lib/setImmediate'>;
}
declare module 'memfs/lib/setTimeoutUnref.js' {
  declare module.exports: $Exports<'memfs/lib/setTimeoutUnref'>;
}
declare module 'memfs/lib/Stats.js' {
  declare module.exports: $Exports<'memfs/lib/Stats'>;
}
declare module 'memfs/lib/volume-localstorage.js' {
  declare module.exports: $Exports<'memfs/lib/volume-localstorage'>;
}
declare module 'memfs/lib/volume.js' {
  declare module.exports: $Exports<'memfs/lib/volume'>;
}
