// flow-typed signature: 8e8e3a62a01b9c47b67523ba1c3dce60
// flow-typed version: <<STUB>>/pinst_v^2.1.4/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pinst'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pinst' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pinst/bin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pinst/bin.js' {
  declare module.exports: $Exports<'pinst/bin'>;
}
declare module 'pinst/index' {
  declare module.exports: $Exports<'pinst'>;
}
declare module 'pinst/index.js' {
  declare module.exports: $Exports<'pinst'>;
}
