// flow-typed signature: e41e3cfb62e1e6121aeda7576a0e1e44
// flow-typed version: <<STUB>>/remark-cli_v^9.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-cli/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-cli/cli.js' {
  declare module.exports: $Exports<'remark-cli/cli'>;
}
