// flow-typed signature: a382db5b5ecb50b333048e1f2a5273a8
// flow-typed version: <<STUB>>/remark-frontmatter_v^2.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-frontmatter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-frontmatter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-frontmatter/lib/compile' {
  declare module.exports: any;
}

declare module 'remark-frontmatter/lib/fence' {
  declare module.exports: any;
}

declare module 'remark-frontmatter/lib/matters' {
  declare module.exports: any;
}

declare module 'remark-frontmatter/lib/parse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-frontmatter/index' {
  declare module.exports: $Exports<'remark-frontmatter'>;
}
declare module 'remark-frontmatter/index.js' {
  declare module.exports: $Exports<'remark-frontmatter'>;
}
declare module 'remark-frontmatter/lib/compile.js' {
  declare module.exports: $Exports<'remark-frontmatter/lib/compile'>;
}
declare module 'remark-frontmatter/lib/fence.js' {
  declare module.exports: $Exports<'remark-frontmatter/lib/fence'>;
}
declare module 'remark-frontmatter/lib/matters.js' {
  declare module.exports: $Exports<'remark-frontmatter/lib/matters'>;
}
declare module 'remark-frontmatter/lib/parse.js' {
  declare module.exports: $Exports<'remark-frontmatter/lib/parse'>;
}
