// flow-typed signature: d72bc770c38620f50ac25791b95c86a2
// flow-typed version: <<STUB>>/remark-mdx_v^1.6.22/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-mdx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-mdx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-mdx/block' {
  declare module.exports: any;
}

declare module 'remark-mdx/extract-imports-and-exports' {
  declare module.exports: any;
}

declare module 'remark-mdx/tag' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-mdx/block.js' {
  declare module.exports: $Exports<'remark-mdx/block'>;
}
declare module 'remark-mdx/extract-imports-and-exports.js' {
  declare module.exports: $Exports<'remark-mdx/extract-imports-and-exports'>;
}
declare module 'remark-mdx/index' {
  declare module.exports: $Exports<'remark-mdx'>;
}
declare module 'remark-mdx/index.js' {
  declare module.exports: $Exports<'remark-mdx'>;
}
declare module 'remark-mdx/tag.js' {
  declare module.exports: $Exports<'remark-mdx/tag'>;
}
