// flow-typed signature: b24481e34bfc6778ac860852bb757c48
// flow-typed version: <<STUB>>/remark-preset-prettier_v^0.4.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-preset-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-preset-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-preset-prettier/lib/cjs' {
  declare module.exports: any;
}

declare module 'remark-preset-prettier/lib/es2015' {
  declare module.exports: any;
}

declare module 'remark-preset-prettier/lib/esm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-preset-prettier/lib/cjs.js' {
  declare module.exports: $Exports<'remark-preset-prettier/lib/cjs'>;
}
declare module 'remark-preset-prettier/lib/es2015.js' {
  declare module.exports: $Exports<'remark-preset-prettier/lib/es2015'>;
}
declare module 'remark-preset-prettier/lib/esm.js' {
  declare module.exports: $Exports<'remark-preset-prettier/lib/esm'>;
}
