// flow-typed signature: 6d4288b4691a6c971c044a8973bf1bbd
// flow-typed version: <<STUB>>/remark-lint-first-heading-level_v^2.0.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-lint-first-heading-level'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-lint-first-heading-level' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remark-lint-first-heading-level/index' {
  declare module.exports: $Exports<'remark-lint-first-heading-level'>;
}
declare module 'remark-lint-first-heading-level/index.js' {
  declare module.exports: $Exports<'remark-lint-first-heading-level'>;
}
