// flow-typed signature: 966cd2d5231e80c9140be7e1aaeaa187
// flow-typed version: <<STUB>>/remark-validate-links_v^10.0.2/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remark-validate-links'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remark-validate-links' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remark-validate-links/lib/check/check-files.browser' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/check/check-files' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/check' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/check/merge-landmarks' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/check/merge-references' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/check/validate' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/constants' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/find/config' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/find/find-repo.browser' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/find/find-repo' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/find/find' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib/find' {
  declare module.exports: any;
}

declare module 'remark-validate-links/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remark-validate-links/index' {
  declare module.exports: $Exports<'remark-validate-links'>;
}
declare module 'remark-validate-links/index.js' {
  declare module.exports: $Exports<'remark-validate-links'>;
}
declare module 'remark-validate-links/lib/check/check-files.browser.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/check/check-files.browser'>;
}
declare module 'remark-validate-links/lib/check/check-files.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/check/check-files'>;
}
declare module 'remark-validate-links/lib/check/index' {
  declare module.exports: $Exports<'remark-validate-links/lib/check'>;
}
declare module 'remark-validate-links/lib/check/index.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/check'>;
}
declare module 'remark-validate-links/lib/check/merge-landmarks.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/check/merge-landmarks'>;
}
declare module 'remark-validate-links/lib/check/merge-references.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/check/merge-references'>;
}
declare module 'remark-validate-links/lib/check/validate.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/check/validate'>;
}
declare module 'remark-validate-links/lib/constants.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/constants'>;
}
declare module 'remark-validate-links/lib/find/config.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/find/config'>;
}
declare module 'remark-validate-links/lib/find/find-repo.browser.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/find/find-repo.browser'>;
}
declare module 'remark-validate-links/lib/find/find-repo.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/find/find-repo'>;
}
declare module 'remark-validate-links/lib/find/find.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/find/find'>;
}
declare module 'remark-validate-links/lib/find/index' {
  declare module.exports: $Exports<'remark-validate-links/lib/find'>;
}
declare module 'remark-validate-links/lib/find/index.js' {
  declare module.exports: $Exports<'remark-validate-links/lib/find'>;
}
declare module 'remark-validate-links/lib/index' {
  declare module.exports: $Exports<'remark-validate-links/lib'>;
}
declare module 'remark-validate-links/lib/index.js' {
  declare module.exports: $Exports<'remark-validate-links/lib'>;
}
