// flow-typed signature: b6a275127b00bd5f4f5360b563ce0325
// flow-typed version: <<STUB>>/rimraf_v^3.0.2/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rimraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rimraf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rimraf/bin' {
  declare module.exports: any;
}

declare module 'rimraf/rimraf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rimraf/bin.js' {
  declare module.exports: $Exports<'rimraf/bin'>;
}
declare module 'rimraf/rimraf.js' {
  declare module.exports: $Exports<'rimraf/rimraf'>;
}
