// flow-typed signature: 17a964bd6b4e07a47536f427557ea194
// flow-typed version: <<STUB>>/sharp_v^0.27.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sharp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sharp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sharp/install/dll-copy' {
  declare module.exports: any;
}

declare module 'sharp/install/libvips' {
  declare module.exports: any;
}

declare module 'sharp/lib/agent' {
  declare module.exports: any;
}

declare module 'sharp/lib/channel' {
  declare module.exports: any;
}

declare module 'sharp/lib/colour' {
  declare module.exports: any;
}

declare module 'sharp/lib/composite' {
  declare module.exports: any;
}

declare module 'sharp/lib/constructor' {
  declare module.exports: any;
}

declare module 'sharp/lib' {
  declare module.exports: any;
}

declare module 'sharp/lib/input' {
  declare module.exports: any;
}

declare module 'sharp/lib/is' {
  declare module.exports: any;
}

declare module 'sharp/lib/libvips' {
  declare module.exports: any;
}

declare module 'sharp/lib/operation' {
  declare module.exports: any;
}

declare module 'sharp/lib/output' {
  declare module.exports: any;
}

declare module 'sharp/lib/platform' {
  declare module.exports: any;
}

declare module 'sharp/lib/resize' {
  declare module.exports: any;
}

declare module 'sharp/lib/utility' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sharp/install/dll-copy.js' {
  declare module.exports: $Exports<'sharp/install/dll-copy'>;
}
declare module 'sharp/install/libvips.js' {
  declare module.exports: $Exports<'sharp/install/libvips'>;
}
declare module 'sharp/lib/agent.js' {
  declare module.exports: $Exports<'sharp/lib/agent'>;
}
declare module 'sharp/lib/channel.js' {
  declare module.exports: $Exports<'sharp/lib/channel'>;
}
declare module 'sharp/lib/colour.js' {
  declare module.exports: $Exports<'sharp/lib/colour'>;
}
declare module 'sharp/lib/composite.js' {
  declare module.exports: $Exports<'sharp/lib/composite'>;
}
declare module 'sharp/lib/constructor.js' {
  declare module.exports: $Exports<'sharp/lib/constructor'>;
}
declare module 'sharp/lib/index' {
  declare module.exports: $Exports<'sharp/lib'>;
}
declare module 'sharp/lib/index.js' {
  declare module.exports: $Exports<'sharp/lib'>;
}
declare module 'sharp/lib/input.js' {
  declare module.exports: $Exports<'sharp/lib/input'>;
}
declare module 'sharp/lib/is.js' {
  declare module.exports: $Exports<'sharp/lib/is'>;
}
declare module 'sharp/lib/libvips.js' {
  declare module.exports: $Exports<'sharp/lib/libvips'>;
}
declare module 'sharp/lib/operation.js' {
  declare module.exports: $Exports<'sharp/lib/operation'>;
}
declare module 'sharp/lib/output.js' {
  declare module.exports: $Exports<'sharp/lib/output'>;
}
declare module 'sharp/lib/platform.js' {
  declare module.exports: $Exports<'sharp/lib/platform'>;
}
declare module 'sharp/lib/resize.js' {
  declare module.exports: $Exports<'sharp/lib/resize'>;
}
declare module 'sharp/lib/utility.js' {
  declare module.exports: $Exports<'sharp/lib/utility'>;
}
