// flow-typed signature: d23ce0f29870158ce060c137d8a2c323
// flow-typed version: <<STUB>>/surge_v^0.21.7/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'surge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'surge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'surge/lib/cli' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/auth' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/card' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/creds' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/deploy' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/discovery' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/domain' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/domainOrSilent' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/email' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/endpoint' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/help' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/ipaddress' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/list' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/log' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/login' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/logout' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/payment' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/pemOrSilent' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/pkg' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/plan' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/plans' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/plus' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/prep' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/project' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/protocol' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/setcard' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/shorthand' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/size' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/ssl' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/stats' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/subscribe' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/subscription' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/teardown' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/token' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/tokencheck' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/util/creds' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/util/helpers' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/util/skin' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/version' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/welcome' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/whitelist' {
  declare module.exports: any;
}

declare module 'surge/lib/middleware/whoami' {
  declare module.exports: any;
}

declare module 'surge/lib/surge' {
  declare module.exports: any;
}

declare module 'surge/test/actions' {
  declare module.exports: any;
}

declare module 'surge/test/basic' {
  declare module.exports: any;
}

declare module 'surge/test/cname' {
  declare module.exports: any;
}

declare module 'surge/test/fixtures/bin/commander-no-args' {
  declare module.exports: any;
}

declare module 'surge/test/fixtures/bin/commander-no-hooks' {
  declare module.exports: any;
}

declare module 'surge/test/fixtures/bin/minimist' {
  declare module.exports: any;
}

declare module 'surge/test/fixtures/bin/yargs' {
  declare module.exports: any;
}

declare module 'surge/test/plus' {
  declare module.exports: any;
}

declare module 'surge/test/publish' {
  declare module.exports: any;
}

declare module 'surge/test/teardown' {
  declare module.exports: any;
}

declare module 'surge/test/welcome' {
  declare module.exports: any;
}

// Filename aliases
declare module 'surge/lib/cli.js' {
  declare module.exports: $Exports<'surge/lib/cli'>;
}
declare module 'surge/lib/middleware/auth.js' {
  declare module.exports: $Exports<'surge/lib/middleware/auth'>;
}
declare module 'surge/lib/middleware/card.js' {
  declare module.exports: $Exports<'surge/lib/middleware/card'>;
}
declare module 'surge/lib/middleware/creds.js' {
  declare module.exports: $Exports<'surge/lib/middleware/creds'>;
}
declare module 'surge/lib/middleware/deploy.js' {
  declare module.exports: $Exports<'surge/lib/middleware/deploy'>;
}
declare module 'surge/lib/middleware/discovery.js' {
  declare module.exports: $Exports<'surge/lib/middleware/discovery'>;
}
declare module 'surge/lib/middleware/domain.js' {
  declare module.exports: $Exports<'surge/lib/middleware/domain'>;
}
declare module 'surge/lib/middleware/domainOrSilent.js' {
  declare module.exports: $Exports<'surge/lib/middleware/domainOrSilent'>;
}
declare module 'surge/lib/middleware/email.js' {
  declare module.exports: $Exports<'surge/lib/middleware/email'>;
}
declare module 'surge/lib/middleware/endpoint.js' {
  declare module.exports: $Exports<'surge/lib/middleware/endpoint'>;
}
declare module 'surge/lib/middleware/help.js' {
  declare module.exports: $Exports<'surge/lib/middleware/help'>;
}
declare module 'surge/lib/middleware/index' {
  declare module.exports: $Exports<'surge/lib/middleware'>;
}
declare module 'surge/lib/middleware/index.js' {
  declare module.exports: $Exports<'surge/lib/middleware'>;
}
declare module 'surge/lib/middleware/ipaddress.js' {
  declare module.exports: $Exports<'surge/lib/middleware/ipaddress'>;
}
declare module 'surge/lib/middleware/list.js' {
  declare module.exports: $Exports<'surge/lib/middleware/list'>;
}
declare module 'surge/lib/middleware/log.js' {
  declare module.exports: $Exports<'surge/lib/middleware/log'>;
}
declare module 'surge/lib/middleware/login.js' {
  declare module.exports: $Exports<'surge/lib/middleware/login'>;
}
declare module 'surge/lib/middleware/logout.js' {
  declare module.exports: $Exports<'surge/lib/middleware/logout'>;
}
declare module 'surge/lib/middleware/payment.js' {
  declare module.exports: $Exports<'surge/lib/middleware/payment'>;
}
declare module 'surge/lib/middleware/pemOrSilent.js' {
  declare module.exports: $Exports<'surge/lib/middleware/pemOrSilent'>;
}
declare module 'surge/lib/middleware/pkg.js' {
  declare module.exports: $Exports<'surge/lib/middleware/pkg'>;
}
declare module 'surge/lib/middleware/plan.js' {
  declare module.exports: $Exports<'surge/lib/middleware/plan'>;
}
declare module 'surge/lib/middleware/plans.js' {
  declare module.exports: $Exports<'surge/lib/middleware/plans'>;
}
declare module 'surge/lib/middleware/plus.js' {
  declare module.exports: $Exports<'surge/lib/middleware/plus'>;
}
declare module 'surge/lib/middleware/prep.js' {
  declare module.exports: $Exports<'surge/lib/middleware/prep'>;
}
declare module 'surge/lib/middleware/project.js' {
  declare module.exports: $Exports<'surge/lib/middleware/project'>;
}
declare module 'surge/lib/middleware/protocol.js' {
  declare module.exports: $Exports<'surge/lib/middleware/protocol'>;
}
declare module 'surge/lib/middleware/setcard.js' {
  declare module.exports: $Exports<'surge/lib/middleware/setcard'>;
}
declare module 'surge/lib/middleware/shorthand.js' {
  declare module.exports: $Exports<'surge/lib/middleware/shorthand'>;
}
declare module 'surge/lib/middleware/size.js' {
  declare module.exports: $Exports<'surge/lib/middleware/size'>;
}
declare module 'surge/lib/middleware/ssl.js' {
  declare module.exports: $Exports<'surge/lib/middleware/ssl'>;
}
declare module 'surge/lib/middleware/stats.js' {
  declare module.exports: $Exports<'surge/lib/middleware/stats'>;
}
declare module 'surge/lib/middleware/subscribe.js' {
  declare module.exports: $Exports<'surge/lib/middleware/subscribe'>;
}
declare module 'surge/lib/middleware/subscription.js' {
  declare module.exports: $Exports<'surge/lib/middleware/subscription'>;
}
declare module 'surge/lib/middleware/teardown.js' {
  declare module.exports: $Exports<'surge/lib/middleware/teardown'>;
}
declare module 'surge/lib/middleware/token.js' {
  declare module.exports: $Exports<'surge/lib/middleware/token'>;
}
declare module 'surge/lib/middleware/tokencheck.js' {
  declare module.exports: $Exports<'surge/lib/middleware/tokencheck'>;
}
declare module 'surge/lib/middleware/util/creds.js' {
  declare module.exports: $Exports<'surge/lib/middleware/util/creds'>;
}
declare module 'surge/lib/middleware/util/helpers.js' {
  declare module.exports: $Exports<'surge/lib/middleware/util/helpers'>;
}
declare module 'surge/lib/middleware/util/skin.js' {
  declare module.exports: $Exports<'surge/lib/middleware/util/skin'>;
}
declare module 'surge/lib/middleware/version.js' {
  declare module.exports: $Exports<'surge/lib/middleware/version'>;
}
declare module 'surge/lib/middleware/welcome.js' {
  declare module.exports: $Exports<'surge/lib/middleware/welcome'>;
}
declare module 'surge/lib/middleware/whitelist.js' {
  declare module.exports: $Exports<'surge/lib/middleware/whitelist'>;
}
declare module 'surge/lib/middleware/whoami.js' {
  declare module.exports: $Exports<'surge/lib/middleware/whoami'>;
}
declare module 'surge/lib/surge.js' {
  declare module.exports: $Exports<'surge/lib/surge'>;
}
declare module 'surge/test/actions.js' {
  declare module.exports: $Exports<'surge/test/actions'>;
}
declare module 'surge/test/basic.js' {
  declare module.exports: $Exports<'surge/test/basic'>;
}
declare module 'surge/test/cname.js' {
  declare module.exports: $Exports<'surge/test/cname'>;
}
declare module 'surge/test/fixtures/bin/commander-no-args.js' {
  declare module.exports: $Exports<'surge/test/fixtures/bin/commander-no-args'>;
}
declare module 'surge/test/fixtures/bin/commander-no-hooks.js' {
  declare module.exports: $Exports<'surge/test/fixtures/bin/commander-no-hooks'>;
}
declare module 'surge/test/fixtures/bin/minimist.js' {
  declare module.exports: $Exports<'surge/test/fixtures/bin/minimist'>;
}
declare module 'surge/test/fixtures/bin/yargs.js' {
  declare module.exports: $Exports<'surge/test/fixtures/bin/yargs'>;
}
declare module 'surge/test/plus.js' {
  declare module.exports: $Exports<'surge/test/plus'>;
}
declare module 'surge/test/publish.js' {
  declare module.exports: $Exports<'surge/test/publish'>;
}
declare module 'surge/test/teardown.js' {
  declare module.exports: $Exports<'surge/test/teardown'>;
}
declare module 'surge/test/welcome.js' {
  declare module.exports: $Exports<'surge/test/welcome'>;
}
