// flow-typed signature: 794b5b137021ae5c8280422903655ec7
// flow-typed version: <<STUB>>/svg2ttf_v^5.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'svg2ttf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'svg2ttf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'svg2ttf/lib/math' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/sfnt' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/str' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/svg' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/cmap' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/glyf' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/gsub' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/head' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/hhea' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/hmtx' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/loca' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/maxp' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/name' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/os2' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/tables/post' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ttf/utils' {
  declare module.exports: any;
}

declare module 'svg2ttf/lib/ucs2' {
  declare module.exports: any;
}

declare module 'svg2ttf/svg2ttf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'svg2ttf/index' {
  declare module.exports: $Exports<'svg2ttf'>;
}
declare module 'svg2ttf/index.js' {
  declare module.exports: $Exports<'svg2ttf'>;
}
declare module 'svg2ttf/lib/math.js' {
  declare module.exports: $Exports<'svg2ttf/lib/math'>;
}
declare module 'svg2ttf/lib/sfnt.js' {
  declare module.exports: $Exports<'svg2ttf/lib/sfnt'>;
}
declare module 'svg2ttf/lib/str.js' {
  declare module.exports: $Exports<'svg2ttf/lib/str'>;
}
declare module 'svg2ttf/lib/svg.js' {
  declare module.exports: $Exports<'svg2ttf/lib/svg'>;
}
declare module 'svg2ttf/lib/ttf.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf'>;
}
declare module 'svg2ttf/lib/ttf/tables/cmap.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/cmap'>;
}
declare module 'svg2ttf/lib/ttf/tables/glyf.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/glyf'>;
}
declare module 'svg2ttf/lib/ttf/tables/gsub.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/gsub'>;
}
declare module 'svg2ttf/lib/ttf/tables/head.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/head'>;
}
declare module 'svg2ttf/lib/ttf/tables/hhea.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/hhea'>;
}
declare module 'svg2ttf/lib/ttf/tables/hmtx.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/hmtx'>;
}
declare module 'svg2ttf/lib/ttf/tables/loca.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/loca'>;
}
declare module 'svg2ttf/lib/ttf/tables/maxp.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/maxp'>;
}
declare module 'svg2ttf/lib/ttf/tables/name.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/name'>;
}
declare module 'svg2ttf/lib/ttf/tables/os2.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/os2'>;
}
declare module 'svg2ttf/lib/ttf/tables/post.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/tables/post'>;
}
declare module 'svg2ttf/lib/ttf/utils.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ttf/utils'>;
}
declare module 'svg2ttf/lib/ucs2.js' {
  declare module.exports: $Exports<'svg2ttf/lib/ucs2'>;
}
declare module 'svg2ttf/svg2ttf.js' {
  declare module.exports: $Exports<'svg2ttf/svg2ttf'>;
}
