// flow-typed signature: 002bded5490389b9d56fd313a9f6d7c3
// flow-typed version: <<STUB>>/webpack-cli_v^4.1.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-cli/bin/cli' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/bootstrap' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/plugins/CLIPlugin' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/__tests__/get-package-manager.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/__tests__/prompt-installation.test' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/capitalize-first-letter' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/dynamic-import-loader' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/get-package-manager' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/logger' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/package-exists' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/prompt-installation' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/run-command' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/utils/to-kebab-case' {
  declare module.exports: any;
}

declare module 'webpack-cli/lib/webpack-cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-cli/bin/cli.js' {
  declare module.exports: $Exports<'webpack-cli/bin/cli'>;
}
declare module 'webpack-cli/lib/bootstrap.js' {
  declare module.exports: $Exports<'webpack-cli/lib/bootstrap'>;
}
declare module 'webpack-cli/lib/index' {
  declare module.exports: $Exports<'webpack-cli/lib'>;
}
declare module 'webpack-cli/lib/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib'>;
}
declare module 'webpack-cli/lib/plugins/CLIPlugin.js' {
  declare module.exports: $Exports<'webpack-cli/lib/plugins/CLIPlugin'>;
}
declare module 'webpack-cli/lib/utils/__tests__/get-package-manager.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/__tests__/get-package-manager.test'>;
}
declare module 'webpack-cli/lib/utils/__tests__/prompt-installation.test.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/__tests__/prompt-installation.test'>;
}
declare module 'webpack-cli/lib/utils/capitalize-first-letter.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/capitalize-first-letter'>;
}
declare module 'webpack-cli/lib/utils/dynamic-import-loader.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/dynamic-import-loader'>;
}
declare module 'webpack-cli/lib/utils/get-package-manager.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/get-package-manager'>;
}
declare module 'webpack-cli/lib/utils/index' {
  declare module.exports: $Exports<'webpack-cli/lib/utils'>;
}
declare module 'webpack-cli/lib/utils/index.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils'>;
}
declare module 'webpack-cli/lib/utils/logger.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/logger'>;
}
declare module 'webpack-cli/lib/utils/package-exists.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/package-exists'>;
}
declare module 'webpack-cli/lib/utils/prompt-installation.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/prompt-installation'>;
}
declare module 'webpack-cli/lib/utils/run-command.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/run-command'>;
}
declare module 'webpack-cli/lib/utils/to-kebab-case.js' {
  declare module.exports: $Exports<'webpack-cli/lib/utils/to-kebab-case'>;
}
declare module 'webpack-cli/lib/webpack-cli.js' {
  declare module.exports: $Exports<'webpack-cli/lib/webpack-cli'>;
}
