name: Node
description: "Installs and caches Node dependencies and Cypress"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "18"

    - name: Restore cache
      uses: actions/cache@v3
      with:
        path: |
          **/node_modules
          ~/.cache/Cypress
        key: node-modules-${{ github.ref}}-${{ hashFiles('**/yarn.lock', '.yarnclean') }}
        restore-keys: |
          node-modules-${{ github.ref}}-
          node-modules-

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash
