name: Node
description: "Installs and caches Node dependencies and Cypress"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: "22"

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Install docs dependencies
      run: cd docs && yarn install --frozen-lockfile
      shell: bash
