export enum NAME_OPTIONS {
  AIRHELP = "AirHelp",
  AIRHELPPLUS = "AirHelpPlus",
  ALIPAY = "Alipay",
  AMEX = "Amex",
  APPLEPAY = "ApplePay",
  AXA = "Axa",
  AXAASSISTANCE = "AxaAssistance",
  AXAWHITE = "AxaWhite",
  BOOKING = "Booking",
  BUSINESSINSIDER = "BusinessInsider",
  CHINAUNIONPAY = "ChinaUnionPay",
  DAILYEXPRESS = "DailyExpress",
  DINERSCLUB = "DinersClub",
  DISCOVER = "Discover",
  GETYOURGUIDE = "GetYourGuide",
  GETYOURGUIDELONG = "GetYourGuideLong",
  GOOGLEPAY = "GooglePay",
  IATA = "IATA",
  JCB = "JCB",
  MAILONLINE = "MailOnline",
  MAESTRO = "Maestro",
  MAESTROSHORT = "MaestroShort",
  MASTERCARD = "MasterCard",
  MASTERCARDSHORT = "MasterCardShort",
  MIR = "MIR",
  MIRROR = "Mirror",
  NEWYORKTIMES = "NewYorkTimes",
  NORTOSECURED = "NortonSecured",
  PAYPAL = "PayPal",
  RENTALCARS = "RentalCars",
  SHERPA = "Sherpa",
  SIMTEX = "Simtex",
  SOFORT = "Sofort",
  TRAVELPULSE = "TravelPulse",
  TRUSTLY = "Trustly",
  USATODAY = "UsaToday",
  VISA = "Visa",
  VISAHQ = "VisaHQ",
  ZOOZ = "Zooz",
  ELO = "Elo",
  KIWI_GUARANTEE = "KiwiGuarantee",
  KIWI_GUARANTEE_FULL = "KiwiGuaranteeFull",
  KIWI_GUARANTEE_INLINE = "KiwiGuaranteeInline",
}

export enum SIZE_OPTIONS {
  SMALL = "small",
  MEDIUM = "medium",
  LARGE = "large",
}

export const baseURL = "//images.kiwi.com";
