export enum NAME_OPTIONS {
  AIRHELP = "AirHelp",
  ALIPAY = "Alipay",
  AMEX = "Amex",
  AXA = "Axa",
  AXAASSISTANCE = "AxaAssistance",
  BOOKING = "Booking",
  BUSINESSINSIDER = "BusinessInsider",
  CHINAUNIONPAY = "ChinaUnionPay",
  DAILYEXPRESS = "DailyExpress",
  DINERSCLUB = "DinersClub",
  DISCOVER = "Discover",
  IATA = "IATA",
  JCB = "JCB",
  MAILONLINE = "MailOnline",
  MAESTRO = "Maestro",
  MAESTROSHORT = "MaestroShort",
  MASTERCARD = "MasterCard",
  MASTERCARDSHORT = "MasterCardShort",
  MIR = "MIR",
  MIRROR = "Mirror",
  NEWYORKTIMES = "NewYorkTimes",
  NORTOSECURED = "NortonSecured",
  PAYPAL = "PayPal",
  RENTALCARS = "RentalCars",
  SOFORT = "Sofort",
  TRAVELPULSE = "TravelPulse",
  TRUSTLY = "Trustly",
  USATODAY = "UsaToday",
  VISA = "Visa",
  VISAHQ = "VisaHQ",
  ZOOZ = "Zooz",
  ELO = "Elo",
}

export enum SIZE_OPTIONS {
  SMALL = "small",
  MEDIUM = "medium",
  LARGE = "large",
}

export const baseURL = "//images.kiwi.com";
