// @flow

export const NAMES = [
  "Accommodation",
  "AirHelp",
  "AirportTransport", // TODO: Get rid off 22.11
  "AirportTransportTaxi", // TODO: Get rid off 22.11
  "AirportShuttle",
  "BaggageDrop",
  "BGYFastTrack",
  "Boarding",
  "BoardingPass",
  "BUDFastTrack",
  "BusinessTravel",
  "CabinBaggage",
  "DesktopSearch",
  "EnjoyApp",
  "Error",
  "Error404",
  "FastTrack",
  "Feedback",
  "Help",
  "Improve",
  "Insurance",
  "InviteAFriend",
  "Login",
  "Lounge",
  "Mailbox",
  "Meal",
  "MobileApp",
  "Money",
  "MusicalInstruments",
  "NCEFastTrack",
  "NetVerify",
  "NoBookings", // TODO: Get rid off 22.11
  "NoFavoriteFlights",
  "Nomad",
  "NoNotification",
  "NoResults",
  "Offline",
  "OnlineCheckIn",
  "OpenSearch",
  "Parking",
  "Pets",
  "PlaceholderAirport",
  "PlaceholderDestination",
  "PlaceholderHotel",
  "PlaceholderTours",
  "PlaneAndMoney",
  "PriorityBoarding",
  "Rating",
  "ReferAFriend",
  "RentalCar",
  "Seating",
  "SpecialAssistance",
  "SportsEquipment",
  "Success",
  "Time",
  "TimelineBoarding", // TODO: Get rid off 22.11
  "TimelineDropBaggage", // TODO: Get rid off 22.11
  "TimelineLeave",
  "TimelinePick",
  "Tours",
  "Train",
  "TransportBus",
  "TransportTaxi",
];
export const SIZE_OPTIONS = {
  SMALL: "small",
  MEDIUM: "medium",
  LARGE: "large",
};

export const baseURL = "//images.kiwi.com";
