import { defaultTokens } from "@kiwicom/orbit-design-tokens";

const cssVarsFoundation = {
  palette: {
    product: {
      normal: `var(--palette-product-normal, ${defaultTokens.paletteProductNormal})`,
      normalHover: `var(--palette-product-normal-hover, ${defaultTokens.paletteProductNormalHover})`,
      normalActive: `var(--palette-product-normal-active, ${defaultTokens.paletteProductNormalActive})`,
      light: `var(--palette-product-light, ${defaultTokens.paletteProductLight})`,
      lightHover: `var(--palette-product-light-hover, ${defaultTokens.paletteProductLightHover})`,
      lightActive: `var(--palette-product-light-active, ${defaultTokens.paletteProductLightActive})`,
      dark: `var(--palette-product-dark, ${defaultTokens.paletteProductDark})`,
      darkHover: `var(--palette-product-dark-hover, ${defaultTokens.paletteProductDarkHover})`,
      darkActive: `var(--palette-product-dark-active, ${defaultTokens.paletteProductDarkActive})`,
      darker: `var(--palette-product-darker, ${defaultTokens.paletteProductDarker})`,
    },
    blue: {
      normal: `var(--palette-blue-normal, ${defaultTokens.paletteBlueNormal})`,
      normalHover: `var(--palette-blue-normal-hover, ${defaultTokens.paletteBlueNormalHover})`,
      normalActive: `var(--palette-blue-normal-active, ${defaultTokens.paletteBlueNormalActive})`,
      light: `var(--palette-blue-light, ${defaultTokens.paletteBlueLight})`,
      lightHover: `var(--palette-blue-light-hover, ${defaultTokens.paletteBlueLightHover})`,
      lightActive: `var(--palette-blue-light-active, ${defaultTokens.paletteBlueLightActive})`,
      dark: `var(--palette-blue-dark, ${defaultTokens.paletteBlueDark})`,
      darkHover: `var(--palette-blue-dark-hover, ${defaultTokens.paletteBlueDarkHover})`,
      darkActive: `var(--palette-blue-dark-active, ${defaultTokens.paletteBlueDarkActive})`,
      darker: `var(--palette-blue-darker, ${defaultTokens.paletteBlueDarker})`,
    },
    bundle: {
      basic: `var(--palette-bundle-basic, ${defaultTokens.paletteBundleBasic})`,
      medium: `var(--palette-bundle-medium, ${defaultTokens.paletteBundleMedium})`,
    },
    cloud: {
      normal: `var(--palette-cloud-normal, ${defaultTokens.paletteCloudNormal})`,
      normalHover: `var(--palette-cloud-normal-hover, ${defaultTokens.paletteCloudNormalHover})`,
      normalActive: `var(--palette-cloud-normal-active, ${defaultTokens.paletteCloudNormalActive})`,
      light: `var(--palette-cloud-light, ${defaultTokens.paletteCloudLight})`,
      lightHover: `var(--palette-cloud-light-hover, ${defaultTokens.paletteCloudLightHover})`,
      lightActive: `var(--palette-cloud-light-active, ${defaultTokens.paletteCloudLightActive})`,
      dark: `var(--palette-cloud-dark, ${defaultTokens.paletteCloudDark})`,
      darkHover: `var(--palette-cloud-dark-hover, ${defaultTokens.paletteCloudDarkHover})`,
      darkActive: `var(--palette-cloud-dark-active, ${defaultTokens.paletteCloudDarkActive})`,
    },
    green: {
      normal: `var(--palette-green-normal, ${defaultTokens.paletteGreenNormal})`,
      normalHover: `var(--palette-green-normal-hover, ${defaultTokens.paletteGreenNormalHover})`,
      normalActive: `var(--palette-green-normal-active, ${defaultTokens.paletteGreenNormalActive})`,
      light: `var(--palette-green-light, ${defaultTokens.paletteGreenLight})`,
      lightHover: `var(--palette-green-light-hover, ${defaultTokens.paletteGreenLightHover})`,
      lightActive: `var(--palette-green-light-active, ${defaultTokens.paletteGreenLightActive})`,
      dark: `var(--palette-green-dark, ${defaultTokens.paletteGreenDark})`,
      darkHover: `var(--palette-green-dark-hover, ${defaultTokens.paletteGreenDarkHover})`,
      darkActive: `var(--palette-green-dark-active, ${defaultTokens.paletteGreenDarkActive})`,
      darker: `var(--palette-green-darker, ${defaultTokens.paletteGreenDarker})`,
    },
    ink: {
      normal: `var(--palette-ink-normal, ${defaultTokens.paletteInkNormal})`,
      normalHover: `var(--palette-ink-normal-hover, ${defaultTokens.paletteInkNormalHover})`,
      normalActive: `var(--palette-ink-normal-active, ${defaultTokens.paletteInkNormalActive})`,
      light: `var(--palette-ink-light, ${defaultTokens.paletteInkLight})`,
      lightHover: `var(--palette-ink-light-hover, ${defaultTokens.paletteInkLightHover})`,
      lightActive: `var(--palette-ink-light-active, ${defaultTokens.paletteInkLightActive})`,
      dark: `var(--palette-ink-dark, ${defaultTokens.paletteInkDark})`,
      darkHover: `var(--palette-ink-dark-hover, ${defaultTokens.paletteInkDarkHover})`,
      darkActive: `var(--palette-ink-dark-active, ${defaultTokens.paletteInkDarkActive})`,
    },
    orange: {
      normal: `var(--palette-orange-normal, ${defaultTokens.paletteOrangeNormal})`,
      normalHover: `var(--palette-orange-normal-hover, ${defaultTokens.paletteOrangeNormalHover})`,
      normalActive: `var(--palette-orange-normal-active, ${defaultTokens.paletteOrangeNormalActive})`,
      light: `var(--palette-orange-light, ${defaultTokens.paletteOrangeLight})`,
      lightHover: `var(--palette-orange-light-hover, ${defaultTokens.paletteOrangeLightHover})`,
      lightActive: `var(--palette-orange-light-active, ${defaultTokens.paletteOrangeLightActive})`,
      dark: `var(--palette-orange-dark, ${defaultTokens.paletteOrangeDark})`,
      darkHover: `var(--palette-orange-dark-hover, ${defaultTokens.paletteOrangeDarkHover})`,
      darkActive: `var(--palette-orange-dark-active, ${defaultTokens.paletteOrangeDarkActive})`,
      darker: `var(--palette-orange-darker, ${defaultTokens.paletteOrangeDarker})`,
    },
    red: {
      normal: `var(--palette-red-normal, ${defaultTokens.paletteRedNormal})`,
      normalHover: `var(--palette-red-normal-hover, ${defaultTokens.paletteRedNormalHover})`,
      normalActive: `var(--palette-red-normal-active, ${defaultTokens.paletteRedNormalActive})`,
      light: `var(--palette-red-light, ${defaultTokens.paletteRedLight})`,
      lightHover: `var(--palette-red-light-hover, ${defaultTokens.paletteRedLightHover})`,
      lightActive: `var(--palette-red-light-active, ${defaultTokens.paletteRedLightActive})`,
      dark: `var(--palette-red-dark, ${defaultTokens.paletteRedDark})`,
      darkHover: `var(--palette-red-dark-hover, ${defaultTokens.paletteRedDarkHover})`,
      darkActive: `var(--palette-red-dark-active, ${defaultTokens.paletteRedDarkActive})`,
      darker: `var(--palette-red-darker, ${defaultTokens.paletteRedDarker})`,
    },
    social: {
      facebook: `var(--palette-social-facebook, ${defaultTokens.paletteSocialFacebook})`,
      facebookHover: `var(--palette-social-facebook-hover, ${defaultTokens.paletteSocialFacebookHover})`,
      facebookActive: `var(--palette-social-facebook-active, ${defaultTokens.paletteSocialFacebookActive})`,
    },
    white: {
      normal: `var(--palette-white-normal, ${defaultTokens.paletteWhiteNormal})`,
      normalHover: `var(--palette-white-normal-hover, ${defaultTokens.paletteWhiteHover})`,
      normalActive: `var(--palette-white-normal-active, ${defaultTokens.paletteWhiteActive})`,
    },
  },
};

export default cssVarsFoundation;
