import type { CSSVarsFoundation } from ".";

const getTailwindTheme = (foundation: CSSVarsFoundation) => {
  return {
    colors: {
      transparent: "transparent",
      blue: {
        dark: foundation.palette.blue.dark,
        "dark-active": foundation.palette.blue.darkActive,
        "dark-hover": foundation.palette.blue.darkHover,
        darker: foundation.palette.blue.darker,
        light: foundation.palette.blue.light,
        "light-active": foundation.palette.blue.lightActive,
        "light-hover": foundation.palette.blue.lightHover,
        normal: foundation.palette.blue.normal,
        "normal-active": foundation.palette.blue.normalActive,
        "normal-hover": foundation.palette.blue.normalHover,
      },
      bundle: {
        basic: foundation.palette.bundle.basic,
        medium: foundation.palette.bundle.medium,
      },
      cloud: {
        dark: foundation.palette.cloud.dark,
        "dark-active": foundation.palette.cloud.darkActive,
        "dark-hover": foundation.palette.cloud.darkHover,
        light: foundation.palette.cloud.light,
        "light-active": foundation.palette.cloud.lightActive,
        "light-hover": foundation.palette.cloud.lightHover,
        normal: foundation.palette.cloud.normal,
        "normal-active": foundation.palette.cloud.normalActive,
        "normal-hover": foundation.palette.cloud.normalHover,
      },
      green: {
        dark: foundation.palette.green.dark,
        "dark-active": foundation.palette.green.darkActive,
        "dark-hover": foundation.palette.green.darkHover,
        darker: foundation.palette.green.darker,
        light: foundation.palette.green.light,
        "light-active": foundation.palette.green.lightActive,
        "light-hover": foundation.palette.green.lightHover,
        normal: foundation.palette.green.normal,
        "normal-active": foundation.palette.green.normalActive,
        "normal-hover": foundation.palette.green.normalHover,
      },
      ink: {
        dark: foundation.palette.ink.dark,
        "dark-active": foundation.palette.ink.darkActive,
        "dark-hover": foundation.palette.ink.darkHover,
        light: foundation.palette.ink.light,
        "light-active": foundation.palette.ink.lightActive,
        "light-hover": foundation.palette.ink.lightHover,
        normal: foundation.palette.ink.normal,
        "normal-active": foundation.palette.ink.normalActive,
        "normal-hover": foundation.palette.ink.normalHover,
      },
      orange: {
        dark: foundation.palette.orange.dark,
        "dark-active": foundation.palette.orange.darkActive,
        "dark-hover": foundation.palette.orange.darkHover,
        darker: foundation.palette.orange.darker,
        light: foundation.palette.orange.light,
        "light-active": foundation.palette.orange.lightActive,
        "light-hover": foundation.palette.orange.lightHover,
        normal: foundation.palette.orange.normal,
        "normal-active": foundation.palette.orange.normalActive,
        "normal-hover": foundation.palette.orange.normalHover,
      },
      product: {
        dark: foundation.palette.product.dark,
        "dark-active": foundation.palette.product.darkActive,
        "dark-hover": foundation.palette.product.darkHover,
        darker: foundation.palette.product.darker,
        light: foundation.palette.product.light,
        "light-active": foundation.palette.product.lightActive,
        "light-hover": foundation.palette.product.lightHover,
        normal: foundation.palette.product.normal,
        "normal-active": foundation.palette.product.normalActive,
        "normal-hover": foundation.palette.product.normalHover,
      },
      red: {
        dark: foundation.palette.red.dark,
        "dark-active": foundation.palette.red.darkActive,
        "dark-hover": foundation.palette.red.darkHover,
        darker: foundation.palette.red.darker,
        light: foundation.palette.red.light,
        "light-active": foundation.palette.red.lightActive,
        "light-hover": foundation.palette.red.lightHover,
        normal: foundation.palette.red.normal,
        "normal-active": foundation.palette.red.normalActive,
        "normal-hover": foundation.palette.red.normalHover,
      },
      social: {
        facebook: foundation.palette.social.facebook,
        "facebook-hover": foundation.palette.social.facebookHover,
        "facebook-active": foundation.palette.social.facebookActive,
      },
      white: {
        normal: foundation.palette.white.normal,
        "normal-active": foundation.palette.white.normalActive,
        "normal-hover": foundation.palette.white.normalHover,
      },
    },
    fontSize: {
      small: foundation.fontSize.small,
      normal: foundation.fontSize.normal,
      large: foundation.fontSize.large,
      "extra-large": foundation.fontSize.extraLarge,
    },
    lineHeight: {
      none: "1",
      small: foundation.lineHeight.small,
      normal: foundation.lineHeight.normal,
      large: foundation.lineHeight.large,
      "extra-large": foundation.lineHeight.extraLarge,
    },
    fontWeight: {
      normal: foundation.fontWeight.normal,
      medium: foundation.fontWeight.medium,
      bold: foundation.fontWeight.bold,
    },
    fontFamily: {
      base: foundation.fontFamily.base,
    },
    spacing: {
      none: "0px",
      0: "0px",
      px: "1px",
      xxxs: foundation.space.XXXSmall,
      xxs: foundation.space.XXSmall,
      xs: foundation.space.XSmall,
      sm: foundation.space.small,
      md: foundation.space.medium,
      lg: foundation.space.large,
      xl: foundation.space.XLarge,
      xxl: foundation.space.XXLarge,
      xxxl: foundation.space.XXXLarge,
    },
    borderRadius: {
      none: "0",
      small: foundation.borderRadius.small,
      normal: foundation.borderRadius.normal,
      large: foundation.borderRadius.large,
      circle: foundation.borderRadius.circle,
    },
    screens: {
      sm: foundation.breakpoint.smallMobile,
      mm: foundation.breakpoint.mediumMobile,
      lm: foundation.breakpoint.largeMobile,
      tb: foundation.breakpoint.tablet,
      de: foundation.breakpoint.desktop,
      ld: foundation.breakpoint.largeDesktop,
    },
    size: {
      small: foundation.size.small,
      medium: foundation.size.medium,
      large: foundation.size.large,
      "extra-large": foundation.size.extraLarge,
      "extra-extra-large": foundation.size.extraExtraLarge,
    },
  };
};

export default getTailwindTheme;
