import type { defaultFoundation } from "@kiwicom/orbit-design-tokens";

import { toPx } from "../fns";

const getTailwindFoundation = (theme: typeof defaultFoundation) => {
  return {
    palette: {
      transparent: "transparent",
      blue: {
        dark: theme.palette.blue.dark,
        "dark-active": theme.palette.blue.darkActive,
        "dark-hover": theme.palette.blue.darkHover,
        darker: theme.palette.blue.darker,
        light: theme.palette.blue.light,
        "light-active": theme.palette.blue.lightActive,
        "light-hover": theme.palette.blue.lightHover,
        normal: theme.palette.blue.normal,
        "normal-active": theme.palette.blue.normalActive,
        "normal-hover": theme.palette.blue.normalHover,
      },
      bundle: {
        basic: theme.palette.bundle.basic,
        medium: theme.palette.bundle.medium,
      },
      cloud: {
        dark: theme.palette.cloud.dark,
        "dark-active": theme.palette.cloud.darkActive,
        "dark-hover": theme.palette.cloud.darkHover,
        light: theme.palette.cloud.light,
        "light-active": theme.palette.cloud.lightActive,
        "light-hover": theme.palette.cloud.lightHover,
        normal: theme.palette.cloud.normal,
        "normal-active": theme.palette.cloud.normalActive,
        "normal-hover": theme.palette.cloud.normalHover,
      },
      green: {
        dark: theme.palette.green.dark,
        "dark-active": theme.palette.green.darkActive,
        "dark-hover": theme.palette.green.darkHover,
        darker: theme.palette.green.darker,
        light: theme.palette.green.light,
        "light-active": theme.palette.green.lightActive,
        "light-hover": theme.palette.green.lightHover,
        normal: theme.palette.green.normal,
        "normal-active": theme.palette.green.normalActive,
        "normal-hover": theme.palette.green.normalHover,
      },
      ink: {
        dark: theme.palette.ink.dark,
        "dark-active": theme.palette.ink.darkActive,
        "dark-hover": theme.palette.ink.darkHover,
        light: theme.palette.ink.light,
        "light-active": theme.palette.ink.lightActive,
        "light-hover": theme.palette.ink.lightHover,
        normal: theme.palette.ink.normal,
        "normal-active": theme.palette.ink.normalActive,
        "normal-hover": theme.palette.ink.normalHover,
      },
      orange: {
        dark: theme.palette.orange.dark,
        "dark-active": theme.palette.orange.darkActive,
        "dark-hover": theme.palette.orange.darkHover,
        darker: theme.palette.orange.darker,
        light: theme.palette.orange.light,
        "light-active": theme.palette.orange.lightActive,
        "light-hover": theme.palette.orange.lightHover,
        normal: theme.palette.orange.normal,
        "normal-active": theme.palette.orange.normalActive,
        "normal-hover": theme.palette.orange.normalHover,
      },
      product: {
        dark: theme.palette.product.dark,
        "dark-active": theme.palette.product.darkActive,
        "dark-hover": theme.palette.product.darkHover,
        darker: theme.palette.product.darker,
        light: theme.palette.product.light,
        "light-active": theme.palette.product.lightActive,
        "light-hover": theme.palette.product.lightHover,
        normal: theme.palette.product.normal,
        "normal-active": theme.palette.product.normalActive,
        "normal-hover": theme.palette.product.normalHover,
      },
      red: {
        dark: theme.palette.red.dark,
        "dark-active": theme.palette.red.darkActive,
        "dark-hover": theme.palette.red.darkHover,
        darker: theme.palette.red.darker,
        light: theme.palette.red.light,
        "light-active": theme.palette.red.lightActive,
        "light-hover": theme.palette.red.lightHover,
        normal: theme.palette.red.normal,
        "normal-active": theme.palette.red.normalActive,
        "normal-hover": theme.palette.red.normalHover,
      },
      social: {
        facebook: theme.palette.social.facebook,
        "facebook-hover": theme.palette.social.facebookHover,
        "facebook-active": theme.palette.social.facebookActive,
      },
      white: {
        normal: theme.palette.white.normal,
        "normal-active": theme.palette.white.normalActive,
        "normal-hover": theme.palette.white.normalHover,
      },
    },
    fontSize: {
      small: theme.fontSize.small,
      normal: theme.fontSize.normal,
      large: theme.fontSize.large,
      "extra-large": theme.fontSize.extraLarge,
    },
    lineHeight: {
      none: "1",
      small: theme.lineHeight.small,
      normal: theme.lineHeight.normal,
      large: theme.lineHeight.large,
      "extra-large": theme.lineHeight.extraLarge,
    },
    fontWeight: {
      normal: theme.fontWeight.normal,
      medium: theme.fontWeight.medium,
      bold: theme.fontWeight.bold,
    },
    fontFamily: {
      base: theme.fontFamily.base,
    },
    spacing: {
      none: "0px",
      0: "0px",
      px: "1px",
      xxxs: theme.space.XXXSmall,
      xxs: theme.space.XXSmall,
      xs: theme.space.XSmall,
      sm: theme.space.small,
      md: theme.space.medium,
      lg: theme.space.large,
      xl: theme.space.XLarge,
      xxl: theme.space.XXLarge,
      xxxl: theme.space.XXXLarge,
    },
    borderRadius: {
      none: "0",
      small: theme.borderRadius.small,
      normal: theme.borderRadius.normal,
      large: theme.borderRadius.large,
      circle: theme.borderRadius.circle,
    },
    screens: {
      sm: toPx(theme.breakpoint.smallMobile),
      mm: toPx(theme.breakpoint.mediumMobile),
      lm: toPx(theme.breakpoint.largeMobile),
      tb: toPx(theme.breakpoint.tablet),
      de: toPx(theme.breakpoint.desktop),
      ld: toPx(theme.breakpoint.largeDesktop),
    },
    size: {
      small: theme.size.small,
      medium: theme.size.medium,
      large: theme.size.large,
      "extra-large": theme.size.extraLarge,
      "extra-extra-large": theme.size.extraExtraLarge,
    },
  };
};

export default getTailwindFoundation;
