import type { defaultFoundation } from "@kiwicom/orbit-design-tokens";

import { toPx } from "../utils";

const getTailwindFoundation = (theme: typeof defaultFoundation) => {
  return {
    palette: {
      transparent: "transparent",
      blue: {
        dark: `var(--palette-blue-dark, ${theme.palette.blue.dark})`,
        "dark-active": `var(--palette-blue-dark-active, ${theme.palette.blue.darkActive})`,
        "dark-hover": `var(--palette-blue-dark-hover, ${theme.palette.blue.darkHover})`,
        darker: `var(--palette-blue-darker, ${theme.palette.blue.darker})`,
        light: `var(--palette-blue-light, ${theme.palette.blue.light})`,
        "light-active": `var(--palette-blue-light-active, ${theme.palette.blue.lightActive})`,
        "light-hover": `var(--palette-blue-light-hover, ${theme.palette.blue.lightHover})`,
        normal: `var(--palette-blue-normal, ${theme.palette.blue.normal})`,
        "normal-active": `var(--palette-blue-normal-active, ${theme.palette.blue.normalActive})`,
        "normal-hover": `var(--palette-blue-normal-hover, ${theme.palette.blue.normalHover})`,
      },
      bundle: {
        basic: `var(--palette-bundle-basic, ${theme.palette.bundle.basic})`,
        medium: `var(--palette-bundle-medium, ${theme.palette.bundle.medium})`,
      },
      cloud: {
        dark: `var(--palette-cloud-dark, ${theme.palette.cloud.dark})`,
        "dark-active": `var(--palette-cloud-dark-active, ${theme.palette.cloud.darkActive})`,
        "dark-hover": `var(--palette-cloud-dark-hover, ${theme.palette.cloud.darkHover})`,
        light: `var(--palette-cloud-light, ${theme.palette.cloud.light})`,
        "light-active": `var(--palette-cloud-light-active, ${theme.palette.cloud.lightActive})`,
        "light-hover": `var(--palette-cloud-light-hover, ${theme.palette.cloud.lightHover})`,
        normal: `var(--palette-cloud-normal, ${theme.palette.cloud.normal})`,
        "normal-active": `var(--palette-cloud-normal-active, ${theme.palette.cloud.normalActive})`,
        "normal-hover": `var(--palette-cloud-normal-hover, ${theme.palette.cloud.normalHover})`,
      },
      green: {
        dark: `var(--palette-green-dark, ${theme.palette.green.dark})`,
        "dark-active": `var(--palette-green-dark-active, ${theme.palette.green.darkActive})`,
        "dark-hover": `var(--palette-green-dark-hover, ${theme.palette.green.darkHover})`,
        darker: `var(--palette-green-darker, ${theme.palette.green.darker})`,
        light: `var(--palette-green-light, ${theme.palette.green.light})`,
        "light-active": `var(--palette-green-light-active, ${theme.palette.green.lightActive})`,
        "light-hover": `var(--palette-green-light-hover, ${theme.palette.green.lightHover})`,
        normal: `var(--palette-green-normal, ${theme.palette.green.normal})`,
        "normal-active": `var(--palette-green-normal-active, ${theme.palette.green.normalActive})`,
        "normal-hover": `var(--palette-green-normal-hover, ${theme.palette.green.normalHover})`,
      },
      ink: {
        dark: `var(--palette-ink-dark, ${theme.palette.ink.dark})`,
        "dark-active": `var(--palette-ink-dark-active, ${theme.palette.ink.darkActive})`,
        "dark-hover": `var(--palette-ink-dark-hover, ${theme.palette.ink.darkHover})`,
        light: `var(--palette-ink-light, ${theme.palette.ink.light})`,
        "light-active": `var(--palette-ink-light-active, ${theme.palette.ink.lightActive})`,
        "light-hover": `var(--palette-ink-light-hover, ${theme.palette.ink.lightHover})`,
        normal: `var(--palette-ink-normal, ${theme.palette.ink.normal})`,
        "normal-active": `var(--palette-ink-normal-active, ${theme.palette.ink.normalActive})`,
        "normal-hover": `var(--palette-ink-normal-hover, ${theme.palette.ink.normalHover})`,
      },
      orange: {
        dark: `var(--palette-orange-dark, ${theme.palette.orange.dark})`,
        "dark-active": `var(--palette-orange-dark-active, ${theme.palette.orange.darkActive})`,
        "dark-hover": `var(--palette-orange-dark-hover, ${theme.palette.orange.darkHover})`,
        darker: `var(--palette-orange-darker, ${theme.palette.orange.darker})`,
        light: `var(--palette-orange-light, ${theme.palette.orange.light})`,
        "light-active": `var(--palette-orange-light-active, ${theme.palette.orange.lightActive})`,
        "light-hover": `var(--palette-orange-light-hover, ${theme.palette.orange.lightHover})`,
        normal: `var(--palette-orange-normal, ${theme.palette.orange.normal})`,
        "normal-active": `var(--palette-orange-normal-active, ${theme.palette.orange.normalActive})`,
        "normal-hover": `var(--palette-orange-normal-hover, ${theme.palette.orange.normalHover})`,
      },
      product: {
        dark: `var(--palette-product-dark, ${theme.palette.product.dark})`,
        "dark-active": `var(--palette-product-dark-active, ${theme.palette.product.darkActive})`,
        "dark-hover": `var(--palette-product-dark-hover, ${theme.palette.product.darkHover})`,
        darker: `var(--palette-product-darker, ${theme.palette.product.darker})`,
        light: `var(--palette-product-light, ${theme.palette.product.light})`,
        "light-active": `var(--palette-product-light-active, ${theme.palette.product.lightActive})`,
        "light-hover": `var(--palette-product-light-hover, ${theme.palette.product.lightHover})`,
        normal: `var(--palette-product-normal, ${theme.palette.product.normal})`,
        "normal-active": `var(--palette-product-normal-active, ${theme.palette.product.normalActive})`,
        "normal-hover": `var(--palette-product-normal-hover, ${theme.palette.product.normalHover})`,
      },
      red: {
        dark: `var(--palette-red-dark, ${theme.palette.red.dark})`,
        "dark-active": `var(--palette-red-dark-active, ${theme.palette.red.darkActive})`,
        "dark-hover": `var(--palette-red-dark-hover, ${theme.palette.red.darkHover})`,
        darker: `var(--palette-red-darker, ${theme.palette.red.darker})`,
        light: `var(--palette-red-light, ${theme.palette.red.light})`,
        "light-active": `var(--palette-red-light-active, ${theme.palette.red.lightActive})`,
        "light-hover": `var(--palette-red-light-hover, ${theme.palette.red.lightHover})`,
        normal: `var(--palette-red-normal, ${theme.palette.red.normal})`,
        "normal-active": `var(--palette-red-normal-active, ${theme.palette.red.normalActive})`,
        "normal-hover": `var(--palette-red-normal-hover, ${theme.palette.red.normalHover})`,
      },
      social: {
        facebook: `var(--palette-social-facebook, ${theme.palette.social.facebook})`,
        "facebook-hover": `var(--palette-social-facebook-hover, ${theme.palette.social.facebookHover})`,
        "facebook-active": `var(--palette-social-facebook-active, ${theme.palette.social.facebookActive})`,
      },
      white: {
        normal: `var(--palette-white-normal, ${theme.palette.white.normal})`,
        "normal-active": `var(--palette-white-normal-active, ${theme.palette.white.normalActive})`,
        "normal-hover": `var(--palette-white-normal-hover, ${theme.palette.white.normalHover})`,
      },
    },
    fontSize: {
      small: theme.fontSize.small,
      normal: theme.fontSize.normal,
      large: theme.fontSize.large,
      "extra-large": theme.fontSize.extraLarge,
    },
    lineHeight: {
      none: "1",
      small: theme.lineHeight.small,
      normal: theme.lineHeight.normal,
      large: theme.lineHeight.large,
      "extra-large": theme.lineHeight.extraLarge,
    },
    fontWeight: {
      normal: theme.fontWeight.normal,
      medium: theme.fontWeight.medium,
      bold: theme.fontWeight.bold,
    },
    fontFamily: {
      base: theme.fontFamily.base,
    },
    spacing: {
      none: "0px",
      0: "0px",
      px: "1px",
      xxxs: theme.space.XXXSmall,
      xxs: theme.space.XXSmall,
      xs: theme.space.XSmall,
      sm: theme.space.small,
      md: theme.space.medium,
      lg: theme.space.large,
      xl: theme.space.XLarge,
      xxl: theme.space.XXLarge,
      xxxl: theme.space.XXXLarge,
    },
    borderRadius: {
      none: "0",
      small: theme.borderRadius.small,
      normal: theme.borderRadius.normal,
      large: theme.borderRadius.large,
      circle: theme.borderRadius.circle,
    },
    screens: {
      sm: toPx(theme.breakpoint.smallMobile),
      mm: toPx(theme.breakpoint.mediumMobile),
      lm: toPx(theme.breakpoint.largeMobile),
      tb: toPx(theme.breakpoint.tablet),
      de: toPx(theme.breakpoint.desktop),
      ld: toPx(theme.breakpoint.largeDesktop),
    },
    size: {
      small: theme.size.small,
      medium: theme.size.medium,
      large: theme.size.large,
      "extra-large": theme.size.extraLarge,
      "extra-extra-large": theme.size.extraExtraLarge,
    },
  };
};

export default getTailwindFoundation;
