import fs from "fs-extra";

import generateXMLDesignTokens from "../generateXMLDesignTokens";

jest.mock("../../src", () => ({
  defaultTokens: {
    black: "#000",
    white: "#fff",
    red: "#f00",
  },
}));

// eslint-disable-next-line @typescript-eslint/no-var-requires
jest.mock("fs", () => require("memfs").fs);

describe(generateXMLDesignTokens.name, () => {
  it("writes tokens into an XML file", () => {
    generateXMLDesignTokens();
    const content = fs.readFileSync("dist/index.xml");
    expect(content.toString()).toMatchInlineSnapshot(`
      "<designTokens>
        <token>
          <name>colorTextPrimary</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextSecondary</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>colorTextError</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>colorTextInfo</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>colorTextSuccess</name>
          <value>#28A138</value>
        </token>
        <token>
          <name>colorTextWarning</name>
          <value>#DF7B00</value>
        </token>
        <token>
          <name>colorTextCritical</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>colorTextWhite</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorIconPrimary</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorIconSecondary</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>colorIconTertiary</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>colorIconInfo</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>colorIconSuccess</name>
          <value>#28A138</value>
        </token>
        <token>
          <name>colorIconWarning</name>
          <value>#DF7B00</value>
        </token>
        <token>
          <name>colorIconCritical</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>colorHeading</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorHeadingInverted</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextLinkPrimary</name>
          <value>#007F6D</value>
        </token>
        <token>
          <name>colorTextLinkPrimaryHover</name>
          <value>#00A58E</value>
        </token>
        <token>
          <name>colorTextLinkSecondary</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextLinkSecondaryHover</name>
          <value>#00A58E</value>
        </token>
        <token>
          <name>colorAlertIconSuccess</name>
          <value>#28A138</value>
        </token>
        <token>
          <name>colorTextAlertSuccess</name>
          <value>#2D7738</value>
        </token>
        <token>
          <name>colorAlertIconInfo</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>colorTextAlertInfo</name>
          <value>#005AA3</value>
        </token>
        <token>
          <name>colorAlertIconWarning</name>
          <value>#DF7B00</value>
        </token>
        <token>
          <name>colorTextAlertWarning</name>
          <value>#BA5D00</value>
        </token>
        <token>
          <name>colorAlertIconCritical</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>colorTextAlertCritical</name>
          <value>#970C0C</value>
        </token>
        <token>
          <name>colorTextButtonFilled</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonFilledHover</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonFilledActive</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonPrimary</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonPrimaryHover</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonPrimaryActive</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonSecondary</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextButtonSecondaryHover</name>
          <value>#181B20</value>
        </token>
        <token>
          <name>colorTextButtonSecondaryActive</name>
          <value>#0B0C0F</value>
        </token>
        <token>
          <name>colorTextButtonInfo</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonInfoHover</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonInfoActive</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonSuccess</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonSuccessHover</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonSuccessActive</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonWarning</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonWarningHover</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonWarningActive</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonCritical</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonCriticalHover</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonCriticalActive</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonFacebook</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonFacebookHover</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonFacebookActive</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonGoogle</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextButtonGoogleHover</name>
          <value>#181B20</value>
        </token>
        <token>
          <name>colorTextButtonGoogleActive</name>
          <value>#0B0C0F</value>
        </token>
        <token>
          <name>colorTextButtonWhite</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextButtonWhiteHover</name>
          <value>#181B20</value>
        </token>
        <token>
          <name>colorTextButtonWhiteActive</name>
          <value>#0B0C0F</value>
        </token>
        <token>
          <name>colorTextButtonPrimaryBordered</name>
          <value>#00A58E</value>
        </token>
        <token>
          <name>colorTextButtonPrimaryBorderedHover</name>
          <value>#009580</value>
        </token>
        <token>
          <name>colorTextButtonPrimaryBorderedActive</name>
          <value>#008472</value>
        </token>
        <token>
          <name>colorTextButtonSecondaryBordered</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextButtonSecondaryBorderedHover</name>
          <value>#181B20</value>
        </token>
        <token>
          <name>colorTextButtonSecondaryBorderedActive</name>
          <value>#0B0C0F</value>
        </token>
        <token>
          <name>colorTextButtonInfoBordered</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>colorTextButtonInfoBorderedHover</name>
          <value>#0161AC</value>
        </token>
        <token>
          <name>colorTextButtonInfoBorderedActive</name>
          <value>#01508E</value>
        </token>
        <token>
          <name>colorTextButtonSuccessBordered</name>
          <value>#28A138</value>
        </token>
        <token>
          <name>colorTextButtonSuccessBorderedHover</name>
          <value>#238B31</value>
        </token>
        <token>
          <name>colorTextButtonSuccessBorderedActive</name>
          <value>#1D7228</value>
        </token>
        <token>
          <name>colorTextButtonWarningBordered</name>
          <value>#DF7B00</value>
        </token>
        <token>
          <name>colorTextButtonWarningBorderedHover</name>
          <value>#C96F00</value>
        </token>
        <token>
          <name>colorTextButtonWarningBorderedActive</name>
          <value>#B26200</value>
        </token>
        <token>
          <name>colorTextButtonCriticalBordered</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>colorTextButtonCriticalBorderedHover</name>
          <value>#B91919</value>
        </token>
        <token>
          <name>colorTextButtonCriticalBorderedActive</name>
          <value>#9D1515</value>
        </token>
        <token>
          <name>colorTextButtonFacebookBordered</name>
          <value>#3B5998</value>
        </token>
        <token>
          <name>colorTextButtonFacebookBorderedHover</name>
          <value>#385490</value>
        </token>
        <token>
          <name>colorTextButtonFacebookBorderedActive</name>
          <value>#354F88</value>
        </token>
        <token>
          <name>colorTextButtonGoogleBordered</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextButtonGoogleBorderedHover</name>
          <value>#181B20</value>
        </token>
        <token>
          <name>colorTextButtonGoogleBorderedActive</name>
          <value>#0B0C0F</value>
        </token>
        <token>
          <name>colorTextButtonWhiteBordered</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonWhiteBorderedHover</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonWhiteBorderedActive</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextButtonLinkPrimary</name>
          <value>#00A58E</value>
        </token>
        <token>
          <name>colorTextButtonLinkPrimaryHover</name>
          <value>#007060</value>
        </token>
        <token>
          <name>colorTextButtonLinkPrimaryActive</name>
          <value>#006657</value>
        </token>
        <token>
          <name>colorTextButtonLinkSecondary</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextButtonLinkSecondaryHover</name>
          <value>#181B20</value>
        </token>
        <token>
          <name>colorTextButtonLinkSecondaryActive</name>
          <value>#0B0C0F</value>
        </token>
        <token>
          <name>colorTextButtonLinkSecondaryCompactHover</name>
          <value>#009580</value>
        </token>
        <token>
          <name>colorTextButtonLinkSecondaryCompactActive</name>
          <value>#008472</value>
        </token>
        <token>
          <name>colorTextInput</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextInputPrefix</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>colorTextInputDisabled</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>colorTextBadgeNeutral</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextBadgeInfo</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>colorTextBadgeSuccess</name>
          <value>#28A138</value>
        </token>
        <token>
          <name>colorTextBadgeWarning</name>
          <value>#DF7B00</value>
        </token>
        <token>
          <name>colorTextBadgeCritical</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>colorTextBadgeDark</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>colorTextBadgeWhite</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextLoading</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>colorTextTable</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>colorTextTag</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorTextTagSelected</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>colorIconInput</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>colorPlaceholderInput</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>colorPlaceholderInputError</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>colorPlaceholderInputFile</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>colorPlaceholderInputFileError</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>colorFormLabel</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>colorFormLabelFilled</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>colorInfoCheckBoxRadio</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>colorIconCheckboxRadio</name>
          <value>#00A58E</value>
        </token>
        <token>
          <name>colorIconCheckboxRadioDisabled</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>colorIconRadioButton</name>
          <value>#00A58E</value>
        </token>
        <token>
          <name>colorIconRadioButtonDisabled</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>colorStopoverArrow</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>fontFamily</name>
          <value>&apos;Roboto&apos;, -apple-system, &apos;.SFNSText-Regular&apos;, &apos;San Francisco&apos;, &apos;Segoe UI&apos;, &apos;Helvetica Neue&apos;, &apos;Lucida Grande&apos;, sans-serif</value>
        </token>
        <token>
          <name>backgroundBody</name>
          <value>#F5F7F9</value>
        </token>
        <token>
          <name>backgroundModal</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>backgroundCard</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>backgroundCarrierLogo</name>
          <value>transparent</value>
        </token>
        <token>
          <name>backgroundCountryFlag</name>
          <value>transparent</value>
        </token>
        <token>
          <name>backgroundButtonPrimary</name>
          <value>#00A58E</value>
        </token>
        <token>
          <name>backgroundButtonPrimaryHover</name>
          <value>#009580</value>
        </token>
        <token>
          <name>backgroundButtonPrimaryActive</name>
          <value>#008472</value>
        </token>
        <token>
          <name>backgroundButtonSecondary</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>backgroundButtonSecondaryHover</name>
          <value>#DCE3E9</value>
        </token>
        <token>
          <name>backgroundButtonSecondaryActive</name>
          <value>#CAD4DE</value>
        </token>
        <token>
          <name>backgroundButtonFacebook</name>
          <value>#3B5998</value>
        </token>
        <token>
          <name>backgroundButtonFacebookHover</name>
          <value>#385490</value>
        </token>
        <token>
          <name>backgroundButtonFacebookActive</name>
          <value>#354F88</value>
        </token>
        <token>
          <name>backgroundButtonGoogle</name>
          <value>#F5F7F9</value>
        </token>
        <token>
          <name>backgroundButtonGoogleHover</name>
          <value>#E5EAEF</value>
        </token>
        <token>
          <name>backgroundButtonGoogleActive</name>
          <value>#D6DEE6</value>
        </token>
        <token>
          <name>backgroundButtonInfo</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>backgroundButtonInfoHover</name>
          <value>#0161AC</value>
        </token>
        <token>
          <name>backgroundButtonInfoActive</name>
          <value>#01508E</value>
        </token>
        <token>
          <name>backgroundButtonSuccess</name>
          <value>#28A138</value>
        </token>
        <token>
          <name>backgroundButtonSuccessHover</name>
          <value>#238B31</value>
        </token>
        <token>
          <name>backgroundButtonSuccessActive</name>
          <value>#1D7228</value>
        </token>
        <token>
          <name>backgroundButtonWarning</name>
          <value>#DF7B00</value>
        </token>
        <token>
          <name>backgroundButtonWarningHover</name>
          <value>#C96F00</value>
        </token>
        <token>
          <name>backgroundButtonWarningActive</name>
          <value>#B26200</value>
        </token>
        <token>
          <name>backgroundButtonCritical</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>backgroundButtonCriticalHover</name>
          <value>#B91919</value>
        </token>
        <token>
          <name>backgroundButtonCriticalActive</name>
          <value>#9D1515</value>
        </token>
        <token>
          <name>backgroundButtonWhite</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>backgroundButtonWhiteHover</name>
          <value>#F5F7F9</value>
        </token>
        <token>
          <name>backgroundButtonWhiteActive</name>
          <value>#E5EAEF</value>
        </token>
        <token>
          <name>backgroundButtonBundleBasic</name>
          <value>linear-gradient(to top right, #E13E3B 0%, #E87E09 100%)</value>
        </token>
        <token>
          <name>backgroundButtonBundleBasicHover</name>
          <value>linear-gradient(to top right, #BD2825 0%, #D67000 100%)</value>
        </token>
        <token>
          <name>backgroundButtonBundleBasicActive</name>
          <value>linear-gradient(to top right, #9F1816 0%, #C36802 100%)</value>
        </token>
        <token>
          <name>backgroundButtonBundleMedium</name>
          <value>linear-gradient(to top right, #3719AB 0%, #8539DB 100%)</value>
        </token>
        <token>
          <name>backgroundButtonBundleMediumHover</name>
          <value>linear-gradient(to top right, #2D1393 0%, #7343AA 100%)</value>
        </token>
        <token>
          <name>backgroundButtonBundleMediumActive</name>
          <value>linear-gradient(to top right, #250F79 0%, #5A3485 100%)</value>
        </token>
        <token>
          <name>backgroundButtonBundleTop</name>
          <value>linear-gradient(to top right, #2D2D2E 0%, #696E73 100%)</value>
        </token>
        <token>
          <name>backgroundButtonBundleTopHover</name>
          <value>linear-gradient(to top right, #171718 0%, #51575C 100%)</value>
        </token>
        <token>
          <name>backgroundButtonBundleTopActive</name>
          <value>linear-gradient(to top right, #101011 0%, #51575C)</value>
        </token>
        <token>
          <name>backgroundButtonBordered</name>
          <value>transparent</value>
        </token>
        <token>
          <name>backgroundButtonBorderedHover</name>
          <value>#F5F7F9</value>
        </token>
        <token>
          <name>backgroundButtonBorderedActive</name>
          <value>#F5F7F9</value>
        </token>
        <token>
          <name>backgroundButtonWhiteBordered</name>
          <value>transparent</value>
        </token>
        <token>
          <name>backgroundButtonWhiteBorderedHover</name>
          <value>rgba(255, 255, 255, 0.2)</value>
        </token>
        <token>
          <name>backgroundButtonWhiteBorderedActive</name>
          <value>rgba(255, 255, 255, 0.2)</value>
        </token>
        <token>
          <name>backgroundButtonLinkPrimary</name>
          <value>transparent</value>
        </token>
        <token>
          <name>backgroundButtonLinkPrimaryHover</name>
          <value>#E5EAEF</value>
        </token>
        <token>
          <name>backgroundButtonLinkPrimaryActive</name>
          <value>#D6DEE6</value>
        </token>
        <token>
          <name>backgroundButtonLinkSecondary</name>
          <value>transparent</value>
        </token>
        <token>
          <name>backgroundButtonLinkSecondaryHover</name>
          <value>#E5EAEF</value>
        </token>
        <token>
          <name>backgroundButtonLinkSecondaryActive</name>
          <value>#D6DEE6</value>
        </token>
        <token>
          <name>backgroundInput</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>backgroundInputDisabled</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>backgroundAlertSuccess</name>
          <value>#F2F8F2</value>
        </token>
        <token>
          <name>backgroundAlertInfo</name>
          <value>#F1F8FE</value>
        </token>
        <token>
          <name>backgroundAlertWarning</name>
          <value>#FEF7F1</value>
        </token>
        <token>
          <name>backgroundAlertCritical</name>
          <value>#FCF3F3</value>
        </token>
        <token>
          <name>backgroundBadgeNeutral</name>
          <value>#F5F7F9</value>
        </token>
        <token>
          <name>backgroundBadgeInfo</name>
          <value>#F1F8FE</value>
        </token>
        <token>
          <name>backgroundBadgeSuccess</name>
          <value>#F2F8F2</value>
        </token>
        <token>
          <name>backgroundBadgeWarning</name>
          <value>#FEF7F1</value>
        </token>
        <token>
          <name>backgroundBadgeCritical</name>
          <value>#FCF3F3</value>
        </token>
        <token>
          <name>backgroundBadgeDark</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>backgroundBadgeWhite</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>backgroundBadgeBundleBasic</name>
          <value>linear-gradient(to top right, #E13E3B 0%, #E87E09 100%)</value>
        </token>
        <token>
          <name>backgroundBadgeBundleMedium</name>
          <value>linear-gradient(to top right, #3719AB 0%, #8539DB 100%)</value>
        </token>
        <token>
          <name>backgroundBadgeBundleTop</name>
          <value>linear-gradient(to top right, #2D2D2E 0%, #696E73 100%)</value>
        </token>
        <token>
          <name>backgroundServiceLogo</name>
          <value>transparent</value>
        </token>
        <token>
          <name>backgroundIllustration</name>
          <value>transparent</value>
        </token>
        <token>
          <name>backgroundSeparator</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>backgroundTableShadowLeft</name>
          <value>linear-gradient(to left, transparent, rgba(232, 237, 241, 0.23))</value>
        </token>
        <token>
          <name>backgroundTableShadowRight</name>
          <value>linear-gradient(to right, transparent, rgba(232, 237, 241, 0.23))</value>
        </token>
        <token>
          <name>backgroundTable</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>backgroundTableEven</name>
          <value>#F5F7F9</value>
        </token>
        <token>
          <name>backgroundTableHover</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>backgroundTag</name>
          <value>#F5F7F9</value>
        </token>
        <token>
          <name>backgroundTagSelected</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>backgroundTagHover</name>
          <value>#E5EAEF</value>
        </token>
        <token>
          <name>backgroundTagSelectedHover</name>
          <value>#181B20</value>
        </token>
        <token>
          <name>backgroundTagActive</name>
          <value>#D6DEE6</value>
        </token>
        <token>
          <name>backgroundTagSelectedActive</name>
          <value>#0B0C0F</value>
        </token>
        <token>
          <name>backgroundTooltip</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>backgroundTooltipLargeMobile</name>
          <value>#005AA3</value>
        </token>
        <token>
          <name>fontSizeHeadingDisplay</name>
          <value>40px</value>
        </token>
        <token>
          <name>fontSizeHeadingDisplaySubtitle</name>
          <value>22px</value>
        </token>
        <token>
          <name>fontSizeHeadingTitle1</name>
          <value>28px</value>
        </token>
        <token>
          <name>fontSizeHeadingTitle2</name>
          <value>22px</value>
        </token>
        <token>
          <name>fontSizeHeadingTitle3</name>
          <value>16px</value>
        </token>
        <token>
          <name>fontSizeHeadingTitle4</name>
          <value>14px</value>
        </token>
        <token>
          <name>fontSizeHeadingTitle5</name>
          <value>12px</value>
        </token>
        <token>
          <name>fontSizeTextNormal</name>
          <value>14px</value>
        </token>
        <token>
          <name>fontSizeTextLarge</name>
          <value>16px</value>
        </token>
        <token>
          <name>fontSizeTextSmall</name>
          <value>12px</value>
        </token>
        <token>
          <name>fontSizeMessage</name>
          <value>14px</value>
        </token>
        <token>
          <name>fontSizeButtonLarge</name>
          <value>16px</value>
        </token>
        <token>
          <name>fontSizeButtonNormal</name>
          <value>14px</value>
        </token>
        <token>
          <name>fontSizeButtonSmall</name>
          <value>12px</value>
        </token>
        <token>
          <name>fontSizeInputNormal</name>
          <value>14px</value>
        </token>
        <token>
          <name>fontSizeInputSmall</name>
          <value>14px</value>
        </token>
        <token>
          <name>fontSizeFormLabel</name>
          <value>14px</value>
        </token>
        <token>
          <name>fontSizeFormFeedback</name>
          <value>12px</value>
        </token>
        <token>
          <name>borderRadiusCircle</name>
          <value>50%</value>
        </token>
        <token>
          <name>borderRadiusNormal</name>
          <value>3px</value>
        </token>
        <token>
          <name>borderRadiusLarge</name>
          <value>6px</value>
        </token>
        <token>
          <name>borderRadiusSmall</name>
          <value>2px</value>
        </token>
        <token>
          <name>borderRadiusBadge</name>
          <value>12px</value>
        </token>
        <token>
          <name>zIndexDefault</name>
          <value>1</value>
        </token>
        <token>
          <name>zIndexSticky</name>
          <value>100</value>
        </token>
        <token>
          <name>zIndexDrawer</name>
          <value>815</value>
        </token>
        <token>
          <name>zIndexModalOverlay</name>
          <value>800</value>
        </token>
        <token>
          <name>zIndexModal</name>
          <value>825</value>
        </token>
        <token>
          <name>zIndexOnTheTop</name>
          <value>900</value>
        </token>
        <token>
          <name>widthIconSmall</name>
          <value>16px</value>
        </token>
        <token>
          <name>heightIconSmall</name>
          <value>16px</value>
        </token>
        <token>
          <name>widthIconMedium</name>
          <value>24px</value>
        </token>
        <token>
          <name>heightIconMedium</name>
          <value>24px</value>
        </token>
        <token>
          <name>widthIconLarge</name>
          <value>32px</value>
        </token>
        <token>
          <name>heightIconLarge</name>
          <value>32px</value>
        </token>
        <token>
          <name>heightInputNormal</name>
          <value>44px</value>
        </token>
        <token>
          <name>heightInputLarge</name>
          <value>52px</value>
        </token>
        <token>
          <name>heightInputSmall</name>
          <value>32px</value>
        </token>
        <token>
          <name>heightButtonNormal</name>
          <value>44px</value>
        </token>
        <token>
          <name>heightButtonLarge</name>
          <value>52px</value>
        </token>
        <token>
          <name>heightButtonSmall</name>
          <value>32px</value>
        </token>
        <token>
          <name>heightRadioButton</name>
          <value>20px</value>
        </token>
        <token>
          <name>widthRadioButton</name>
          <value>20px</value>
        </token>
        <token>
          <name>heightCheckbox</name>
          <value>20px</value>
        </token>
        <token>
          <name>widthCheckbox</name>
          <value>20px</value>
        </token>
        <token>
          <name>heightCountryFlag</name>
          <value>auto</value>
        </token>
        <token>
          <name>widthCountryFlag</name>
          <value>24px</value>
        </token>
        <token>
          <name>heightBadge</name>
          <value>24px</value>
        </token>
        <token>
          <name>widthBadgeCircled</name>
          <value>24px</value>
        </token>
        <token>
          <name>heightIllustrationSmall</name>
          <value>90px</value>
        </token>
        <token>
          <name>heightIllustrationMedium</name>
          <value>200px</value>
        </token>
        <token>
          <name>heightServiceLogoSmall</name>
          <value>12px</value>
        </token>
        <token>
          <name>heightServiceLogoMedium</name>
          <value>24px</value>
        </token>
        <token>
          <name>heightServiceLogoLarge</name>
          <value>48px</value>
        </token>
        <token>
          <name>heightSeparator</name>
          <value>1px</value>
        </token>
        <token>
          <name>heightInputGroupSeparatorSmall</name>
          <value>16px</value>
        </token>
        <token>
          <name>heightInputGroupSeparatorNormal</name>
          <value>24px</value>
        </token>
        <token>
          <name>widthModalSmall</name>
          <value>540px</value>
        </token>
        <token>
          <name>widthModalNormal</name>
          <value>740px</value>
        </token>
        <token>
          <name>widthModalLarge</name>
          <value>900px</value>
        </token>
        <token>
          <name>widthModalExtraLarge</name>
          <value>1280px</value>
        </token>
        <token>
          <name>widthStopoverArrow</name>
          <value>36px</value>
        </token>
        <token>
          <name>heightStopoverArrow</name>
          <value>7px</value>
        </token>
        <token>
          <name>widthBreakpointMediumMobile</name>
          <value>414</value>
        </token>
        <token>
          <name>widthBreakpointLargeMobile</name>
          <value>576</value>
        </token>
        <token>
          <name>widthBreakpointTablet</name>
          <value>768</value>
        </token>
        <token>
          <name>widthBreakpointDesktop</name>
          <value>992</value>
        </token>
        <token>
          <name>widthBreakpointLargeDesktop</name>
          <value>1200</value>
        </token>
        <token>
          <name>borderColorInput</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>borderColorInputHover</name>
          <value>#3E4E63</value>
        </token>
        <token>
          <name>borderColorInputActive</name>
          <value>#324256</value>
        </token>
        <token>
          <name>borderColorInputFocus</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>borderColorInputError</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>borderColorInputErrorHover</name>
          <value>#B91919</value>
        </token>
        <token>
          <name>borderColorInputErrorFocus</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>borderColorTableCell</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>borderColorCard</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>borderColorModal</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>borderColorButtonPrimaryBordered</name>
          <value>#00A58E</value>
        </token>
        <token>
          <name>borderColorButtonPrimaryBorderedHover</name>
          <value>#009580</value>
        </token>
        <token>
          <name>borderColorButtonPrimaryBorderedActive</name>
          <value>#008472</value>
        </token>
        <token>
          <name>borderColorButtonSecondaryBordered</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>borderColorButtonSecondaryBorderedHover</name>
          <value>#181B20</value>
        </token>
        <token>
          <name>borderColorButtonSecondaryBorderedActive</name>
          <value>#0B0C0F</value>
        </token>
        <token>
          <name>borderColorButtonFacebookBordered</name>
          <value>#3B5998</value>
        </token>
        <token>
          <name>borderColorButtonFacebookBorderedHover</name>
          <value>#385490</value>
        </token>
        <token>
          <name>borderColorButtonFacebookBorderedActive</name>
          <value>#354F88</value>
        </token>
        <token>
          <name>borderColorButtonGoogleBordered</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>borderColorButtonGoogleBorderedHover</name>
          <value>#181B20</value>
        </token>
        <token>
          <name>borderColorButtonGoogleBorderedActive</name>
          <value>#0B0C0F</value>
        </token>
        <token>
          <name>borderColorButtonInfoBordered</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>borderColorButtonInfoBorderedHover</name>
          <value>#0161AC</value>
        </token>
        <token>
          <name>borderColorButtonInfoBorderedActive</name>
          <value>#01508E</value>
        </token>
        <token>
          <name>borderColorButtonSuccessBordered</name>
          <value>#28A138</value>
        </token>
        <token>
          <name>borderColorButtonSuccessBorderedHover</name>
          <value>#238B31</value>
        </token>
        <token>
          <name>borderColorButtonSuccessBorderedActive</name>
          <value>#1D7228</value>
        </token>
        <token>
          <name>borderColorButtonWarningBordered</name>
          <value>#DF7B00</value>
        </token>
        <token>
          <name>borderColorButtonWarningBorderedHover</name>
          <value>#C96F00</value>
        </token>
        <token>
          <name>borderColorButtonWarningBorderedActive</name>
          <value>#B26200</value>
        </token>
        <token>
          <name>borderColorButtonCriticalBordered</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>borderColorButtonCriticalBorderedHover</name>
          <value>#B91919</value>
        </token>
        <token>
          <name>borderColorButtonCriticalBorderedActive</name>
          <value>#9D1515</value>
        </token>
        <token>
          <name>borderColorButtonWhiteBordered</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>borderColorButtonWhiteBorderedHover</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>borderColorButtonWhiteBorderedActive</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>borderColorCheckboxRadio</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>borderColorCheckboxRadioError</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>borderColorCheckboxRadioHover</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>borderColorCheckboxRadioActive</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>borderColorCheckboxRadioFocus</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>borderColorTable</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>borderColorTableHead</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>borderColorTag</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>borderColorTagFocus</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>borderStyleCard</name>
          <value>solid</value>
        </token>
        <token>
          <name>borderWidthCard</name>
          <value>1px</value>
        </token>
        <token>
          <name>borderStyleInput</name>
          <value>solid</value>
        </token>
        <token>
          <name>borderWidthInput</name>
          <value>1px</value>
        </token>
        <token>
          <name>borderWidthInputFocus</name>
          <value>2px</value>
        </token>
        <token>
          <name>opacityOverlay</name>
          <value>0.8</value>
        </token>
        <token>
          <name>opacityButtonDisabled</name>
          <value>0.3</value>
        </token>
        <token>
          <name>opacityRadioButtonDisabled</name>
          <value>0.5</value>
        </token>
        <token>
          <name>opacityCheckboxDisabled</name>
          <value>0.5</value>
        </token>
        <token>
          <name>fontWeightNormal</name>
          <value>400</value>
        </token>
        <token>
          <name>fontWeightMedium</name>
          <value>500</value>
        </token>
        <token>
          <name>fontWeightBold</name>
          <value>700</value>
        </token>
        <token>
          <name>fontWeightLinks</name>
          <value>500</value>
        </token>
        <token>
          <name>fontWeightHeadingDisplay</name>
          <value>700</value>
        </token>
        <token>
          <name>fontWeightHeadingDisplaySubtitle</name>
          <value>400</value>
        </token>
        <token>
          <name>fontWeightHeadingTitle1</name>
          <value>700</value>
        </token>
        <token>
          <name>fontWeightHeadingTitle2</name>
          <value>500</value>
        </token>
        <token>
          <name>fontWeightHeadingTitle3</name>
          <value>500</value>
        </token>
        <token>
          <name>fontWeightHeadingTitle4</name>
          <value>500</value>
        </token>
        <token>
          <name>fontWeightHeadingTitle5</name>
          <value>700</value>
        </token>
        <token>
          <name>fontWeightTableHead</name>
          <value>700</value>
        </token>
        <token>
          <name>paddingAlert</name>
          <value>16px</value>
        </token>
        <token>
          <name>paddingAlertWithIcon</name>
          <value>12px</value>
        </token>
        <token>
          <name>paddingBadge</name>
          <value>0 8px</value>
        </token>
        <token>
          <name>paddingButtonWithoutText</name>
          <value>0</value>
        </token>
        <token>
          <name>paddingButtonSmall</name>
          <value>0 12px</value>
        </token>
        <token>
          <name>paddingButtonNormal</name>
          <value>0 16px</value>
        </token>
        <token>
          <name>paddingButtonLarge</name>
          <value>0 28px</value>
        </token>
        <token>
          <name>paddingButtonSmallWithIcons</name>
          <value>0 8px</value>
        </token>
        <token>
          <name>paddingButtonNormalWithIcons</name>
          <value>0 12px</value>
        </token>
        <token>
          <name>paddingButtonLargeWithIcons</name>
          <value>0 16px</value>
        </token>
        <token>
          <name>paddingButtonSmallWithLeftIcon</name>
          <value>0 12px 0 8px</value>
        </token>
        <token>
          <name>paddingButtonNormalWithLeftIcon</name>
          <value>0 16px 0 12px</value>
        </token>
        <token>
          <name>paddingButtonLargeWithLeftIcon</name>
          <value>0 28px 0 16px</value>
        </token>
        <token>
          <name>paddingButtonSmallWithRightIcon</name>
          <value>0 8px 0 12px</value>
        </token>
        <token>
          <name>paddingButtonNormalWithRightIcon</name>
          <value>0 12px 0 16px</value>
        </token>
        <token>
          <name>paddingButtonLargeWithRightIcon</name>
          <value>0 16px 0 28px</value>
        </token>
        <token>
          <name>paddingTextareaSmall</name>
          <value>8px 12px</value>
        </token>
        <token>
          <name>paddingTextareaNormal</name>
          <value>12px</value>
        </token>
        <token>
          <name>paddingInputSmall</name>
          <value>0 12px</value>
        </token>
        <token>
          <name>paddingInputNormal</name>
          <value>0 12px</value>
        </token>
        <token>
          <name>marginButtonIconSmall</name>
          <value>8px</value>
        </token>
        <token>
          <name>marginButtonIconNormal</name>
          <value>8px</value>
        </token>
        <token>
          <name>marginButtonIconLarge</name>
          <value>12px</value>
        </token>
        <token>
          <name>marginButtonGroup</name>
          <value>0 1px 0 0</value>
        </token>
        <token>
          <name>marginTopFormFeedback</name>
          <value>2px</value>
        </token>
        <token>
          <name>marginBottomSelectSuffix</name>
          <value>2px</value>
        </token>
        <token>
          <name>paddingInputFile</name>
          <value>0 0 0 6px</value>
        </token>
        <token>
          <name>paddingLeftSelectPrefix</name>
          <value>48px</value>
        </token>
        <token>
          <name>paddingLoading</name>
          <value>12px</value>
        </token>
        <token>
          <name>paddingTable</name>
          <value>12px 16px</value>
        </token>
        <token>
          <name>paddingTableCompact</name>
          <value>8px 12px</value>
        </token>
        <token>
          <name>paddingTag</name>
          <value>8px</value>
        </token>
        <token>
          <name>paddingTagWithIcon</name>
          <value>6px 8px 6px 6px</value>
        </token>
        <token>
          <name>paddingTagRemovable</name>
          <value>6px 6px 6px 8px</value>
        </token>
        <token>
          <name>paddingTagRemovableWithIcon</name>
          <value>6px</value>
        </token>
        <token>
          <name>marginBadgeIcon</name>
          <value>0 4px 0 0</value>
        </token>
        <token>
          <name>spaceXXXSmall</name>
          <value>2px</value>
        </token>
        <token>
          <name>spaceXXSmall</name>
          <value>4px</value>
        </token>
        <token>
          <name>spaceXSmall</name>
          <value>8px</value>
        </token>
        <token>
          <name>spaceSmall</name>
          <value>12px</value>
        </token>
        <token>
          <name>spaceMedium</name>
          <value>16px</value>
        </token>
        <token>
          <name>spaceLarge</name>
          <value>24px</value>
        </token>
        <token>
          <name>spaceXLarge</name>
          <value>32px</value>
        </token>
        <token>
          <name>spaceXXLarge</name>
          <value>40px</value>
        </token>
        <token>
          <name>spaceXXXLarge</name>
          <value>52px</value>
        </token>
        <token>
          <name>durationFast</name>
          <value>0.15s</value>
        </token>
        <token>
          <name>durationNormal</name>
          <value>0.3s</value>
        </token>
        <token>
          <name>durationSlow</name>
          <value>0.4s</value>
        </token>
        <token>
          <name>modifierScaleButtonActive</name>
          <value>0.95</value>
        </token>
        <token>
          <name>modifierScaleCheckboxRadioActive</name>
          <value>0.95</value>
        </token>
        <token>
          <name>lineHeightText</name>
          <value>1.4</value>
        </token>
        <token>
          <name>lineHeightTextSmall</name>
          <value>16px</value>
        </token>
        <token>
          <name>lineHeightTextNormal</name>
          <value>20px</value>
        </token>
        <token>
          <name>lineHeightTextLarge</name>
          <value>24px</value>
        </token>
        <token>
          <name>lineHeightHeading</name>
          <value>1.2</value>
        </token>
        <token>
          <name>lineHeightHeadingDisplay</name>
          <value>44px</value>
        </token>
        <token>
          <name>lineHeightHeadingDisplaySubtitle</name>
          <value>28px</value>
        </token>
        <token>
          <name>lineHeightHeadingTitle1</name>
          <value>36px</value>
        </token>
        <token>
          <name>lineHeightHeadingTitle2</name>
          <value>28px</value>
        </token>
        <token>
          <name>lineHeightHeadingTitle3</name>
          <value>24px</value>
        </token>
        <token>
          <name>lineHeightHeadingTitle4</name>
          <value>20px</value>
        </token>
        <token>
          <name>lineHeightHeadingTitle5</name>
          <value>20px</value>
        </token>
        <token>
          <name>textDecorationTextLinkPrimary</name>
          <value>underline</value>
        </token>
        <token>
          <name>textDecorationTextLinkPrimaryHover</name>
          <value>none</value>
        </token>
        <token>
          <name>textDecorationTextLinkSecondary</name>
          <value>underline</value>
        </token>
        <token>
          <name>textDecorationTextLinkSecondaryHover</name>
          <value>none</value>
        </token>
        <token>
          <name>boxShadowButtonFocus</name>
          <value>0 0 4px 1px rgba(1, 114, 203, 0.3)</value>
        </token>
        <token>
          <name>boxShadowAction</name>
          <value>0px 0px 2px 0px rgba(37, 42, 49, 0.16), 0px 1px 4px 0px rgba(37, 42, 49, 0.12)</value>
        </token>
        <token>
          <name>boxShadowActionActive</name>
          <value>0px 1px 4px 0px rgba(37, 42, 49, 0.16), 0px 4px 8px 0px rgba(37, 42, 49, 0.12)</value>
        </token>
        <token>
          <name>boxShadowFixed</name>
          <value>0px 0px 2px 0px rgba(37, 42, 49, 0.16), 0px 2px 4px 0px rgba(37, 42, 49, 0.12)</value>
        </token>
        <token>
          <name>boxShadowFixedReverse</name>
          <value>0px 0px 2px 0px rgba(37, 42, 49, 0.16), 0px -2px 4px 0px rgba(37, 42, 49, 0.12)</value>
        </token>
        <token>
          <name>boxShadowRaised</name>
          <value>0px 4px 8px 0px rgba(37, 42, 49, 0.16), 0px 8px 24px 0px rgba(37, 42, 49, 0.24)</value>
        </token>
        <token>
          <name>boxShadowRaisedReverse</name>
          <value>0px -4px 8px 0px rgba(37, 42, 49, 0.16), 0px -8px 24px 0px rgba(37, 42, 49, 0.24)</value>
        </token>
        <token>
          <name>boxShadowOverlay</name>
          <value>0px 12px 24px -4px rgba(37, 42, 49, 0.24), 0px 8px 60px 0px rgba(37, 42, 49, 0.32)</value>
        </token>
        <token>
          <name>paletteProductLight</name>
          <value>#ECF8F7</value>
        </token>
        <token>
          <name>paletteProductLightHover</name>
          <value>#D6F0EC</value>
        </token>
        <token>
          <name>paletteProductLightActive</name>
          <value>#BFE8E2</value>
        </token>
        <token>
          <name>paletteProductNormal</name>
          <value>#00A58E</value>
        </token>
        <token>
          <name>paletteProductNormalHover</name>
          <value>#009580</value>
        </token>
        <token>
          <name>paletteProductNormalActive</name>
          <value>#008472</value>
        </token>
        <token>
          <name>paletteProductDark</name>
          <value>#007F6D</value>
        </token>
        <token>
          <name>paletteProductDarkHover</name>
          <value>#007060</value>
        </token>
        <token>
          <name>paletteProductDarkActive</name>
          <value>#006657</value>
        </token>
        <token>
          <name>paletteProductDarker</name>
          <value>#005C4E</value>
        </token>
        <token>
          <name>paletteWhite</name>
          <value>#FFFFFF</value>
        </token>
        <token>
          <name>paletteWhiteHover</name>
          <value>#F5F7F9</value>
        </token>
        <token>
          <name>paletteWhiteActive</name>
          <value>#E5EAEF</value>
        </token>
        <token>
          <name>paletteCloudLight</name>
          <value>#F5F7F9</value>
        </token>
        <token>
          <name>paletteCloudLightHover</name>
          <value>#E5EAEF</value>
        </token>
        <token>
          <name>paletteCloudLightActive</name>
          <value>#D6DEE6</value>
        </token>
        <token>
          <name>paletteCloudNormal</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>paletteCloudNormalHover</name>
          <value>#DCE3E9</value>
        </token>
        <token>
          <name>paletteCloudNormalActive</name>
          <value>#CAD4DE</value>
        </token>
        <token>
          <name>paletteCloudDark</name>
          <value>#E8EDF1</value>
        </token>
        <token>
          <name>paletteCloudDarkHover</name>
          <value>#DCE3E9</value>
        </token>
        <token>
          <name>paletteCloudDarkActive</name>
          <value>#CAD4DE</value>
        </token>
        <token>
          <name>paletteInkLight</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>paletteInkLightHover</name>
          <value>#3E4E63</value>
        </token>
        <token>
          <name>paletteInkLightActive</name>
          <value>#324256</value>
        </token>
        <token>
          <name>paletteInkDark</name>
          <value>#252A31</value>
        </token>
        <token>
          <name>paletteInkDarkHover</name>
          <value>#181B20</value>
        </token>
        <token>
          <name>paletteInkDarkActive</name>
          <value>#0B0C0F</value>
        </token>
        <token>
          <name>paletteInkNormal</name>
          <value>#4F5E71</value>
        </token>
        <token>
          <name>paletteInkNormalHover</name>
          <value>#3E4E63</value>
        </token>
        <token>
          <name>paletteInkNormalActive</name>
          <value>#324256</value>
        </token>
        <token>
          <name>paletteOrangeLight</name>
          <value>#FEF7F1</value>
        </token>
        <token>
          <name>paletteOrangeLightHover</name>
          <value>#FCECDA</value>
        </token>
        <token>
          <name>paletteOrangeLightActive</name>
          <value>#FAE2C6</value>
        </token>
        <token>
          <name>paletteOrangeNormal</name>
          <value>#DF7B00</value>
        </token>
        <token>
          <name>paletteOrangeNormalHover</name>
          <value>#C96F00</value>
        </token>
        <token>
          <name>paletteOrangeNormalActive</name>
          <value>#B26200</value>
        </token>
        <token>
          <name>paletteOrangeDark</name>
          <value>#BA5D00</value>
        </token>
        <token>
          <name>paletteOrangeDarkHover</name>
          <value>#A75400</value>
        </token>
        <token>
          <name>paletteOrangeDarkActive</name>
          <value>#954A00</value>
        </token>
        <token>
          <name>paletteOrangeDarker</name>
          <value>#803F00</value>
        </token>
        <token>
          <name>paletteRedLight</name>
          <value>#FCF3F3</value>
        </token>
        <token>
          <name>paletteRedLightHover</name>
          <value>#F8E2E2</value>
        </token>
        <token>
          <name>paletteRedLightActive</name>
          <value>#F3CECE</value>
        </token>
        <token>
          <name>paletteRedNormal</name>
          <value>#D21C1C</value>
        </token>
        <token>
          <name>paletteRedNormalHover</name>
          <value>#B91919</value>
        </token>
        <token>
          <name>paletteRedNormalActive</name>
          <value>#9D1515</value>
        </token>
        <token>
          <name>paletteRedDark</name>
          <value>#970C0C</value>
        </token>
        <token>
          <name>paletteRedDarkHover</name>
          <value>#890B0B</value>
        </token>
        <token>
          <name>paletteRedDarkActive</name>
          <value>#6D0909</value>
        </token>
        <token>
          <name>paletteRedDarker</name>
          <value>#760909</value>
        </token>
        <token>
          <name>paletteGreenLight</name>
          <value>#F2F8F2</value>
        </token>
        <token>
          <name>paletteGreenLightHover</name>
          <value>#E1EFE2</value>
        </token>
        <token>
          <name>paletteGreenLightActive</name>
          <value>#CDE4CF</value>
        </token>
        <token>
          <name>paletteGreenNormal</name>
          <value>#28A138</value>
        </token>
        <token>
          <name>paletteGreenNormalHover</name>
          <value>#238B31</value>
        </token>
        <token>
          <name>paletteGreenNormalActive</name>
          <value>#1D7228</value>
        </token>
        <token>
          <name>paletteGreenDark</name>
          <value>#2D7738</value>
        </token>
        <token>
          <name>paletteGreenDarkHover</name>
          <value>#276831</value>
        </token>
        <token>
          <name>paletteGreenDarkActive</name>
          <value>#1F5126</value>
        </token>
        <token>
          <name>paletteGreenDarker</name>
          <value>#235C2B</value>
        </token>
        <token>
          <name>paletteBlueLight</name>
          <value>#F1F8FE</value>
        </token>
        <token>
          <name>paletteBlueLightHover</name>
          <value>#DEF0FC</value>
        </token>
        <token>
          <name>paletteBundleBasic</name>
          <value>#D7331C</value>
        </token>
        <token>
          <name>paletteBundleMedium</name>
          <value>#3B1EB0</value>
        </token>
        <token>
          <name>paletteBlueLightActive</name>
          <value>#C7E4FA</value>
        </token>
        <token>
          <name>paletteBlueNormal</name>
          <value>#0172CB</value>
        </token>
        <token>
          <name>paletteBlueNormalHover</name>
          <value>#0161AC</value>
        </token>
        <token>
          <name>paletteBlueNormalActive</name>
          <value>#01508E</value>
        </token>
        <token>
          <name>paletteBlueDark</name>
          <value>#005AA3</value>
        </token>
        <token>
          <name>paletteBlueDarkHover</name>
          <value>#004F8F</value>
        </token>
        <token>
          <name>paletteBlueDarkActive</name>
          <value>#003E70</value>
        </token>
        <token>
          <name>paletteBlueDarker</name>
          <value>#004680</value>
        </token>
        <token>
          <name>paletteSocialFacebook</name>
          <value>#3B5998</value>
        </token>
        <token>
          <name>paletteSocialFacebookHover</name>
          <value>#385490</value>
        </token>
        <token>
          <name>paletteSocialFacebookActive</name>
          <value>#354F88</value>
        </token>
      </designTokens>"
    `);
  });
});
