// flow-typed signature: 53b0214b3c08e4e5d4644836aba940cd
// flow-typed version: <<STUB>>/@lerna/project_v^3.21.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@lerna/project'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@lerna/project' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@lerna/project/lib/apply-extends' {
  declare module.exports: any;
}

declare module '@lerna/project/lib/deprecate-config' {
  declare module.exports: any;
}

declare module '@lerna/project/lib/make-file-finder' {
  declare module.exports: any;
}

declare module '@lerna/project/lib/shallow-extend' {
  declare module.exports: any;
}

// Filename aliases
declare module '@lerna/project/index' {
  declare module.exports: $Exports<'@lerna/project'>;
}
declare module '@lerna/project/index.js' {
  declare module.exports: $Exports<'@lerna/project'>;
}
declare module '@lerna/project/lib/apply-extends.js' {
  declare module.exports: $Exports<'@lerna/project/lib/apply-extends'>;
}
declare module '@lerna/project/lib/deprecate-config.js' {
  declare module.exports: $Exports<'@lerna/project/lib/deprecate-config'>;
}
declare module '@lerna/project/lib/make-file-finder.js' {
  declare module.exports: $Exports<'@lerna/project/lib/make-file-finder'>;
}
declare module '@lerna/project/lib/shallow-extend.js' {
  declare module.exports: $Exports<'@lerna/project/lib/shallow-extend'>;
}
