// flow-typed signature: 88a5ac8fa6857df4d7df4877764fd20b
// flow-typed version: <<STUB>>/@testing-library/react-hooks_v^5.0.3/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/react-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/react-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/react-hooks/disable-error-filtering' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/dom' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/dom/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/dont-cleanup-after-each' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/core/asyncUtils' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/core/cleanup' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/core/console' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/core' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/dom' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/dom/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/helpers/createTestHarness' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/helpers/error' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/helpers/promises' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/native' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/native/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/server' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/server/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/types' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/types/react' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/native' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/native/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/server' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/server/pure' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/react-hooks/disable-error-filtering.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/disable-error-filtering'>;
}
declare module '@testing-library/react-hooks/dom/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/dom'>;
}
declare module '@testing-library/react-hooks/dom/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/dom'>;
}
declare module '@testing-library/react-hooks/dom/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/dom/pure'>;
}
declare module '@testing-library/react-hooks/dont-cleanup-after-each.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/dont-cleanup-after-each'>;
}
declare module '@testing-library/react-hooks/lib/core/asyncUtils.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/core/asyncUtils'>;
}
declare module '@testing-library/react-hooks/lib/core/cleanup.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/core/cleanup'>;
}
declare module '@testing-library/react-hooks/lib/core/console.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/core/console'>;
}
declare module '@testing-library/react-hooks/lib/core/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/core'>;
}
declare module '@testing-library/react-hooks/lib/core/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/core'>;
}
declare module '@testing-library/react-hooks/lib/dom/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/dom'>;
}
declare module '@testing-library/react-hooks/lib/dom/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/dom'>;
}
declare module '@testing-library/react-hooks/lib/dom/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/dom/pure'>;
}
declare module '@testing-library/react-hooks/lib/helpers/createTestHarness.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/helpers/createTestHarness'>;
}
declare module '@testing-library/react-hooks/lib/helpers/error.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/helpers/error'>;
}
declare module '@testing-library/react-hooks/lib/helpers/promises.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/helpers/promises'>;
}
declare module '@testing-library/react-hooks/lib/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib'>;
}
declare module '@testing-library/react-hooks/lib/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib'>;
}
declare module '@testing-library/react-hooks/lib/native/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/native'>;
}
declare module '@testing-library/react-hooks/lib/native/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/native'>;
}
declare module '@testing-library/react-hooks/lib/native/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/native/pure'>;
}
declare module '@testing-library/react-hooks/lib/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/pure'>;
}
declare module '@testing-library/react-hooks/lib/server/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/server'>;
}
declare module '@testing-library/react-hooks/lib/server/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/server'>;
}
declare module '@testing-library/react-hooks/lib/server/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/server/pure'>;
}
declare module '@testing-library/react-hooks/lib/types/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/types'>;
}
declare module '@testing-library/react-hooks/lib/types/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/types'>;
}
declare module '@testing-library/react-hooks/lib/types/react.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/types/react'>;
}
declare module '@testing-library/react-hooks/native/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/native'>;
}
declare module '@testing-library/react-hooks/native/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/native'>;
}
declare module '@testing-library/react-hooks/native/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/native/pure'>;
}
declare module '@testing-library/react-hooks/pure/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/pure'>;
}
declare module '@testing-library/react-hooks/pure/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/pure'>;
}
declare module '@testing-library/react-hooks/server/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/server'>;
}
declare module '@testing-library/react-hooks/server/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/server'>;
}
declare module '@testing-library/react-hooks/server/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/server/pure'>;
}
