// flow-typed signature: c8f31e3f55d89eb5609ef157773f92b8
// flow-typed version: <<STUB>>/@svgr/core_v^5.5.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/core/lib/config' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/convert' {
  declare module.exports: any;
}

declare module '@svgr/core/lib' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/plugins' {
  declare module.exports: any;
}

declare module '@svgr/core/lib/state' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/core/lib/config.js' {
  declare module.exports: $Exports<'@svgr/core/lib/config'>;
}
declare module '@svgr/core/lib/convert.js' {
  declare module.exports: $Exports<'@svgr/core/lib/convert'>;
}
declare module '@svgr/core/lib/index' {
  declare module.exports: $Exports<'@svgr/core/lib'>;
}
declare module '@svgr/core/lib/index.js' {
  declare module.exports: $Exports<'@svgr/core/lib'>;
}
declare module '@svgr/core/lib/plugins.js' {
  declare module.exports: $Exports<'@svgr/core/lib/plugins'>;
}
declare module '@svgr/core/lib/state.js' {
  declare module.exports: $Exports<'@svgr/core/lib/state'>;
}
