// flow-typed signature: d612ed3f2d40c7358ccb073335ec32fc
// flow-typed version: <<STUB>>/@svgr/plugin-svgo_v^5.5.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/plugin-svgo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/plugin-svgo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/plugin-svgo/lib/config' {
  declare module.exports: any;
}

declare module '@svgr/plugin-svgo/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/plugin-svgo/lib/config.js' {
  declare module.exports: $Exports<'@svgr/plugin-svgo/lib/config'>;
}
declare module '@svgr/plugin-svgo/lib/index' {
  declare module.exports: $Exports<'@svgr/plugin-svgo/lib'>;
}
declare module '@svgr/plugin-svgo/lib/index.js' {
  declare module.exports: $Exports<'@svgr/plugin-svgo/lib'>;
}
