// flow-typed signature: fc04c19a33a2d56bb5de67e2faf39daa
// flow-typed version: <<STUB>>/@svgr/plugin-prettier_v^5.5.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/plugin-prettier'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/plugin-prettier' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/plugin-prettier/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/plugin-prettier/lib/index' {
  declare module.exports: $Exports<'@svgr/plugin-prettier/lib'>;
}
declare module '@svgr/plugin-prettier/lib/index.js' {
  declare module.exports: $Exports<'@svgr/plugin-prettier/lib'>;
}
