// flow-typed signature: f5290d703aa1136b531f0ec1b3f81f06
// flow-typed version: <<STUB>>/@svgr/plugin-jsx_v^5.5.0/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@svgr/plugin-jsx'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@svgr/plugin-jsx' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@svgr/plugin-jsx/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@svgr/plugin-jsx/lib/index' {
  declare module.exports: $Exports<'@svgr/plugin-jsx/lib'>;
}
declare module '@svgr/plugin-jsx/lib/index.js' {
  declare module.exports: $Exports<'@svgr/plugin-jsx/lib'>;
}
