// @flow

export const NAMES = [
  "Accommodation",
  "AirHelp",
  "AirportTransport", // TODO: Get rid off 22.11
  "AirportTransportTaxi", // TODO: Get rid off 22.11
  "AirportShuttle",
  "AppQRCode",
  "BaggageDrop",
  "Boarding",
  "BoardingPass",
  "BusinessTravel",
  "CabinBaggage",
  "CompassCollectPoints",
  "CompassDemoted",
  "CompassEmailAdventurer",
  "CompassEmailCaptain",
  "CompassEmailPromoted",
  "CompassEmailPromotedCaptain",
  "CompassEmailScout",
  "CompassPoints",
  "CompassTravelPlan",
  "CompassSaveOnBooking",
  "DesktopSearch",
  "EnjoyApp",
  "Error",
  "Error404",
  "FastTrack",
  "Feedback",
  "Help",
  "Improve",
  "Insurance",
  "InviteAFriend",
  "GroundTransport404",
  "Login",
  "Lounge",
  "Mailbox",
  "Meal",
  "MobileApp",
  "Money",
  "MusicalInstruments",
  "NetVerify",
  "NoBookings", // TODO: Get rid off 22.11
  "NoFavoriteFlights",
  "Nomad",
  "NomadNeutral",
  "NoNotification",
  "NoResults",
  "Offline",
  "OnlineCheckIn",
  "OpenSearch",
  "Parking",
  "Pets",
  "PlaceholderAirport",
  "PlaceholderDestination",
  "PlaceholderHotel",
  "PlaceholderTours",
  "PlaneAndMoney",
  "PriorityBoarding",
  "Rating",
  "ReferAFriend",
  "RentalCar",
  "Seating",
  "SpecialAssistance",
  "SportsEquipment",
  "Success",
  "Time",
  "TicketFlexi",
  "TimelineBoarding", // TODO: Get rid off 22.11
  "TimelineDropBaggage", // TODO: Get rid off 22.11
  "TimelineLeave",
  "TimelinePick",
  "Tours",
  "Train",
  "TransportBus",
  "TransportTaxi",
  "WomanWithPhone",
];
