/*
  DOCUMENTATION: https://orbit.kiwi/components/illustration/
*/
import type React from "react";

import type * as Common from "../common/types";

export type Name =
  | "Accommodation"
  | "AirHelp"
  | "AirportTransportBus"
  | "AirportTransportTaxi"
  | "AppKiwi"
  | "AppQRCode"
  | "BaggageDrop"
  | "Boarding"
  | "BoardingPass"
  | "BusinessTravel"
  | "CabinBaggage"
  | "Cancelled"
  | "Chatbot"
  | "CompassCollectPoints"
  | "CompassDemoted"
  | "CompassEmailAdventurer"
  | "CompassEmailCaptain"
  | "CompassEmailPromoted"
  | "CompassEmailPromotedCaptain"
  | "CompassEmailScout"
  | "CompassPoints"
  | "CompassSaveOnBooking"
  | "CompassTravelPlan"
  | "CovidTest"
  | "DesktopSearch"
  | "EnjoyApp"
  | "Error"
  | "Error404"
  | "EVisa"
  | "ExclusiveOffers"
  | "FareLock"
  | "FareLockSuccess"
  | "FastBooking"
  | "FastTrack"
  | "FastTrackMan"
  | "Feedback"
  | "GroundTransport404"
  | "Help"
  | "Improve"
  | "Insurance"
  | "InviteAFriend"
  | "kek"
  | "Login"
  | "Lounge"
  | "Mailbox"
  | "Meal"
  | "MobileApp"
  | "MobileApp2"
  | "Money"
  | "MusicalInstruments"
  | "NetVerify"
  | "NoBookings"
  | "NoDiscount"
  | "NoFavoriteFlights"
  | "Nomad"
  | "NomadNeutral"
  | "NoNotification"
  | "NoResults"
  | "Offline"
  | "OnlineCheckIn"
  | "OpenSearch"
  | "Parking"
  | "Pets"
  | "PlaceholderAirport"
  | "PlaceholderDestination"
  | "PlaceholderHotel"
  | "PlaceholderTours"
  | "PlaneAndMoney"
  | "PlaneDelayed"
  | "PriorityBoarding"
  | "Rating"
  | "ReferAFriend"
  | "RentalCar"
  | "Seating"
  | "SpecialAssistance"
  | "SportsEquipment"
  | "Success"
  | "TicketFlexi"
  | "Time"
  | "TimelineBoarding"
  | "TimelineDropBaggage"
  | "TimelineLeave"
  | "TimelinePick"
  | "Tours"
  | "Train"
  | "TransporTaxi"
  | "TransportBus"
  | "UnfinishedBooking"
  | "WomanWithPhone";

// TODO: remove spaceAfter in the next major version
/** SpaceAfter is deprecated, use margin instead */

export interface Props extends Common.Globals, Common.SpaceAfter {
  readonly size?: "extraSmall" | "small" | "medium" | "large" | "display";
  readonly name: Name;
  readonly margin?: React.CSSProperties["margin"] | Common.ObjectProperty;
  readonly alt?: string;
}
