// Type definitions for @kiwicom/orbit-components
// Project: http://github.com/kiwicom/orbit
import type * as Common from "../common/types";

export type Indent = "none" | "small" | "medium" | "large" | "XLarge" | "XXLarge";
export type Align = "left" | "center" | "right";

export type PaletteTokens =
  | "paletteProductLight"
  | "paletteProductLightHover"
  | "paletteProductLightActive"
  | "paletteProductNormal"
  | "paletteProductNormalHover"
  | "paletteProductNormalActive"
  | "paletteProductDark"
  | "paletteProductDarkHover"
  | "paletteProductDarkActive"
  | "paletteProductDarker"
  | "paletteWhite"
  | "paletteWhiteHover"
  | "paletteWhiteActive"
  | "paletteCloudLight"
  | "paletteCloudLightHover"
  | "paletteCloudLightActive"
  | "paletteCloudNormal"
  | "paletteCloudNormalHover"
  | "paletteCloudNormalActive"
  | "paletteCloudDark"
  | "paletteCloudDarkHover"
  | "paletteCloudDarkActive"
  | "paletteInkLight"
  | "paletteInkLightHover"
  | "paletteInkLightActive"
  | "paletteInkDark"
  | "paletteInkDarkHover"
  | "paletteInkDarkActive"
  | "paletteInkNormal"
  | "paletteInkNormalHover"
  | "paletteInkNormalActive"
  | "paletteOrangeLight"
  | "paletteOrangeLightHover"
  | "paletteOrangeLightActive"
  | "paletteOrangeNormal"
  | "paletteOrangeNormalHover"
  | "paletteOrangeNormalActive"
  | "paletteOrangeDark"
  | "paletteOrangeDarkHover"
  | "paletteOrangeDarkActive"
  | "paletteOrangeDarker"
  | "paletteRedLight"
  | "paletteRedLightHover"
  | "paletteRedLightActive"
  | "paletteRedNormal"
  | "paletteRedNormalHover"
  | "paletteRedNormalActive"
  | "paletteRedDark"
  | "paletteRedDarkHover"
  | "paletteRedDarkActive"
  | "paletteRedDarker"
  | "paletteGreenLight"
  | "paletteGreenLightHover"
  | "paletteGreenLightActive"
  | "paletteGreenNormal"
  | "paletteGreenNormalHover"
  | "paletteGreenNormalActive"
  | "paletteGreenDark"
  | "paletteGreenDarkHover"
  | "paletteGreenDarkActive"
  | "paletteGreenDarker"
  | "paletteBlueLight"
  | "paletteBlueLightHover"
  | "paletteBundleBasic"
  | "paletteBundleMedium"
  | "paletteBlueLightActive"
  | "paletteBlueNormal"
  | "paletteBlueNormalHover"
  | "paletteBlueNormalActive"
  | "paletteBlueDark"
  | "paletteBlueDarkHover"
  | "paletteBlueDarkActive"
  | "paletteBlueDarker"
  | "paletteSocialFacebook"
  | "paletteSocialFacebookHover"
  | "paletteSocialFacebookActive";

export interface Props extends Common.SpaceAfter {
  indent?: Indent;
  type?: "solid" | "dashed" | "dotted" | "double" | "none";
  color?: PaletteTokens;
  align?: Align;
}
