import createTheme from "../createTheme";
import { defaultTheme } from "../..";

describe("createTheme", () => {
  it("should match defaultTheme without any parameters", () => {
    expect(createTheme()).toEqual(defaultTheme);
  });

  it("should create custom theme - colors", () => {
    const customFoundation = {
      palette: {
        blue: {
          // replaced for green for the test
          light: "#EBF4EC",
          lightSecondary: "#D7EAD9",
          lightTertiary: "#C3DFC7",
          normal: "#28A138",
          normalSecondary: "#238B31",
          normalTertiary: "#1D7228",
          dark: "#2B7336",
          darkSecondary: "#25642F",
          darkTertiary: "#1F5126",
          darker: "#235C2B",
        },
      },
    };

    const theme = createTheme(customFoundation);

    expect(theme.paletteBlueLight).toBe(customFoundation.palette.blue.light);
    expect(theme.paletteBlueLightHover).toBe(customFoundation.palette.blue.lightSecondary);
    expect(theme.paletteBlueLightSecondary).toBe(customFoundation.palette.blue.lightSecondary);
    expect(theme.paletteBlueLightActive).toBe(customFoundation.palette.blue.lightTertiary);
    expect(theme.paletteBlueLightTertiary).toBe(customFoundation.palette.blue.lightTertiary);
    expect(theme.paletteBlueNormal).toBe(customFoundation.palette.blue.normal);
    expect(theme.paletteBlueNormalHover).toBe(customFoundation.palette.blue.normalSecondary);
    expect(theme.paletteBlueNormalSecondary).toBe(customFoundation.palette.blue.normalSecondary);
    expect(theme.paletteBlueNormalActive).toBe(customFoundation.palette.blue.normalTertiary);
    expect(theme.paletteBlueNormalTertiary).toBe(customFoundation.palette.blue.normalTertiary);
    expect(theme.paletteBlueDark).toBe(customFoundation.palette.blue.dark);
    expect(theme.paletteBlueDarkHover).toBe(customFoundation.palette.blue.darkSecondary);
    expect(theme.paletteBlueDarkSecondary).toBe(customFoundation.palette.blue.darkSecondary);
    expect(theme.paletteBlueDarkActive).toBe(customFoundation.palette.blue.darkTertiary);
    expect(theme.paletteBlueDarkTertiary).toBe(customFoundation.palette.blue.darkTertiary);
    expect(theme.paletteBlueDarker).toBe(customFoundation.palette.blue.darker);
  });

  it("should override tokens", () => {
    const customFoundation = {
      palette: {
        blue: {
          // replaced for green for the test
          light: "#EBF4EC",
          lightSecondary: "#D7EAD9",
          lightTertiary: "#C3DFC7",
          normal: "#28A138",
          normalSecondary: "#238B31",
          normalTertiary: "#1D7228",
          dark: "#2B7336",
          darkSecondary: "#25642F",
          darkTertiary: "#1F5126",
          darker: "#235C2B",
        },
      },
    };

    expect(createTheme(customFoundation, { paletteBlueLight: "kek" })).toMatchInlineSnapshot(`
      Object {
        "alertButtonCriticalSubtleBackground": "#F4D2D2",
        "alertButtonCriticalSubtleBackgroundActive": "#EEB9B9",
        "alertButtonCriticalSubtleBackgroundHover": "#F4D2D2",
        "alertButtonCriticalSubtleBorderColorFocus": "rgba(210, 28, 28, 0.5)",
        "alertButtonCriticalSubtleForeground": "#970C0C",
        "alertButtonInfoBackground": "#28A138",
        "alertButtonInfoBackgroundActive": "#1D7228",
        "alertButtonInfoBackgroundHover": "#238B31",
        "alertButtonInfoBorderColorFocus": "rgba(40, 161, 56, 0.5)",
        "alertButtonInfoForeground": "#FFFFFF",
        "alertButtonInfoSubtleBackground": "#D7EAD9",
        "alertButtonInfoSubtleBackgroundActive": "#C3DFC7",
        "alertButtonInfoSubtleBackgroundHover": "#D7EAD9",
        "alertButtonInfoSubtleBorderColorFocus": "rgba(40, 161, 56, 0.5)",
        "alertButtonInfoSubtleForeground": "#2B7336",
        "alertButtonSuccessBackground": "#28A138",
        "alertButtonSuccessBackgroundActive": "#1D7228",
        "alertButtonSuccessBackgroundHover": "#238B31",
        "alertButtonSuccessBorderColorFocus": "rgba(40, 161, 56, 0.5)",
        "alertButtonSuccessForeground": "#FFFFFF",
        "alertButtonSuccessSubtleBackground": "#D7EAD9",
        "alertButtonSuccessSubtleBackgroundActive": "#C3DFC7",
        "alertButtonSuccessSubtleBackgroundHover": "#D7EAD9",
        "alertButtonSuccessSubtleBorderColorFocus": "rgba(40, 161, 56, 0.5)",
        "alertButtonSuccessSubtleForeground": "#2B7336",
        "alertButtonWarningBackground": "#E98305",
        "alertButtonWarningBackgroundActive": "#CD7304",
        "alertButtonWarningBackgroundHover": "#DC7C05",
        "alertButtonWarningBorderColorFocus": "rgba(233, 131, 5, 0.5)",
        "alertButtonWarningForeground": "#FFFFFF",
        "alertButtonWarningSubtleBackground": "#FAE2C7",
        "alertButtonWarningSubtleBackgroundActive": "#F8D3AB",
        "alertButtonWarningSubtleBackgroundHover": "#FAE2C7",
        "alertButtonWarningSubtleBorderColorFocus": "rgba(233, 131, 5, 0.5)",
        "alertButtonWarningSubtleForeground": "#A25100",
        "backgroundAlertCritical": "#FAEAEA",
        "backgroundAlertInfo": "#EBF4EC",
        "backgroundAlertSuccess": "#EBF4EC",
        "backgroundAlertWarning": "#FDF0E3",
        "backgroundBadgeCritical": "#FAEAEA",
        "backgroundBadgeDark": "#252A31",
        "backgroundBadgeInfo": "#EBF4EC",
        "backgroundBadgeNeutral": "#F5F7F9",
        "backgroundBadgeSuccess": "#EBF4EC",
        "backgroundBadgeWarning": "#FDF0E3",
        "backgroundBadgeWhite": "#FFFFFF",
        "backgroundBody": "#F5F7F9",
        "backgroundButtonBordered": "transparent",
        "backgroundButtonBorderedActive": "#F5F7F9",
        "backgroundButtonBorderedHover": "#F5F7F9",
        "backgroundButtonCritical": "#D21C1C",
        "backgroundButtonCriticalActive": "#9D1515",
        "backgroundButtonCriticalHover": "#B91919",
        "backgroundButtonFacebook": "#3B5998",
        "backgroundButtonFacebookActive": "#354F88",
        "backgroundButtonFacebookHover": "#385490",
        "backgroundButtonGoogle": "#F5F7F9",
        "backgroundButtonGoogleActive": "#D6DEE6",
        "backgroundButtonGoogleHover": "#E5EAEF",
        "backgroundButtonInfo": "#28A138",
        "backgroundButtonInfoActive": "#1D7228",
        "backgroundButtonInfoHover": "#238B31",
        "backgroundButtonLinkPrimary": "transparent",
        "backgroundButtonLinkPrimaryActive": "#D6DEE6",
        "backgroundButtonLinkPrimaryHover": "#E5EAEF",
        "backgroundButtonLinkSecondary": "transparent",
        "backgroundButtonLinkSecondaryActive": "#D6DEE6",
        "backgroundButtonLinkSecondaryHover": "#E5EAEF",
        "backgroundButtonPrimary": "#00A991",
        "backgroundButtonPrimaryActive": "#008F7B",
        "backgroundButtonPrimaryHover": "#009882",
        "backgroundButtonSecondary": "#E8EDF1",
        "backgroundButtonSecondaryActive": "#CAD4DE",
        "backgroundButtonSecondaryHover": "#DCE3E9",
        "backgroundButtonSuccess": "#28A138",
        "backgroundButtonSuccessActive": "#1D7228",
        "backgroundButtonSuccessHover": "#238B31",
        "backgroundButtonWarning": "#E98305",
        "backgroundButtonWarningActive": "#CD7304",
        "backgroundButtonWarningHover": "#DC7C05",
        "backgroundButtonWhite": "#FFFFFF",
        "backgroundButtonWhiteActive": "#E5EAEF",
        "backgroundButtonWhiteBordered": "transparent",
        "backgroundButtonWhiteBorderedActive": "rgba(255, 255, 255, 0.2)",
        "backgroundButtonWhiteBorderedHover": "rgba(255, 255, 255, 0.2)",
        "backgroundButtonWhiteHover": "#F5F7F9",
        "backgroundCard": "#FFFFFF",
        "backgroundCarrierLogo": "transparent",
        "backgroundCountryFlag": "transparent",
        "backgroundIllustration": "transparent",
        "backgroundInput": "#FFFFFF",
        "backgroundInputDisabled": "#EFF2F5",
        "backgroundModal": "#FFFFFF",
        "backgroundSeparator": "#EFF2F5",
        "backgroundServiceLogo": "transparent",
        "backgroundTable": "#FFFFFF",
        "backgroundTableEven": "#F5F7F9",
        "backgroundTableHover": "#EFF2F5",
        "backgroundTableShadowLeft": "linear-gradient(to left, transparent, rgba(186, 199, 213, 23))",
        "backgroundTableShadowRight": "linear-gradient(to right, transparent, rgba(186, 199, 213, 23))",
        "backgroundTag": "#F5F7F9",
        "backgroundTagActive": "#D6DEE6",
        "backgroundTagHover": "#E5EAEF",
        "backgroundTagSelected": "#252A31",
        "backgroundTagSelectedActive": "#0B0C0F",
        "backgroundTagSelectedHover": "#181B20",
        "backgroundTooltip": "#FFFFFF",
        "backgroundTooltipLargeMobile": "#2B7336",
        "badgeBundleBasicBackground": "linear-gradient(to top right, #E13E3B 0%, #E87E09 100%)",
        "badgeBundleMediumBackground": "linear-gradient(to top right, #3719AB 0%, #8539DB 100%)",
        "badgeBundleTopBackground": "linear-gradient(to top right, #2D2D2E 0%, #696E73 100%)",
        "borderColorButtonCriticalBordered": "#D21C1C",
        "borderColorButtonCriticalBorderedActive": "#9D1515",
        "borderColorButtonCriticalBorderedHover": "#B91919",
        "borderColorButtonFacebookBordered": "#3B5998",
        "borderColorButtonFacebookBorderedActive": "#354F88",
        "borderColorButtonFacebookBorderedHover": "#385490",
        "borderColorButtonGoogleBordered": "#252A31",
        "borderColorButtonGoogleBorderedActive": "#0B0C0F",
        "borderColorButtonGoogleBorderedHover": "#181B20",
        "borderColorButtonInfoBordered": "#28A138",
        "borderColorButtonInfoBorderedActive": "#1D7228",
        "borderColorButtonInfoBorderedHover": "#238B31",
        "borderColorButtonPrimaryBordered": "#00A991",
        "borderColorButtonPrimaryBorderedActive": "#008F7B",
        "borderColorButtonPrimaryBorderedHover": "#009882",
        "borderColorButtonSecondaryBordered": "#252A31",
        "borderColorButtonSecondaryBorderedActive": "#0B0C0F",
        "borderColorButtonSecondaryBorderedHover": "#181B20",
        "borderColorButtonSuccessBordered": "#28A138",
        "borderColorButtonSuccessBorderedActive": "#1D7228",
        "borderColorButtonSuccessBorderedHover": "#238B31",
        "borderColorButtonWarningBordered": "#E98305",
        "borderColorButtonWarningBorderedActive": "#CD7304",
        "borderColorButtonWarningBorderedHover": "#DC7C05",
        "borderColorButtonWhiteBordered": "#FFFFFF",
        "borderColorButtonWhiteBorderedActive": "#FFFFFF",
        "borderColorButtonWhiteBorderedHover": "#FFFFFF",
        "borderColorCard": "#EFF2F5",
        "borderColorCheckboxRadio": "#697D95",
        "borderColorCheckboxRadioActive": "#252A31",
        "borderColorCheckboxRadioError": "#D21C1C",
        "borderColorCheckboxRadioFocus": "#28A138",
        "borderColorCheckboxRadioHover": "#4F5E71",
        "borderColorInput": "#697D95",
        "borderColorInputActive": "#4A617C",
        "borderColorInputError": "#D21C1C",
        "borderColorInputErrorFocus": "#D21C1C",
        "borderColorInputErrorHover": "#B91919",
        "borderColorInputFocus": "#28A138",
        "borderColorInputHover": "#5D738E",
        "borderColorModal": "#EFF2F5",
        "borderColorTable": "#EFF2F5",
        "borderColorTableCell": "#697D95",
        "borderColorTableHead": "#697D95",
        "borderColorTag": "#EFF2F5",
        "borderColorTagFocus": "#28A138",
        "borderRadiusBadge": "12px",
        "borderRadiusCircle": "50%",
        "borderRadiusLarge": "6px",
        "borderRadiusNormal": "3px",
        "borderRadiusSmall": "2px",
        "borderStyleCard": "solid",
        "borderStyleInput": "solid",
        "borderWidthCard": "1px",
        "borderWidthInput": "1px",
        "borderWidthInputFocus": "2px",
        "boxShadowAction": "0 0 2px 0 rgba(37, 42, 49, 0.16),0 1px 4px 0 rgba(37, 42, 49, 0.12)",
        "boxShadowActionActive": "0 1px 4px 0 rgba(37, 42, 49, 0.16),0 4px 8px 0 rgba(37, 42, 49, 0.12)",
        "boxShadowButtonFocus": "0 0 4px 1px rgba(40, 161, 56, 0.3)",
        "boxShadowFixed": "0 0 2px 0 rgba(37, 42, 49, 0.16),0 2px 4px 0 rgba(37, 42, 49, 0.12)",
        "boxShadowFixedReverse": "0 0 2px 0 rgba(37, 42, 49, 0.16),0 -2px 4px 0 rgba(37, 42, 49, 0.12)",
        "boxShadowOverlay": "0 12px 24px -4px rgba(37, 42, 49, 0.24),0 8px 60px 0 rgba(37, 42, 49, 0.32)",
        "boxShadowRaised": "0 4px 8px 0 rgba(37, 42, 49, 0.16),0 8px 24px 0 rgba(37, 42, 49, 0.24)",
        "boxShadowRaisedReverse": "0 -4px 8px 0 rgba(37, 42, 49, 0.16),0 -8px 24px 0 rgba(37, 42, 49, 0.24)",
        "breakpointDesktop": 992,
        "breakpointLargeDesktop": 1200,
        "breakpointLargeMobile": 576,
        "breakpointMediumMobile": 414,
        "breakpointTablet": 768,
        "buttonBundleBasicBackground": "linear-gradient(to top right, #E13E3B 0%, #E87E09 100%)",
        "buttonBundleBasicBackgroundActive": "linear-gradient(to top right, #9F1816 0%, #C36802 100%)",
        "buttonBundleBasicBackgroundHover": "linear-gradient(to top right, #BD2825 0%, #D67000 100%)",
        "buttonBundleMediumBackground": "linear-gradient(to top right, #3719AB 0%, #8539DB 100%)",
        "buttonBundleMediumBackgroundActive": "linear-gradient(to top right, #250F79 0%, #5A3485 100%)",
        "buttonBundleMediumBackgroundHover": "linear-gradient(to top right, #BD2825 0%, #D67000 100%)",
        "buttonBundleTopBackground": "linear-gradient(to top right, #2D2D2E 0%, #696E73 100%)",
        "buttonBundleTopBackgroundActive": "linear-gradient(to top right, #101011 0%, #51575C)",
        "buttonBundleTopBackgroundHover": "linear-gradient(to top right, #171718 0%, #51575C 100%)",
        "buttonCriticalBackground": "#D21C1C",
        "buttonCriticalBackgroundActive": "#9D1515",
        "buttonCriticalBackgroundHover": "#B91919",
        "buttonCriticalBorderColorFocus": "rgba(210, 28, 28, 0.5)",
        "buttonCriticalForeground": "#FFFFFF",
        "buttonCriticalForegroundActive": "#FFFFFF",
        "buttonCriticalForegroundHover": "#FFFFFF",
        "buttonCriticalSubtleBackground": "#FAEAEA",
        "buttonCriticalSubtleBackgroundActive": "#EEB9B9",
        "buttonCriticalSubtleBackgroundHover": "#F4D2D2",
        "buttonCriticalSubtleBorderColorFocus": "rgba(210, 28, 28, 0.5)",
        "buttonCriticalSubtleForeground": "#D21C1C",
        "buttonCriticalSubtleForegroundActive": "#970C0C",
        "buttonCriticalSubtleForegroundHover": "#970C0C",
        "buttonDisabledOpacity": "0.3",
        "buttonLargeBothIconsPadding": "0 16px",
        "buttonLargeFontSize": "16px",
        "buttonLargeLeftIconPadding": "0 28px 0 16px",
        "buttonLargePadding": "0 28px",
        "buttonLargeRightIconPadding": "0 16px 0 28px",
        "buttonLinkCriticalBackground": "transparent",
        "buttonLinkCriticalBackgroundActive": "#EEB9B9",
        "buttonLinkCriticalBackgroundHover": "#F4D2D2",
        "buttonLinkCriticalForeground": "#D21C1C",
        "buttonLinkCriticalForegroundActive": "#9D1515",
        "buttonLinkCriticalForegroundHover": "#B91919",
        "buttonLinkPrimaryBackground": "transparent",
        "buttonLinkPrimaryBackgroundActive": "#C0E8E4",
        "buttonLinkPrimaryBackgroundHover": "#D6F0EE",
        "buttonLinkPrimaryForeground": "#00A991",
        "buttonLinkPrimaryForegroundActive": "#008F7B",
        "buttonLinkPrimaryForegroundHover": "#009882",
        "buttonLinkSecondaryBackground": "transparent",
        "buttonLinkSecondaryBackgroundActive": "#D6DEE6",
        "buttonLinkSecondaryBackgroundHover": "#E5EAEF",
        "buttonLinkSecondaryForeground": "#252A31",
        "buttonLinkSecondaryForegroundActive": "#0B0C0F",
        "buttonLinkSecondaryForegroundHover": "#181B20",
        "buttonNormalBothIconsPadding": "0 12px",
        "buttonNormalFontSize": "14px",
        "buttonNormalLeftIconPadding": "0 16px 0 12px",
        "buttonNormalPadding": "0 16px",
        "buttonNormalRightIconPadding": "0 12px 0 16px",
        "buttonPrimaryBackground": "#00A991",
        "buttonPrimaryBackgroundActive": "#008F7B",
        "buttonPrimaryBackgroundHover": "#009882",
        "buttonPrimaryBorderColorFocus": "rgba(0, 169, 145, 0.5)",
        "buttonPrimaryForeground": "#FFFFFF",
        "buttonPrimaryForegroundActive": "#FFFFFF",
        "buttonPrimaryForegroundHover": "#FFFFFF",
        "buttonPrimarySubtleBackground": "#ECF8F7",
        "buttonPrimarySubtleBackgroundActive": "#C0E8E4",
        "buttonPrimarySubtleBackgroundHover": "#D6F0EE",
        "buttonPrimarySubtleBorderColorFocus": "rgba(0, 169, 145, 0.5)",
        "buttonPrimarySubtleForeground": "#00A991",
        "buttonPrimarySubtleForegroundActive": "#007F6D",
        "buttonPrimarySubtleForegroundHover": "#007F6D",
        "buttonSecondaryBackground": "#E8EDF1",
        "buttonSecondaryBackgroundActive": "#CAD4DE",
        "buttonSecondaryBackgroundHover": "#DCE3E9",
        "buttonSecondaryBorderColorFocus": "rgba(79, 94, 113, 0.3)",
        "buttonSecondaryForeground": "#252A31",
        "buttonSecondaryForegroundActive": "#181B20",
        "buttonSecondaryForegroundHover": "#181B20",
        "buttonSmallBothIconsPadding": "0 8px",
        "buttonSmallFontSize": "12px",
        "buttonSmallLeftIconPadding": "0 12px 0 8px",
        "buttonSmallPadding": "0 12px",
        "buttonSmallRightIconPadding": "0 8px 0 12px",
        "buttonWhiteBackground": "#FFFFFF",
        "buttonWhiteBackgroundActive": "#E5EAEF",
        "buttonWhiteBackgroundHover": "#F5F7F9",
        "buttonWhiteBorderColorFocus": "rgba(231, 236, 241, 0.5)",
        "buttonWhiteForeground": "#252A31",
        "buttonWhiteForegroundActive": "#0B0C0F",
        "buttonWhiteForegroundHover": "#181B20",
        "buttonWithoutTextPadding": "0",
        "colorAlertIconCritical": "#D21C1C",
        "colorAlertIconInfo": "#28A138",
        "colorAlertIconSuccess": "#28A138",
        "colorAlertIconWarning": "#E98305",
        "colorFormLabel": "#252A31",
        "colorFormLabelFilled": "#4F5E71",
        "colorHeading": "#252A31",
        "colorHeadingInverted": "#FFFFFF",
        "colorIconCheckboxRadio": "#00A991",
        "colorIconCheckboxRadioDisabled": "#697D95",
        "colorIconCritical": "#D21C1C",
        "colorIconInfo": "#28A138",
        "colorIconInput": "#697D95",
        "colorIconPrimary": "#252A31",
        "colorIconRadioButton": "#00A991",
        "colorIconRadioButtonDisabled": "#697D95",
        "colorIconSecondary": "#4F5E71",
        "colorIconSuccess": "#28A138",
        "colorIconTertiary": "#697D95",
        "colorIconWarning": "#E98305",
        "colorInfoCheckBoxRadio": "#4F5E71",
        "colorPlaceholderInput": "#697D95",
        "colorPlaceholderInputError": "#D21C1C",
        "colorPlaceholderInputFile": "#4F5E71",
        "colorPlaceholderInputFileError": "#D21C1C",
        "colorStopoverArrow": "#4F5E71",
        "colorTextAlertCritical": "#970C0C",
        "colorTextAlertInfo": "#2B7336",
        "colorTextAlertLink": "#252A31",
        "colorTextAlertSuccess": "#2B7336",
        "colorTextAlertWarning": "#A25100",
        "colorTextBadgeCritical": "#D21C1C",
        "colorTextBadgeDark": "#FFFFFF",
        "colorTextBadgeInfo": "#28A138",
        "colorTextBadgeNeutral": "#252A31",
        "colorTextBadgeSuccess": "#28A138",
        "colorTextBadgeWarning": "#E98305",
        "colorTextBadgeWhite": "#252A31",
        "colorTextButtonCritical": "#FFFFFF",
        "colorTextButtonCriticalActive": "#FFFFFF",
        "colorTextButtonCriticalBordered": "#D21C1C",
        "colorTextButtonCriticalBorderedActive": "#9D1515",
        "colorTextButtonCriticalBorderedHover": "#B91919",
        "colorTextButtonCriticalHover": "#FFFFFF",
        "colorTextButtonFacebook": "#FFFFFF",
        "colorTextButtonFacebookActive": "#FFFFFF",
        "colorTextButtonFacebookBordered": "#3B5998",
        "colorTextButtonFacebookBorderedActive": "#354F88",
        "colorTextButtonFacebookBorderedHover": "#385490",
        "colorTextButtonFacebookHover": "#FFFFFF",
        "colorTextButtonFilled": "#FFFFFF",
        "colorTextButtonFilledActive": "#FFFFFF",
        "colorTextButtonFilledHover": "#FFFFFF",
        "colorTextButtonGoogle": "#252A31",
        "colorTextButtonGoogleActive": "#0B0C0F",
        "colorTextButtonGoogleBordered": "#252A31",
        "colorTextButtonGoogleBorderedActive": "#0B0C0F",
        "colorTextButtonGoogleBorderedHover": "#181B20",
        "colorTextButtonGoogleHover": "#181B20",
        "colorTextButtonInfo": "#FFFFFF",
        "colorTextButtonInfoActive": "#FFFFFF",
        "colorTextButtonInfoBordered": "#28A138",
        "colorTextButtonInfoBorderedActive": "#1D7228",
        "colorTextButtonInfoBorderedHover": "#238B31",
        "colorTextButtonInfoHover": "#FFFFFF",
        "colorTextButtonLinkPrimary": "#00A991",
        "colorTextButtonLinkPrimaryActive": "#008F7B",
        "colorTextButtonLinkPrimaryHover": "#009882",
        "colorTextButtonLinkSecondary": "#252A31",
        "colorTextButtonLinkSecondaryActive": "#0B0C0F",
        "colorTextButtonLinkSecondaryHover": "#181B20",
        "colorTextButtonPrimary": "#FFFFFF",
        "colorTextButtonPrimaryActive": "#FFFFFF",
        "colorTextButtonPrimaryBordered": "#00A991",
        "colorTextButtonPrimaryBorderedActive": "#008F7B",
        "colorTextButtonPrimaryBorderedHover": "#009882",
        "colorTextButtonPrimaryHover": "#FFFFFF",
        "colorTextButtonSecondary": "#252A31",
        "colorTextButtonSecondaryActive": "#181B20",
        "colorTextButtonSecondaryBordered": "#252A31",
        "colorTextButtonSecondaryBorderedActive": "#181B20",
        "colorTextButtonSecondaryBorderedHover": "#181B20",
        "colorTextButtonSecondaryHover": "#181B20",
        "colorTextButtonSuccess": "#FFFFFF",
        "colorTextButtonSuccessActive": "#FFFFFF",
        "colorTextButtonSuccessBordered": "#28A138",
        "colorTextButtonSuccessBorderedActive": "#1D7228",
        "colorTextButtonSuccessBorderedHover": "#238B31",
        "colorTextButtonSuccessHover": "#FFFFFF",
        "colorTextButtonWarning": "#FFFFFF",
        "colorTextButtonWarningActive": "#FFFFFF",
        "colorTextButtonWarningBordered": "#E98305",
        "colorTextButtonWarningBorderedActive": "#CD7304",
        "colorTextButtonWarningBorderedHover": "#DC7C05",
        "colorTextButtonWarningHover": "#FFFFFF",
        "colorTextButtonWhite": "#252A31",
        "colorTextButtonWhiteActive": "#0B0C0F",
        "colorTextButtonWhiteBordered": "#FFFFFF",
        "colorTextButtonWhiteBorderedActive": "#FFFFFF",
        "colorTextButtonWhiteBorderedHover": "#FFFFFF",
        "colorTextButtonWhiteHover": "#181B20",
        "colorTextCritical": "#D21C1C",
        "colorTextError": "#D21C1C",
        "colorTextInfo": "#28A138",
        "colorTextInput": "#252A31",
        "colorTextInputDisabled": "#697D95",
        "colorTextInputPrefix": "#4F5E71",
        "colorTextLinkPrimary": "#007F6D",
        "colorTextLinkPrimaryHover": "#00A991",
        "colorTextLinkSecondary": "#252A31",
        "colorTextLinkSecondaryHover": "#00A991",
        "colorTextLoading": "#697D95",
        "colorTextPrimary": "#252A31",
        "colorTextSecondary": "#4F5E71",
        "colorTextSuccess": "#28A138",
        "colorTextTable": "#4F5E71",
        "colorTextTag": "#252A31",
        "colorTextTagSelected": "#EFF2F5",
        "colorTextWarning": "#E98305",
        "colorTextWhite": "#FFFFFF",
        "durationFast": "0.15s",
        "durationNormal": "0.3s",
        "durationSlow": "0.4s",
        "elevationActionActiveBackground": "#FFFFFF",
        "elevationActionActiveBoxShadow": "0 1px 4px 0 rgba(37, 42, 49, 0.16),0 4px 8px 0 rgba(37, 42, 49, 0.12)",
        "elevationActionBackground": "#FFFFFF",
        "elevationActionBoxShadow": "0 0 2px 0 rgba(37, 42, 49, 0.16),0 1px 4px 0 rgba(37, 42, 49, 0.12)",
        "elevationFixedBackground": "#FFFFFF",
        "elevationFixedBoxShadow": "0 0 2px 0 rgba(37, 42, 49, 0.16),0 2px 4px 0 rgba(37, 42, 49, 0.12)",
        "elevationFixedReverseBackground": "#FFFFFF",
        "elevationFixedReverseBoxShadow": "0 0 2px 0 rgba(37, 42, 49, 0.16),0 -2px 4px 0 rgba(37, 42, 49, 0.12)",
        "elevationFlatBackground": "#FFFFFF",
        "elevationFlatBorderColor": "#EFF2F5",
        "elevationFlatBorderSize": "1px",
        "elevationOverlayBackground": "#FFFFFF",
        "elevationOverlayBoxShadow": "0 12px 24px -4px rgba(37, 42, 49, 0.24),0 8px 60px 0 rgba(37, 42, 49, 0.32)",
        "elevationRaisedBackground": "#FFFFFF",
        "elevationRaisedBoxShadow": "0 4px 8px 0 rgba(37, 42, 49, 0.16),0 8px 24px 0 rgba(37, 42, 49, 0.24)",
        "elevationRaisedReverseBackground": "#FFFFFF",
        "elevationRaisedReverseBoxShadow": "0 -4px 8px 0 rgba(37, 42, 49, 0.16),0 -8px 24px 0 rgba(37, 42, 49, 0.24)",
        "elevationSuppressedBackground": "#F5F7F9",
        "fontFamily": "'Roboto', -apple-system, '.SFNSText-Regular', 'San Francisco', 'Segoe UI', 'Helvetica Neue', 'Lucida Grande', sans-serif",
        "fontSizeButtonLarge": "16px",
        "fontSizeButtonNormal": "14px",
        "fontSizeButtonSmall": "12px",
        "fontSizeFormFeedback": "12px",
        "fontSizeFormLabel": "14px",
        "fontSizeHeadingDisplay": "40px",
        "fontSizeHeadingDisplaySubtitle": "22px",
        "fontSizeHeadingTitle1": "28px",
        "fontSizeHeadingTitle2": "22px",
        "fontSizeHeadingTitle3": "16px",
        "fontSizeHeadingTitle4": "14px",
        "fontSizeHeadingTitle5": "12px",
        "fontSizeInputNormal": "14px",
        "fontSizeInputSmall": "14px",
        "fontSizeLarge": "16px",
        "fontSizeMessage": "14px",
        "fontSizeNormal": "14px",
        "fontSizeSmall": "12px",
        "fontSizeTextLarge": "16px",
        "fontSizeTextNormal": "14px",
        "fontSizeTextSmall": "12px",
        "fontWeightBold": "700",
        "fontWeightHeadingDisplay": "700",
        "fontWeightHeadingDisplaySubtitle": "400",
        "fontWeightHeadingTitle1": "700",
        "fontWeightHeadingTitle2": "500",
        "fontWeightHeadingTitle3": "500",
        "fontWeightHeadingTitle4": "500",
        "fontWeightHeadingTitle5": "700",
        "fontWeightLinks": "500",
        "fontWeightMedium": "500",
        "fontWeightNormal": "400",
        "fontWeightTableHead": "700",
        "formBoxLargeHeight": "52px",
        "formBoxNormalHeight": "44px",
        "formBoxSmallHeight": "32px",
        "formElementBackground": "#FFFFFF",
        "formElementBorderColor": "#697D95",
        "formElementBorderColorError": "#D21C1C",
        "formElementBorderColorFocus": "#28A138",
        "formElementBorderColorHover": "#5D738E",
        "formElementDisabledBackground": "#EFF2F5",
        "formElementDisabledForeground": "#697D95",
        "formElementDisabledOpacity": "0.5",
        "formElementErrorFocusBoxShadow": "inset 0 0 0 1px rgba(210, 28, 28, 1),inset 0 0 0 3px rgba(210, 28, 28, 0.15)",
        "formElementFilledForeground": "#252A31",
        "formElementFocusBoxShadow": "inset 0 0 0 1px rgba(40, 161, 56, 1),inset 0 0 0 3px rgba(40, 161, 56, 0.15)",
        "formElementForeground": "#697D95",
        "formElementLabelFilled": "#4F5E71",
        "formElementLabelForeground": "#252A31",
        "formElementNormalFontSize": "14px",
        "formElementNormalPadding": "0 12px",
        "formElementPrefixForeground": "#4F5E71",
        "formElementSmallFontSize": "14px",
        "formElementSmallPadding": "0 12px",
        "headingDisplayFontSize": "40px",
        "headingDisplayFontWeight": "700",
        "headingDisplayLineHeight": "44px",
        "headingDisplaySubtitleFontSize": "22px",
        "headingDisplaySubtitleFontWeight": "400",
        "headingDisplaySubtitleLineHeight": "28px",
        "headingForeground": "#252A31",
        "headingForegroundInverted": "#FFFFFF",
        "headingTitle1FontSize": "28px",
        "headingTitle1FontWeight": "700",
        "headingTitle1LineHeight": "36px",
        "headingTitle2FontSize": "22px",
        "headingTitle2FontWeight": "500",
        "headingTitle2LineHeight": "28px",
        "headingTitle3FontSize": "16px",
        "headingTitle3FontWeight": "500",
        "headingTitle3LineHeight": "24px",
        "headingTitle4FontSize": "14px",
        "headingTitle4FontWeight": "500",
        "headingTitle4LineHeight": "20px",
        "headingTitle5FontSize": "12px",
        "headingTitle5FontWeight": "700",
        "headingTitle5LineHeight": "20px",
        "heightBadge": "24px",
        "heightButtonLarge": "52px",
        "heightButtonNormal": "44px",
        "heightButtonSmall": "32px",
        "heightCheckbox": "20px",
        "heightCountryFlag": "auto",
        "heightIconLarge": "32px",
        "heightIconMedium": "24px",
        "heightIconSmall": "16px",
        "heightIllustrationMedium": "200px",
        "heightIllustrationSmall": "90px",
        "heightInputGroupSeparatorNormal": "24px",
        "heightInputGroupSeparatorSmall": "16px",
        "heightInputLarge": "52px",
        "heightInputNormal": "44px",
        "heightInputSmall": "32px",
        "heightRadioButton": "20px",
        "heightSeparator": "1px",
        "heightServiceLogoLarge": "48px",
        "heightServiceLogoMedium": "24px",
        "heightServiceLogoSmall": "12px",
        "heightStopoverArrow": "7px",
        "iconCriticalForeground": "#D21C1C",
        "iconExtraExtraSmallSize": "12px",
        "iconExtraLargeSize": "48px",
        "iconExtraSmallSize": "16px",
        "iconInfoForeground": "#28A138",
        "iconLargeSize": "32px",
        "iconMediumSize": "24px",
        "iconPrimaryForeground": "#252A31",
        "iconSecondaryForeground": "#4F5E71",
        "iconSmallSize": "20px",
        "iconSuccessForeground": "#28A138",
        "iconTertiaryForeground": "#697D95",
        "iconWarningForeground": "#E98305",
        "illustrationDisplayHeight": "460px",
        "illustrationExtraSmallHeight": "90px",
        "illustrationLargeHeight": "280px",
        "illustrationMediumHeight": "200px",
        "illustrationSmallHeight": "120px",
        "lineHeightHeading": "1.2",
        "lineHeightHeadingDisplay": "44px",
        "lineHeightHeadingDisplaySubtitle": "28px",
        "lineHeightHeadingTitle1": "36px",
        "lineHeightHeadingTitle2": "28px",
        "lineHeightHeadingTitle3": "24px",
        "lineHeightHeadingTitle4": "20px",
        "lineHeightHeadingTitle5": "20px",
        "lineHeightLarge": "22px",
        "lineHeightNormal": "20px",
        "lineHeightSmall": "16px",
        "lineHeightText": "1.4",
        "lineHeightTextLarge": "22px",
        "lineHeightTextNormal": "20px",
        "lineHeightTextSmall": "16px",
        "marginBadgeIcon": "0 4px 0 0",
        "marginBottomSelectSuffix": "2px",
        "marginButtonGroup": "0 1px 0 0",
        "marginButtonIconLarge": "12px",
        "marginButtonIconNormal": "8px",
        "marginButtonIconSmall": "8px",
        "marginTopFormFeedback": "2px",
        "modalExtraLargeWidth": "1280px",
        "modalExtraSmallWidth": "360px",
        "modalLargeWidth": "900px",
        "modalNormalWidth": "740px",
        "modalSmallWidth": "540px",
        "modifierScaleButtonActive": 0.95,
        "modifierScaleCheckboxRadioActive": 0.95,
        "opacityButtonDisabled": "0.3",
        "opacityCheckboxDisabled": "0.5",
        "opacityOverlay": "0.8",
        "opacityRadioButtonDisabled": "0.5",
        "paddingAlert": "16px",
        "paddingAlertWithIcon": "12px",
        "paddingBadge": "0 8px",
        "paddingButtonLarge": "0 28px",
        "paddingButtonLargeWithIcons": "0 16px",
        "paddingButtonLargeWithLeftIcon": "0 28px 0 16px",
        "paddingButtonLargeWithRightIcon": "0 16px 0 28px",
        "paddingButtonNormal": "0 16px",
        "paddingButtonNormalWithIcons": "0 12px",
        "paddingButtonNormalWithLeftIcon": "0 16px 0 12px",
        "paddingButtonNormalWithRightIcon": "0 12px 0 16px",
        "paddingButtonSmall": "0 12px",
        "paddingButtonSmallWithIcons": "0 8px",
        "paddingButtonSmallWithLeftIcon": "0 12px 0 8px",
        "paddingButtonSmallWithRightIcon": "0 8px 0 12px",
        "paddingButtonWithoutText": "0",
        "paddingInputFile": "0 0 0 6px",
        "paddingInputNormal": "0 12px",
        "paddingInputSmall": "0 12px",
        "paddingLeftSelectPrefix": "48px",
        "paddingLoading": "12px",
        "paddingTable": "12px 16px",
        "paddingTableCompact": "8px 12px",
        "paddingTag": "6px 8px",
        "paddingTagRemovable": "6px 6px 6px 8px",
        "paddingTagRemovableWithIcon": "6px",
        "paddingTagWithIcon": "6px 8px 6px 6px",
        "paddingTextareaNormal": "12px",
        "paddingTextareaSmall": "8px 12px",
        "paletteBlueDark": "#2B7336",
        "paletteBlueDarkActive": "#1F5126",
        "paletteBlueDarkHover": "#25642F",
        "paletteBlueDarkSecondary": "#25642F",
        "paletteBlueDarkTertiary": "#1F5126",
        "paletteBlueDarker": "#235C2B",
        "paletteBlueLight": "kek",
        "paletteBlueLightActive": "#C3DFC7",
        "paletteBlueLightHover": "#D7EAD9",
        "paletteBlueLightSecondary": "#D7EAD9",
        "paletteBlueLightTertiary": "#C3DFC7",
        "paletteBlueNormal": "#28A138",
        "paletteBlueNormalActive": "#1D7228",
        "paletteBlueNormalHover": "#238B31",
        "paletteBlueNormalSecondary": "#238B31",
        "paletteBlueNormalTertiary": "#1D7228",
        "paletteCloudDark": "#E8EDF1",
        "paletteCloudDarker": "#BAC7D5",
        "paletteCloudDarkerActive": "#94A8BE",
        "paletteCloudDarkerHover": "#A6B6C8",
        "paletteCloudLight": "#F5F7F9",
        "paletteCloudLightActive": "#D6DEE6",
        "paletteCloudLightHover": "#E5EAEF",
        "paletteCloudLightSecondary": "#E5EAEF",
        "paletteCloudLightTertiary": "#D6DEE6",
        "paletteCloudNormal": "#EFF2F5",
        "paletteCloudNormalActive": "#CAD4DE",
        "paletteCloudNormalHover": "#DCE3E9",
        "paletteCloudNormalSecondary": "#DCE3E9",
        "paletteCloudNormalTertiary": "#CAD4DE",
        "paletteGreenDark": "#2B7336",
        "paletteGreenDarkActive": "#1F5126",
        "paletteGreenDarkHover": "#25642F",
        "paletteGreenDarkSecondary": "#25642F",
        "paletteGreenDarkTertiary": "#1F5126",
        "paletteGreenDarker": "#235C2B",
        "paletteGreenLight": "#EBF4EC",
        "paletteGreenLightActive": "#C3DFC7",
        "paletteGreenLightHover": "#D7EAD9",
        "paletteGreenLightSecondary": "#D7EAD9",
        "paletteGreenLightTertiary": "#C3DFC7",
        "paletteGreenNormal": "#28A138",
        "paletteGreenNormalActive": "#1D7228",
        "paletteGreenNormalHover": "#238B31",
        "paletteGreenNormalSecondary": "#238B31",
        "paletteGreenNormalTertiary": "#1D7228",
        "paletteInkLight": "#4F5E71",
        "paletteInkLightActive": "#324256",
        "paletteInkLightHover": "#3E4E63",
        "paletteInkLightSecondary": "#3E4E63",
        "paletteInkLightTertiary": "#324256",
        "paletteInkLighter": "#697D95",
        "paletteInkLighterActive": "#4A617C",
        "paletteInkLighterHover": "#5D738E",
        "paletteInkLighterSecondary": "#5D738E",
        "paletteInkLighterTertiary": "#4A617C",
        "paletteInkNormal": "#252A31",
        "paletteInkNormalActive": "#0B0C0F",
        "paletteInkNormalHover": "#181B20",
        "paletteInkNormalSecondary": "#181B20",
        "paletteInkNormalTertiary": "#0B0C0F",
        "paletteOrangeDark": "#A25100",
        "paletteOrangeDarkActive": "#753A00",
        "paletteOrangeDarkHover": "#8F4700",
        "paletteOrangeDarkSecondary": "#8F4700",
        "paletteOrangeDarkTertiary": "#753A00",
        "paletteOrangeDarker": "#803F00",
        "paletteOrangeLight": "#FDF0E3",
        "paletteOrangeLightActive": "#F8D3AB",
        "paletteOrangeLightHover": "#FAE2C7",
        "paletteOrangeLightSecondary": "#FAE2C7",
        "paletteOrangeLightTertiary": "#F8D3AB",
        "paletteOrangeNormal": "#E98305",
        "paletteOrangeNormalActive": "#CD7304",
        "paletteOrangeNormalHover": "#DC7C05",
        "paletteOrangeNormalSecondary": "#DC7C05",
        "paletteOrangeNormalTertiary": "#CD7304",
        "paletteProductDark": "#007F6D",
        "paletteProductDarkActive": "#006657",
        "paletteProductDarkHover": "#007060",
        "paletteProductDarkSecondary": "#007060",
        "paletteProductDarkTertiary": "#006657",
        "paletteProductDarker": "#005C4E",
        "paletteProductLight": "#ECF8F7",
        "paletteProductLightActive": "#C0E8E4",
        "paletteProductLightHover": "#D6F0EE",
        "paletteProductLightSecondary": "#D6F0EE",
        "paletteProductLightTertiary": "#C0E8E4",
        "paletteProductNormal": "#00A991",
        "paletteProductNormalActive": "#008F7B",
        "paletteProductNormalHover": "#009882",
        "paletteProductNormalSecondary": "#009882",
        "paletteProductNormalTertiary": "#008F7B",
        "paletteRedDark": "#970C0C",
        "paletteRedDarkActive": "#6D0909",
        "paletteRedDarkHover": "#890B0B",
        "paletteRedDarkSecondary": "#890B0B",
        "paletteRedDarkTertiary": "#6D0909",
        "paletteRedDarker": "#760909",
        "paletteRedLight": "#FAEAEA",
        "paletteRedLightActive": "#EEB9B9",
        "paletteRedLightHover": "#F4D2D2",
        "paletteRedLightSecondary": "#F4D2D2",
        "paletteRedLightTertiary": "#EEB9B9",
        "paletteRedNormal": "#D21C1C",
        "paletteRedNormalActive": "#9D1515",
        "paletteRedNormalHover": "#B91919",
        "paletteRedNormalSecondary": "#B91919",
        "paletteRedNormalTertiary": "#9D1515",
        "paletteSocialFacebook": "#3B5998",
        "paletteSocialFacebookActive": "#354F88",
        "paletteSocialFacebookHover": "#385490",
        "paletteSocialFacebookSecondary": "#385490",
        "paletteSocialFacebookTertiary": "#354F88",
        "paletteWhite": "#FFFFFF",
        "paletteWhiteActive": "#E7ECF1",
        "paletteWhiteHover": "#F1F4F7",
        "paletteWhiteNormal": "#FFFFFF",
        "paletteWhiteNormalSecondary": "#F1F4F7",
        "paletteWhiteNormalTertiary": "#E7ECF1",
        "socialButtonAppleBackground": "#252A31",
        "socialButtonAppleBackgroundActive": "#0B0C0F",
        "socialButtonAppleBackgroundHover": "#181B20",
        "socialButtonAppleBorderColorFocus": "rgba(79, 94, 113, 0.5)",
        "socialButtonAppleForeground": "#FFFFFF",
        "socialButtonAppleForegroundActive": "#FFFFFF",
        "socialButtonAppleForegroundHover": "#FFFFFF",
        "socialButtonAppleIconForeground": "#FFFFFF",
        "socialButtonFacebookBackground": "#E8EDF1",
        "socialButtonFacebookBackgroundActive": "#CAD4DE",
        "socialButtonFacebookBackgroundHover": "#DCE3E9",
        "socialButtonFacebookBorderColorFocus": "rgba(79, 94, 113, 0.3)",
        "socialButtonFacebookForeground": "#252A31",
        "socialButtonFacebookForegroundActive": "#252A31",
        "socialButtonFacebookForegroundHover": "#252A31",
        "socialButtonFacebookIconForeground": "#3B5998",
        "socialButtonGoogleBackground": "#E8EDF1",
        "socialButtonGoogleBackgroundActive": "#CAD4DE",
        "socialButtonGoogleBackgroundHover": "#DCE3E9",
        "socialButtonGoogleBorderColorFocus": "rgba(79, 94, 113, 0.5)",
        "socialButtonGoogleForeground": "#252A31",
        "socialButtonGoogleForegroundActive": "#252A31",
        "socialButtonGoogleForegroundHover": "#252A31",
        "socialButtonGoogleIconForeground": "currentColor",
        "socialButtonTwitterBackground": "#E8EDF1",
        "socialButtonTwitterBackgroundActive": "#CAD4DE",
        "socialButtonTwitterBackgroundHover": "#DCE3E9",
        "socialButtonTwitterBorderColorFocus": "rgba(79, 94, 113, 0.5)",
        "socialButtonTwitterForeground": "#252A31",
        "socialButtonTwitterForegroundActive": "#252A31",
        "socialButtonTwitterForegroundHover": "#252A31",
        "socialButtonTwitterIconForeground": "#00ACEE",
        "spaceEightX": "32px",
        "spaceFourX": "16px",
        "spaceHalfX": "2px",
        "spaceLarge": "24px",
        "spaceMedium": "16px",
        "spaceOneX": "4px",
        "spaceSixX": "24px",
        "spaceSmall": "12px",
        "spaceTenX": "40px",
        "spaceThreeX": "12px",
        "spaceTwoX": "8px",
        "spaceXLarge": "32px",
        "spaceXSmall": "8px",
        "spaceXXLarge": "40px",
        "spaceXXSmall": "4px",
        "spaceXXXLarge": "52px",
        "spaceXXXSmall": "2px",
        "textCriticalForeground": "#D21C1C",
        "textDecorationTextLinkPrimary": "underline",
        "textDecorationTextLinkPrimaryHover": "none",
        "textDecorationTextLinkSecondary": "underline",
        "textDecorationTextLinkSecondaryHover": "none",
        "textInfoForeground": "#28A138",
        "textLinkFontWeight": "500",
        "textLinkForegroundHover": "#009882",
        "textLinkPrimaryForeground": "#007F6D",
        "textLinkSecondaryForeground": "#252A31",
        "textLinkTextDecoration": "underline",
        "textLinkTextDecorationHover": "none",
        "textPrimaryForeground": "#252A31",
        "textSecondaryForeground": "#4F5E71",
        "textSuccessForeground": "#28A138",
        "textWarningForeground": "#E98305",
        "textWhiteForeground": "#FFFFFF",
        "widthBadgeCircled": "24px",
        "widthBreakpointDesktop": 992,
        "widthBreakpointLargeDesktop": 1200,
        "widthBreakpointLargeMobile": 576,
        "widthBreakpointMediumMobile": 414,
        "widthBreakpointTablet": 768,
        "widthCheckbox": "20px",
        "widthCountryFlag": "24px",
        "widthIconLarge": "32px",
        "widthIconMedium": "24px",
        "widthIconSmall": "16px",
        "widthModalExtraLarge": "1280px",
        "widthModalLarge": "900px",
        "widthModalNormal": "740px",
        "widthModalSmall": "540px",
        "widthRadioButton": "20px",
        "widthStopoverArrow": "36px",
        "zIndexDefault": 1,
        "zIndexDrawer": 815,
        "zIndexModal": 825,
        "zIndexModalOverlay": 800,
        "zIndexOnTheTop": 900,
        "zIndexSticky": 100,
      }
    `);
  });
});
