// @flow

type Colors = {|
	product?: {|
		light?: string,
		lightHover?: string,
		lightActive?: string,
		normal?: string,
		normalHover?: string,
		normalActive?: string,
		dark?: string,
	|},
	white?: {|
		normal: string,
	|},
	cloud?: {|
		light?: string,
		lightHover?: string,
		lightActive?: string,
		normal?: string,
		normalHover?: string,
		normalActive?: string,
	|},
	ink?: {|
		lighter?: string,
		lighterHover?: string,
		lighterActive?: string,
		light?: string,
		lightHover?: string,
		lightActive?: string,
		normal?: string,
		normalHover?: string,
		normalActive?: string,
		dark?: string,
	|},
	orange?: {|
		light?: string,
		lightHover?: string,
		lightActive?: string,
		normal?: string,
		normalHover?: string,
		normalActive?: string,
		dark?: string,
	|},
	red?: {|
		light?: string,
		lightHover?: string,
		lightActive?: string,
		normal?: string,
		normalHover?: string,
		normalActive?: string,
		dark?: string,
	|},
	green: {|
		light?: string,
		lightHover?: string,
		lightActive?: string,
		normal?: string,
		normalHover?: string,
		normalActive?: string,
		dark?: string,
	|},
	blue?: {|
		light?: string,
		lightHover?: string,
		lightActive?: string,
		normal?: string,
		normalHover?: string,
		normalActive?: string,
		dark?: string,
	|},
	social?: {|
		facebook?: string,
		facebookHover?: string,
		facebookActive?: string,
	|}
|}

const COLORS = {
	product: {
		light: "#9ae5da",
		lightHover: "#7fded0",
		lightActive: "#64d7c6",
		normal: "#00a991",
		normalHover: "#009882",
		normalActive: "#008f7b",
		dark: "#005448"
	},
	white: {
		normal: "#fff",
	},
	cloud: {
		light: "#f5f7f9",
		lightHover: "#e5eaef",
		lightActive: "#d6dee6",
		normal: "#e8edf1",
		normalHover: "#d9e1e8",
		normalActive: "#cad5df"
	},
	ink: {
		lighter: "#bac7d5",
		lighterHover: "#a6b6c8",
		lighterActive: "#94a8be",
		light: "#7f91a8",
		lightHover: "#6d819c",
		lightActive: "#5f738c",
		normal: "#46515e",
		normalHover: "#3f4854",
		normalActive: "#38404b",
		dark: "#171b1e"
	},
	orange: {
		light: "#fcf1cd",
		lightHover: "#faeab7",
		lightActive: "#f9e4a1",
		normal: "#f9971e",
		normalHover: "#f48a06",
		normalActive: "#e68206",
		dark: "#a93610"
	},
	red: {
		light: "#fae8e8",
		lightHover: "#f5d4d4",
		lightActive: "#f1c0c0",
		normal: "#d21c1c",
		normalHover: "#bd1919",
		normalActive: "#b21717",
		dark: "#650808"
	},
	green: {
		light: "#e7f3e8",
		lightHover: "#d7ebd8",
		lightActive: "#c7e3c9",
		normal: "#46B655",
		normalHover: "#42ac50",
		normalActive: "#3fa34c",
		dark: "#065d12"
	},
	blue: {
		light: "#e0f6ff",
		lightHover: "#c8effe",
		lightActive: "#b0e8fe",
		normal: "#0176D2",
		normalHover: "#006abd",
		normalActive: "#0064b2",
		dark: "#07405c"
	},
	social: {
		facebook: "#3b5998",
		facebookHover: "#385490",
		facebookActive: "#354f88"
	}
};

function getTokens(palette?: Colors) {
	const _colors = Object.assign({}, COLORS, palette);
	return ({
		// category:Colors
		// description:Use these tokens for text or icon colors. Don't use these for borders and background colors.
		colorTextInfo: _colors.blue.normal,
		colorTextPrimary: _colors.ink.normal,
		colorTextSecondary: _colors.ink.light,
		colorTextAttention: _colors.ink.dark,
		colorTextError: _colors.red.normal,
		colorIconPrimary: _colors.ink.normal,
		colorIconSecondary: _colors.ink.light,
		colorIconAttention: _colors.ink.dark,
		colorIconTerciary: _colors.ink.lighter,
		colorHeading: _colors.ink.dark,
		colorHeadingInverted: _colors.white.normal,
		colorTextLinkPrimary: _colors.product.normal,
		colorTextLinkPrimaryHover: _colors.product.normal,
		colorTextLinkSecondary: _colors.ink.dark,
		colorTextLinkSecondaryHover: _colors.product.normal,
		colorAlertIconSuccess: _colors.green.normal,
		colorTextAlertSuccess: _colors.green.dark,
		colorAlertIconInfo: _colors.blue.normal,
		colorTextAlertInfo: _colors.blue.dark,
		colorAlertIconWarning: _colors.orange.normal,
		colorTextAlertWarning: _colors.orange.dark,
		colorAlertIconCritical: _colors.red.normal,
		colorTextAlertCritical: _colors.red.dark,
		colorTextButtonFilled: _colors.white.normal,
		colorTextButtonFilledHover: _colors.white.normal,
		colorTextButtonFilledActive: _colors.white.normal,
		colorTextButtonPrimary: _colors.white.normal,
		colorTextButtonPrimaryHover: _colors.white.normal,
		colorTextButtonPrimaryActive: _colors.white.normal,
		colorTextButtonSecondary: _colors.ink.normal,
		colorTextButtonSecondaryHover: _colors.ink.normalHover,
		colorTextButtonSecondaryActive: _colors.ink.normalActive,
		colorTextButtonInfo: _colors.white.normal,
		colorTextButtonInfoHover: _colors.white.normal,
		colorTextButtonInfoActive: _colors.white.normal,
		colorTextButtonSuccess: _colors.white.normal,
		colorTextButtonSuccessHover: _colors.white.normal,
		colorTextButtonSuccessActive: _colors.white.normal,
		colorTextButtonWarning: _colors.white.normal,
		colorTextButtonWarningHover: _colors.white.normal,
		colorTextButtonWarningActive: _colors.white.normal,
		colorTextButtonCritical: _colors.white.normal,
		colorTextButtonCriticalHover: _colors.white.normal,
		colorTextButtonCriticalActive: _colors.white.normal,
		colorTextButtonFacebook: _colors.white.normal,
		colorTextButtonFacebookHover: _colors.white.normal,
		colorTextButtonFacebookActive: _colors.white.normal,
		colorTextButtonGoogle: _colors.ink.normal,
		colorTextButtonGoogleHover: _colors.ink.normalHover,
		colorTextButtonGoogleActive: _colors.ink.normalActive,
		colorTextButtonPrimaryBordered: _colors.product.normal,
		colorTextButtonPrimaryBorderedHover: _colors.product.normalHover,
		colorTextButtonPrimaryBorderedActive: _colors.product.normalActive,
		colorTextButtonSecondaryBordered: _colors.ink.normal,
		colorTextButtonSecondaryBorderedHover: _colors.ink.normalHover,
		colorTextButtonSecondaryBorderedActive: _colors.ink.normalActive,
		colorTextButtonInfoBordered: _colors.blue.normal,
		colorTextButtonInfoBorderedHover: _colors.blue.normalHover,
		colorTextButtonInfoBorderedActive: _colors.blue.normalActive,
		colorTextButtonSuccessBordered: _colors.green.normal,
		colorTextButtonSuccessBorderedHover: _colors.green.normalHover,
		colorTextButtonSuccessBorderedActive: _colors.green.normalActive,
		colorTextButtonWarningBordered: _colors.orange.normal,
		colorTextButtonWarningBorderedHover: _colors.orange.normalHover,
		colorTextButtonWarningBorderedActive: _colors.orange.normalActive,
		colorTextButtonCriticalBordered: _colors.red.normal,
		colorTextButtonCriticalBorderedHover: _colors.red.normalHover,
		colorTextButtonCriticalBorderedActive: _colors.red.normalActive,
		colorTextButtonFacebookBordered: _colors.social.facebook,
		colorTextButtonFacebookBorderedHover: _colors.social.facebookHover,
		colorTextButtonFacebookBorderedActive: _colors.social.facebookActive,
		colorTextButtonGoogleBordered: _colors.ink.normal,
		colorTextButtonGoogleBorderedHover: _colors.ink.normalHover,
		colorTextButtonGoogleBorderedActive: _colors.ink.normalActive,
		colorTextButtonLinkPrimary: _colors.product.normal,
		colorTextButtonLinkPrimaryHover: _colors.product.normalHover,
		colorTextButtonLinkPrimaryActive: _colors.product.normalActive,
		colorTextButtonLinkSecondary: _colors.ink.normal,
		colorTextButtonLinkSecondaryHover: _colors.ink.normalHover,
		colorTextButtonLinkSecondaryActive: _colors.ink.normalActive,
		colorTextInput: _colors.ink.normal,
		colorTextInputDisabled: _colors.ink.lighter,
		colorIconInput: _colors.ink.lighter,
		colorPlaceholderInput: _colors.ink.lighter,
		colorLabelForm: _colors.ink.normal,
		colorLabelFormFilled: _colors.ink.light,
		colorIconCheckbox: _colors.product.normal,
		colorIconCheckboxDisabled: _colors.ink.lighter,
		colorIconRadioButton: _colors.product.normal,
		colorIconRadioButtonDisabled: _colors.ink.lighter,
		// category:Font family
		// description:
		fontFamily:
			'"Roboto", -apple-system, ".SFNSText-Regular", "San Francisco", "Segoe UI", "Helvetica Neue", "Lucida Grande", sans-serif',
		// category:Background colors
		// description:Use these tokens for background colors only. Do not use these for border colors or text _colors.
		backgroundBody: _colors.cloud.light,
		backgroundModal: _colors.white.normal,
		backgroundCard: _colors.white.normal,
		backgroundCarrierLogo: "transparent",
		backgroundButtonPrimary: _colors.product.normal,
		backgroundButtonPrimaryHover: _colors.product.normalHover,
		backgroundButtonPrimaryActive: _colors.product.normalActive,
		backgroundButtonSecondary: _colors.cloud.normal,
		backgroundButtonSecondaryHover: _colors.cloud.normalHover,
		backgroundButtonSecondaryActive: _colors.cloud.normalActive,
		backgroundButtonFacebook: _colors.social.facebook,
		backgroundButtonFacebookHover: _colors.social.facebookHover,
		backgroundButtonFacebookActive: _colors.social.facebookActive,
		backgroundButtonGoogle: _colors.cloud.light,
		backgroundButtonGoogleHover: _colors.cloud.lightHover,
		backgroundButtonGoogleActive: _colors.cloud.lightActive,
		backgroundButtonInfo: _colors.blue.normal,
		backgroundButtonInfoHover: _colors.blue.normalHover,
		backgroundButtonInfoActive: _colors.blue.normalActive,
		backgroundButtonSuccess: _colors.green.normal,
		backgroundButtonSuccessHover: _colors.green.normalHover,
		backgroundButtonSuccessActive: _colors.green.normalActive,
		backgroundButtonWarning: _colors.orange.normal,
		backgroundButtonWarningHover: _colors.orange.normalHover,
		backgroundButtonWarningActive: _colors.orange.normalActive,
		backgroundButtonCritical: _colors.red.normal,
		backgroundButtonCriticalHover: _colors.red.normalHover,
		backgroundButtonCriticalActive: _colors.red.normalActive,
		backgroundButtonBordered: "transparent",
		backgroundButtonBorderedHover: _colors.cloud.light,
		backgroundButtonBorderedActive: _colors.white.normal,
		backgroundButtonLinkPrimary: "transparent",
		backgroundButtonLinkPrimaryHover: _colors.cloud.lightHover,
		backgroundButtonLinkPrimaryActive: _colors.cloud.lightActive,
		backgroundButtonLinkSecondary: "transparent",
		backgroundButtonLinkSecondaryHover: _colors.cloud.lightHover,
		backgroundButtonLinkSecondaryActive: _colors.cloud.lightActive,
		backgroundInput: _colors.white.normal,
		backgroundInputDisabled: _colors.cloud.normal,
		backgroundAlertSuccess: _colors.green.light,
		backgroundAlertInfo: _colors.blue.light,
		backgroundAlertWarning: _colors.orange.light,
		backgroundAlertCritical: _colors.red.light,
		// category:Font size
		// description:Use these sizing tokens for font sizes.
		fontSizeHeadingDisplay: "40px",
		fontSizeHeadingTitle1: "28px",
		fontSizeHeadingTitle2: "22px",
		fontSizeHeadingTitle3: "16px",
		fontSizeTextNormal: "14px",
		fontSizeTextLarge: "16px",
		fontSizeTextSmall: "12px",
		fontSizeMessage: "14px",
		fontSizeButtonLarge: "16px",
		fontSizeButtonNormal: "14px",
		fontSizeButtonSmall: "12px",
		fontSizeInputNormal: "16px",
		fontSizeInputSmall: "14px",
		fontSizeLabelForm: "14px",
		fontSizeMessageForm: "12px",
		// category:Border radius
		// description:Use radius tokens to change the border-radius size (rounded corners).
		/** use only for square */
		borderRadiusCircle: "50%",
		/** use for all basic elements like buttons, inputs, content containers */
		borderRadiusNormal: "3px",
		/** use for big elements like modal and large buttons */
		borderRadiusLarge: "6px",
		/** use for smaller elements like tags */
		borderRadiusSmall: "2px",
		// category:Z Index
		// description:Use layers to show depth of page.
		zIndexDefault: "1",
		zIndexSticky: "100",
		zIndexModalOverlay: "800",
		zIndexModal: "825",
		zIndexOnTheTop: "900",
		// category:Size (width, height)
		// description:
		widthIconSmall: "16px",
		heightIconSmall: "16px",
		widthIconMedium: "24px",
		heightIconMedium: "24px",
		widthIconLarge: "32px",
		heightIconLarge: "32px",
		heightInputNormal: "44px",
		heightInputLarge: "52px",
		heightInputSmall: "32px",
		heightButtonNormal: "44px",
		heightButtonLarge: "52px",
		heightButtonSmall: "32px",
		heightRadioButton: "20px",
		widthRadioButton: "20px",
		heightCheckbox: "20px",
		widthCheckbox: "20px",
		heightCountryFlag: "20px",
		widthCountryFlag: "20px",
		// category:Border color
		// description:
		borderColorInput: _colors.ink.lighter,
		borderColorInputHover: _colors.ink.lighterHover,
		borderColorInputActive: _colors.ink.lighterActive,
		borderColorInputFocus: _colors.blue.normal,
		borderColorInputError: _colors.red.normal,
		borderColorInputErrorFocus: _colors.red.normal,
		borderColorTableCell: _colors.ink.lighter,
		borderColorCard: _colors.cloud.normal,
		borderColorModal: _colors.cloud.normal,
		borderColorButtonPrimaryBordered: _colors.product.normal,
		borderColorButtonPrimaryBorderedHover: _colors.product.normalHover,
		borderColorButtonPrimaryBorderedActive: _colors.product.normalActive,
		borderColorButtonSecondaryBordered: _colors.ink.normal,
		borderColorButtonSecondaryBorderedHover: _colors.ink.normalHover,
		borderColorButtonSecondaryBorderedActive: _colors.ink.normalActive,
		borderColorButtonFacebookBordered: _colors.social.facebook,
		borderColorButtonFacebookBorderedHover: _colors.social.facebookHover,
		borderColorButtonFacebookBorderedActive: _colors.social.facebookActive,
		borderColorButtonGoogleBordered: _colors.ink.normal,
		borderColorButtonGoogleBorderedHover: _colors.ink.normalHover,
		borderColorButtonGoogleBorderedActive: _colors.ink.normalActive,
		borderColorButtonInfoBordered: _colors.blue.normal,
		borderColorButtonInfoBorderedHover: _colors.blue.normalHover,
		borderColorButtonInfoBorderedActive: _colors.blue.normalActive,
		borderColorButtonSuccessBordered: _colors.green.normal,
		borderColorButtonSuccessBorderedHover: _colors.green.normalHover,
		borderColorButtonSuccessBorderedActive: _colors.green.normalActive,
		borderColorButtonWarningBordered: _colors.orange.normal,
		borderColorButtonWarningBorderedHover: _colors.orange.normalHover,
		borderColorButtonWarningBorderedActive: _colors.orange.normalActive,
		borderColorButtonCriticalBordered: _colors.red.normal,
		borderColorButtonCriticalBorderedHover: _colors.red.normalHover,
		borderColorButtonCriticalBorderedActive: _colors.red.normalActive,
		// category:Border style
		// description:
		borderStyleCard: "solid",
		borderWidthCard: "1px",
		borderStyleInput: "solid",
		borderWidthInput: "1px",
		// category:Opacity
		// description:
		opacityOverlay: "0.8",
		opacityButtonDisabled: "0.3",
		opacityRadioButtonDisabled: "0.5",
		opacityCheckboxDisabled: "0.5",
		// category:Font weight
		// description:Use this for setting basic font weights.
		fontWeightNormal: "400",
		fontWeightMedium: "500",
		fontWeightBold: "700",
		fontWeightLinks: "500",
		fontWeightHeadingDisplay: "700",
		fontWeightHeadingTitle1: "700",
		fontWeightHeadingTitle2: "500",
		fontWeightHeadingTitle3: "500",
		// category:Spacing
		// description:Use this for setting spacings for elements.
		paddingAlert: "16px",
		paddingAlertWithIcon: "12px",
		paddingButtonSmall: "12px",
		paddingButtonNormal: "16px",
		paddingButtonLarge: "28px",
		paddingInputSmall: "12px",
		paddingInputNormal: "16px",
		paddingButtonSmallWithIcon: "8px",
		paddingButtonNormalWithIcon: "8px",
		paddingButtonLargeWithIcon: "12px",
		marginButtonIconSmall: "8px",
		marginButtonIconNormal: "12px",
		marginButtonIconLarge: "16px",
		spaceXXSmall: "4px",
		spaceXSmall: "8px",
		spaceSmall: "12px",
		spaceMedium: "16px",
		spaceLarge: "24px",
		spaceXLarge: "32px",
		spaceXXLarge: "40px",
		spaceXXXLarge: "52px",
		// category:Duration
		// description:Use this for setting the speed of animation or transition.
		durationFast: "0.2s",
		durationNormal: "0.3s",
		durationSlow: "0.4s",
		// category:Modifier
		// description:Use this for values for transform property, etc.
		modifierScaleButtonActive: 0.9,
		// category:Line height
		// description:
		lineHeightText: "1.4",
		lineHeightHeading: "1.2",
		// category:Text decoration
		// description:
		textDecorationTextLinkPrimary: "none",
		textDecorationTextLinkPrimaryHover: "underline",
		textDecorationTextLinkSecondary: "underline",
		textDecorationTextLinkSecondaryHover: "underline",
		// category:Box shadow
		// description:
		boxShadowInputFocus: "0px 0px 3px 1px rgba(1,118,210,0.3)",
		boxShadowInputErrorFocus: "0px 0px 3px 1px rgba(210,28,28,0.3)",
		// category:Color palette
		// description: Use these tokens as a fallback when you need specific color. It's always preferred to use less abstract design tokens. Don't use Hover and Active shades as base _colors.
		paletteProductLight: _colors.product.light,
		paletteProductLightHover: _colors.product.lightHover,
		paletteProductLightActive: _colors.product.lightActive,
		paletteProductNormal: _colors.product.normal,
		paletteProductNormalHover: _colors.product.normalHover,
		paletteProductNormalActive: _colors.product.normalActive,
		paletteProductDark: _colors.product.dark,
		paletteWhite: _colors.white.normal,
		paletteWhiteHover: _colors.cloud.light,
		paletteWhiteActive: _colors.cloud.lightHover,
		paletteCloudLight: _colors.cloud.light,
		paletteCloudLightHover: _colors.cloud.lightHover,
		paletteCloudLightActive: _colors.cloud.lightActive,
		paletteCloudNormal: _colors.cloud.normal,
		paletteCloudNormalHover: _colors.cloud.normalHover,
		paletteCloudNormalActive: _colors.cloud.normalActive,
		paletteInkLighter: _colors.ink.lighter,
		paletteInkLighterHover: _colors.ink.lighterHover,
		paletteInkLighterActive: _colors.ink.lighterActive,
		paletteInkLight: _colors.ink.light,
		paletteInkLightHover: _colors.ink.lightHover,
		paletteInkLightActive: _colors.ink.lightActive,
		paletteInkNormal: _colors.ink.normal,
		paletteInkNormalHover: _colors.ink.normalHover,
		paletteInkNormalActive: _colors.ink.normalActive,
		paletteInkDark: _colors.ink.dark,
		paletteOrangeLight: _colors.orange.light,
		paletteOrangeLightHover: _colors.orange.lightHover,
		paletteOrangeLightActive: _colors.orange.lightActive,
		paletteOrangeNormal: _colors.orange.normal,
		paletteOrangeNormalHover: _colors.orange.normalHover,
		paletteOrangeNormalActive: _colors.orange.normalActive,
		paletteOrangeDark: _colors.orange.dark,
		paletteRedLight: _colors.red.light,
		paletteRedLightHover: _colors.red.lightHover,
		paletteRedLightActive: _colors.red.lightActive,
		paletteRedNormal: _colors.red.normal,
		paletteRedNormalHover: _colors.red.normalHover,
		paletteRedNormalActive: _colors.red.normalActive,
		paletteRedDark: _colors.red.dark,
		paletteGreenLight: _colors.green.light,
		paletteGreenLightHover: _colors.green.lightHover,
		paletteGreenLightActive: _colors.green.lightActive,
		paletteGreenNormal: _colors.green.normal,
		paletteGreenNormalHover: _colors.green.normalHover,
		paletteGreenNormalActive: _colors.green.normalActive,
		paletteGreenDark: _colors.green.dark,
		paletteBlueLight: _colors.blue.light,
		paletteBlueLightHover: _colors.blue.lightHover,
		paletteBlueLightActive: _colors.blue.lightActive,
		paletteBlueNormal: _colors.blue.normal,
		paletteBlueNormalHover: _colors.blue.normalHover,
		paletteBlueNormalActive: _colors.blue.normalActive,
		paletteBlueDark: _colors.blue.dark,
		paletteSocialFacebook: _colors.social.facebook,
		paletteSocialFacebookHover: _colors.social.facebookHover,
		paletteSocialFacebookActive: _colors.social.facebookActive,
	});
}

const defaultTokens = getTokens(COLORS);

module.exports = {
	defaultTokens,
	getTokens
};
