"use client";

import * as React from "react";
import cx from "clsx";

import { QUERIES } from "../utils/mediaQuery";
import type { Props } from "./types";
import getTailwindClasses from "./helpers";

const Box = ({
  as: Component = "div",
  id,
  mediumMobile,
  largeMobile,
  tablet,
  desktop,
  largeDesktop,
  children,
  dataTest,
  className,
  display,
  wrap,
  direction,
  position,
  align,
  justify,
  textAlign,
  elevation,
  borderRadius,
  overflow,
  shrink,
  grow,
  zIndex,
  width,
  minWidth,
  maxWidth,
  height,
  maxHeight,
  top,
  right,
  bottom,
  left,
  color,
  background,
  padding,
  margin,
  ariaLabel,
  ref,
}: Props) => {
  const twProps = {
    display,
    wrap,
    direction,
    position,
    align,
    justify,
    textAlign,
    elevation,
    borderRadius,
    overflow,
    color,
    background,
    padding,
    margin,
  };

  const viewportClasses = React.useMemo(() => {
    const viewportSpecs = {
      mediumMobile,
      largeMobile,
      tablet,
      desktop,
      largeDesktop,
    };

    return Object.values(QUERIES).map(viewport => {
      const viewportProps = viewportSpecs[viewport];

      if (viewportProps == null) return null;

      return getTailwindClasses(viewportProps, viewport);
    });
  }, [mediumMobile, largeMobile, tablet, desktop, largeDesktop]);

  const vars = {
    "--box-shrink": shrink,
    "--ld-box-shrink": largeDesktop?.shrink,
    "--de-box-shrink": desktop?.shrink,
    "--tb-box-shrink": tablet?.shrink,
    "--lm-box-shrink": largeMobile?.shrink,
    "--mm-box-shrink": mediumMobile?.shrink,
    "--box-grow": grow,
    "--ld-box-grow": largeDesktop?.grow,
    "--de-box-grow": desktop?.grow,
    "--tb-box-grow": tablet?.grow,
    "--lm-box-grow": largeMobile?.grow,
    "--mm-box-grow": mediumMobile?.grow,
    "--box-z-index": zIndex,
    "--ld-box-z-index": largeDesktop?.zIndex,
    "--de-box-z-index": desktop?.zIndex,
    "--tb-box-z-index": tablet?.zIndex,
    "--lm-box-z-index": largeMobile?.zIndex,
    "--mm-box-z-index": mediumMobile?.zIndex,
    "--box-width": width,
    "--ld-box-width": largeDesktop?.width,
    "--de-box-width": desktop?.width,
    "--tb-box-width": tablet?.width,
    "--lm-box-width": largeMobile?.width,
    "--mm-box-width": mediumMobile?.width,
    "--box-min-width": minWidth,
    "--ld-box-min-width": largeDesktop?.minWidth,
    "--de-box-min-width": desktop?.minWidth,
    "--tb-box-min-width": tablet?.minWidth,
    "--lm-box-min-width": largeMobile?.minWidth,
    "--mm-box-min-width": mediumMobile?.minWidth,
    "--box-max-width": maxWidth,
    "--ld-box-max-width": largeDesktop?.maxWidth,
    "--de-box-max-width": desktop?.maxWidth,
    "--tb-box-max-width": tablet?.maxWidth,
    "--lm-box-max-width": largeMobile?.maxWidth,
    "--mm-box-max-width": mediumMobile?.maxWidth,
    "--box-height": height,
    "--ld-box-height": largeDesktop?.height,
    "--de-box-height": desktop?.height,
    "--tb-box-height": tablet?.height,
    "--lm-box-height": largeMobile?.height,
    "--mm-box-height": mediumMobile?.height,
    "--box-max-height": maxHeight,
    "--ld-box-max-height": largeDesktop?.maxHeight,
    "--de-box-max-height": desktop?.maxHeight,
    "--tb-box-max-height": tablet?.maxHeight,
    "--lm-box-max-height": largeMobile?.maxHeight,
    "--mm-box-max-height": mediumMobile?.maxHeight,
    "--box-top": top,
    "--ld-box-top": largeDesktop?.top,
    "--de-box-top": desktop?.top,
    "--tb-box-top": tablet?.top,
    "--lm-box-top": largeMobile?.top,
    "--mm-box-top": mediumMobile?.top,
    "--box-right": right,
    "--ld-box-right": largeDesktop?.right,
    "--de-box-right": desktop?.right,
    "--tb-box-right": tablet?.right,
    "--lm-box-right": largeMobile?.right,
    "--mm-box-right": mediumMobile?.right,
    "--box-bottom": bottom,
    "--ld-box-bottom": largeDesktop?.bottom,
    "--de-box-bottom": desktop?.bottom,
    "--tb-box-bottom": tablet?.bottom,
    "--lm-box-bottom": largeMobile?.bottom,
    "--mm-box-bottom": mediumMobile?.bottom,
    "--box-left": left,
    "--ld-box-left": largeDesktop?.left,
    "--de-box-left": desktop?.left,
    "--tb-box-left": tablet?.left,
    "--lm-box-left": largeMobile?.left,
    "--mm-box-left": mediumMobile?.left,
  };

  const varClasses = [
    vars["--box-shrink"] != null && "shrink-(--box-shrink)",
    vars["--ld-box-shrink"] != null && "ld:shrink-(--ld-box-shrink)",
    vars["--de-box-shrink"] != null && "de:shrink-(--de-box-shrink)",
    vars["--tb-box-shrink"] != null && "tb:shrink-(--tb-box-shrink)",
    vars["--lm-box-shrink"] != null && "lm:shrink-(--lm-box-shrink)",
    vars["--mm-box-shrink"] != null && "mm:shrink-(--mm-box-shrink)",
    vars["--box-grow"] != null && "grow-(--box-grow)",
    vars["--ld-box-grow"] != null && "ld:grow-(--ld-box-grow)",
    vars["--de-box-grow"] != null && "de:grow-(--de-box-grow)",
    vars["--tb-box-grow"] != null && "tb:grow-(--tb-box-grow)",
    vars["--lm-box-grow"] != null && "lm:grow-(--lm-box-grow)",
    vars["--mm-box-grow"] != null && "mm:grow-(--mm-box-grow)",
    vars["--box-z-index"] != null && "z-(--box-z-index)",
    vars["--ld-box-z-index"] != null && "ld:z-(--ld-box-z-index)",
    vars["--de-box-z-index"] != null && "de:z-(--de-box-z-index)",
    vars["--tb-box-z-index"] != null && "tb:z-(--tb-box-z-index)",
    vars["--lm-box-z-index"] != null && "lm:z-(--lm-box-z-index)",
    vars["--mm-box-z-index"] != null && "mm:z-(--mm-box-z-index)",
    vars["--box-width"] != null && "w-(--box-width)",
    vars["--ld-box-width"] != null && "ld:w-(--ld-box-width)",
    vars["--de-box-width"] != null && "de:w-(--de-box-width)",
    vars["--tb-box-width"] != null && "tb:w-(--tb-box-width)",
    vars["--lm-box-width"] != null && "lm:w-(--lm-box-width)",
    vars["--mm-box-width"] != null && "mm:w-(--mm-box-width)",
    vars["--box-min-width"] != null && "min-w-(--box-min-width)",
    vars["--ld-box-min-width"] != null && "ld:min-w-(--ld-box-min-width)",
    vars["--de-box-min-width"] != null && "de:min-w-(--de-box-min-width)",
    vars["--tb-box-min-width"] != null && "tb:min-w-(--tb-box-min-width)",
    vars["--lm-box-min-width"] != null && "lm:min-w-(--lm-box-min-width)",
    vars["--mm-box-min-width"] != null && "mm:min-w-(--mm-box-min-width)",
    vars["--box-max-width"] != null && "max-w-(--box-max-width)",
    vars["--ld-box-max-width"] != null && "ld:max-w-(--ld-box-max-width)",
    vars["--de-box-max-width"] != null && "de:max-w-(--de-box-max-width)",
    vars["--tb-box-max-width"] != null && "tb:max-w-(--tb-box-max-width)",
    vars["--lm-box-max-width"] != null && "lm:max-w-(--lm-box-max-width)",
    vars["--mm-box-max-width"] != null && "mm:max-w-(--mm-box-max-width)",
    vars["--box-height"] != null && "h-(--box-height)",
    vars["--ld-box-height"] != null && "ld:h-(--ld-box-height)",
    vars["--de-box-height"] != null && "de:h-(--de-box-height)",
    vars["--tb-box-height"] != null && "tb:h-(--tb-box-height)",
    vars["--lm-box-height"] != null && "lm:h-(--lm-box-height)",
    vars["--mm-box-height"] != null && "mm:h-(--mm-box-height)",
    vars["--box-max-height"] != null && "max-h-(--box-max-height)",
    vars["--ld-box-max-height"] != null && "ld:max-h-(--ld-box-max-height)",
    vars["--de-box-max-height"] != null && "de:max-h-(--de-box-max-height)",
    vars["--tb-box-max-height"] != null && "tb:max-h-(--tb-box-max-height)",
    vars["--lm-box-max-height"] != null && "lm:max-h-(--lm-box-max-height)",
    vars["--mm-box-max-height"] != null && "mm:max-h-(--mm-box-max-height)",
    vars["--box-top"] != null && "top-(--box-top)",
    vars["--ld-box-top"] != null && "ld:top-(--ld-box-top)",
    vars["--de-box-top"] != null && "de:top-(--de-box-top)",
    vars["--tb-box-top"] != null && "tb:top-(--tb-box-top)",
    vars["--lm-box-top"] != null && "lm:top-(--lm-box-top)",
    vars["--mm-box-top"] != null && "mm:top-(--mm-box-top)",
    vars["--box-right"] != null && "right-(--box-right)",
    vars["--ld-box-right"] != null && "ld:right-(--ld-box-right)",
    vars["--de-box-right"] != null && "de:right-(--de-box-right)",
    vars["--tb-box-right"] != null && "tb:right-(--tb-box-right)",
    vars["--lm-box-right"] != null && "lm:right-(--lm-box-right)",
    vars["--mm-box-right"] != null && "mm:right-(--mm-box-right)",
    vars["--box-bottom"] != null && "bottom-(--box-bottom)",
    vars["--ld-box-bottom"] != null && "ld:bottom-(--ld-box-bottom)",
    vars["--de-box-bottom"] != null && "de:bottom-(--de-box-bottom)",
    vars["--tb-box-bottom"] != null && "tb:bottom-(--tb-box-bottom)",
    vars["--lm-box-bottom"] != null && "lm:bottom-(--lm-box-bottom)",
    vars["--mm-box-bottom"] != null && "mm:bottom-(--mm-box-bottom)",
    vars["--box-left"] != null && "left-(--box-left)",
    vars["--ld-box-left"] != null && "ld:left-(--ld-box-left)",
    vars["--de-box-left"] != null && "de:left-(--de-box-left)",
    vars["--tb-box-left"] != null && "tb:left-(--tb-box-left)",
    vars["--lm-box-left"] != null && "lm:left-(--lm-box-left)",
    vars["--mm-box-left"] != null && "mm:left-(--mm-box-left)",
  ];

  return (
    // @ts-expect-error Allow any component
    <Component
      className={cx(
        className,
        "orbit-box font-base box-border",
        ...getTailwindClasses(twProps),
        ...viewportClasses,
        ...varClasses,
      )}
      ref={ref}
      id={id}
      data-test={dataTest}
      style={vars}
      aria-label={ariaLabel}
    >
      {children}
    </Component>
  );
};

export default Box;
