// flow-typed signature: 356c73dcd2a7928f862dd1b0f40aa7bd
// flow-typed version: <<STUB>>/@storybook/addon-actions_v^6.0.28/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-actions'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-actions' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-actions/dist/components/ActionLogger' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/components/ActionLogger/style' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/containers/ActionLogger' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/ActionDisplay' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/ActionOptions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/ActionsFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/ActionsMap' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/DecoratorFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models/HandlerFunction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/models' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preset/addArgs' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/action' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/actions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/configureActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/decorateAction' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/preview/withActions' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-actions/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-actions/dist/components/ActionLogger/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/components/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/components/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/components/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/components/ActionLogger/style.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/components/ActionLogger/style'>;
}
declare module '@storybook/addon-actions/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/constants'>;
}
declare module '@storybook/addon-actions/dist/containers/ActionLogger/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/containers/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/containers/ActionLogger/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/containers/ActionLogger'>;
}
declare module '@storybook/addon-actions/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist'>;
}
declare module '@storybook/addon-actions/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist'>;
}
declare module '@storybook/addon-actions/dist/models/ActionDisplay.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/ActionDisplay'>;
}
declare module '@storybook/addon-actions/dist/models/ActionOptions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/ActionOptions'>;
}
declare module '@storybook/addon-actions/dist/models/ActionsFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/ActionsFunction'>;
}
declare module '@storybook/addon-actions/dist/models/ActionsMap.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/ActionsMap'>;
}
declare module '@storybook/addon-actions/dist/models/DecoratorFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/DecoratorFunction'>;
}
declare module '@storybook/addon-actions/dist/models/HandlerFunction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models/HandlerFunction'>;
}
declare module '@storybook/addon-actions/dist/models/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models'>;
}
declare module '@storybook/addon-actions/dist/models/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/models'>;
}
declare module '@storybook/addon-actions/dist/preset/addArgs.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preset/addArgs'>;
}
declare module '@storybook/addon-actions/dist/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preset/addDecorator'>;
}
declare module '@storybook/addon-actions/dist/preset/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preset'>;
}
declare module '@storybook/addon-actions/dist/preset/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preset'>;
}
declare module '@storybook/addon-actions/dist/preview/action.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/action'>;
}
declare module '@storybook/addon-actions/dist/preview/actions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/actions'>;
}
declare module '@storybook/addon-actions/dist/preview/configureActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/configureActions'>;
}
declare module '@storybook/addon-actions/dist/preview/decorateAction.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/decorateAction'>;
}
declare module '@storybook/addon-actions/dist/preview/index' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview'>;
}
declare module '@storybook/addon-actions/dist/preview/index.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview'>;
}
declare module '@storybook/addon-actions/dist/preview/withActions.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/preview/withActions'>;
}
declare module '@storybook/addon-actions/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/register'>;
}
declare module '@storybook/addon-actions/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/dist/typings.d'>;
}
declare module '@storybook/addon-actions/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/preset'>;
}
declare module '@storybook/addon-actions/register.js' {
  declare module.exports: $Exports<'@storybook/addon-actions/register'>;
}
