// flow-typed signature: 58fa3a9c415bf894453ba8ffcfa23fb2
// flow-typed version: <<STUB>>/@storybook/addon-info_v^6.0.0-alpha.2/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-info'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-info' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-info/dist/components/makeTableComponent' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown/code' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown/htags' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown/pre/copy' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown/pre/copyButton' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown/pre/pre' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/markdown/text' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/Props' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropTable' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropTable/components/Table' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropTable/components/Tbody' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropTable/components/Td' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropTable/components/Th' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropTable/components/Thead' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropTable/components/Tr' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropTable' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/PropVal' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/Story' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/ArrayOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/Enum' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/InstanceOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/Literal' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/ObjectOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/OneOf' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/OneOfType' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/PrettyPropType' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/PropertyLabel' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/proptypes' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/Shape' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/components/types/Signature' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-info/dist/react-utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-info/dist/components/makeTableComponent.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/makeTableComponent'>;
}
declare module '@storybook/addon-info/dist/components/markdown/code.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown/code'>;
}
declare module '@storybook/addon-info/dist/components/markdown/htags.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown/htags'>;
}
declare module '@storybook/addon-info/dist/components/markdown/index' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown'>;
}
declare module '@storybook/addon-info/dist/components/markdown/index.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown'>;
}
declare module '@storybook/addon-info/dist/components/markdown/pre/copy.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown/pre/copy'>;
}
declare module '@storybook/addon-info/dist/components/markdown/pre/copyButton.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown/pre/copyButton'>;
}
declare module '@storybook/addon-info/dist/components/markdown/pre/pre.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown/pre/pre'>;
}
declare module '@storybook/addon-info/dist/components/markdown/text.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/markdown/text'>;
}
declare module '@storybook/addon-info/dist/components/Props.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/Props'>;
}
declare module '@storybook/addon-info/dist/components/PropTable.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropTable'>;
}
declare module '@storybook/addon-info/dist/components/PropTable/components/Table.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropTable/components/Table'>;
}
declare module '@storybook/addon-info/dist/components/PropTable/components/Tbody.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropTable/components/Tbody'>;
}
declare module '@storybook/addon-info/dist/components/PropTable/components/Td.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropTable/components/Td'>;
}
declare module '@storybook/addon-info/dist/components/PropTable/components/Th.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropTable/components/Th'>;
}
declare module '@storybook/addon-info/dist/components/PropTable/components/Thead.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropTable/components/Thead'>;
}
declare module '@storybook/addon-info/dist/components/PropTable/components/Tr.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropTable/components/Tr'>;
}
declare module '@storybook/addon-info/dist/components/PropTable/index' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropTable'>;
}
declare module '@storybook/addon-info/dist/components/PropTable/index.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropTable'>;
}
declare module '@storybook/addon-info/dist/components/PropVal.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/PropVal'>;
}
declare module '@storybook/addon-info/dist/components/Story.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/Story'>;
}
declare module '@storybook/addon-info/dist/components/types/ArrayOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/ArrayOf'>;
}
declare module '@storybook/addon-info/dist/components/types/Enum.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/Enum'>;
}
declare module '@storybook/addon-info/dist/components/types/InstanceOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/InstanceOf'>;
}
declare module '@storybook/addon-info/dist/components/types/Literal.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/Literal'>;
}
declare module '@storybook/addon-info/dist/components/types/ObjectOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/ObjectOf'>;
}
declare module '@storybook/addon-info/dist/components/types/OneOf.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/OneOf'>;
}
declare module '@storybook/addon-info/dist/components/types/OneOfType.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/OneOfType'>;
}
declare module '@storybook/addon-info/dist/components/types/PrettyPropType.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/PrettyPropType'>;
}
declare module '@storybook/addon-info/dist/components/types/PropertyLabel.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/PropertyLabel'>;
}
declare module '@storybook/addon-info/dist/components/types/proptypes.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/proptypes'>;
}
declare module '@storybook/addon-info/dist/components/types/Shape.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/Shape'>;
}
declare module '@storybook/addon-info/dist/components/types/Signature.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/components/types/Signature'>;
}
declare module '@storybook/addon-info/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-info/dist'>;
}
declare module '@storybook/addon-info/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist'>;
}
declare module '@storybook/addon-info/dist/react-utils.js' {
  declare module.exports: $Exports<'@storybook/addon-info/dist/react-utils'>;
}
