// flow-typed signature: 619063b87c064cd1cec76721e1978c44
// flow-typed version: <<STUB>>/@storybook/addons_v^6.0.28/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addons/dist/hooks' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/make-decorator' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/public_api' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/storybook-channel-mock' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/types' {
  declare module.exports: any;
}

declare module '@storybook/addons/dist/typings.d' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addons/dist/hooks.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/hooks'>;
}
declare module '@storybook/addons/dist/index' {
  declare module.exports: $Exports<'@storybook/addons/dist'>;
}
declare module '@storybook/addons/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addons/dist'>;
}
declare module '@storybook/addons/dist/make-decorator.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/make-decorator'>;
}
declare module '@storybook/addons/dist/public_api.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/public_api'>;
}
declare module '@storybook/addons/dist/storybook-channel-mock.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/storybook-channel-mock'>;
}
declare module '@storybook/addons/dist/types.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/types'>;
}
declare module '@storybook/addons/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addons/dist/typings.d'>;
}
