// flow-typed signature: 6b0ce41628e5f33be0b38c8c2d0b5776
// flow-typed version: <<STUB>>/@storybook/addon-knobs_v^6.1.11/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-knobs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-knobs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-knobs/dist/__types__/knob-test-cases' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/Panel' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/PropForm' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Array' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Boolean' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Button' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Checkboxes' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Color' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Date' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Files' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Number' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Object' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Options' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Radio' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Select' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/Text' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/components/types/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/converters' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/KnobManager' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/KnobStore' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/registerKnobs' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/shared' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/title' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/type-defs' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-knobs/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-knobs/dist/__types__/knob-test-cases.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/__types__/knob-test-cases'>;
}
declare module '@storybook/addon-knobs/dist/components/Panel.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/Panel'>;
}
declare module '@storybook/addon-knobs/dist/components/PropForm.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/PropForm'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Array.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Array'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Boolean.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Boolean'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Button.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Button'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Checkboxes.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Checkboxes'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Color.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Color'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Date.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Date'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Files.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Files'>;
}
declare module '@storybook/addon-knobs/dist/components/types/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types'>;
}
declare module '@storybook/addon-knobs/dist/components/types/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Number.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Number'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Object.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Object'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Options.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Options'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Radio.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Radio'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Select.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Select'>;
}
declare module '@storybook/addon-knobs/dist/components/types/Text.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/Text'>;
}
declare module '@storybook/addon-knobs/dist/components/types/types.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/components/types/types'>;
}
declare module '@storybook/addon-knobs/dist/converters.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/converters'>;
}
declare module '@storybook/addon-knobs/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist'>;
}
declare module '@storybook/addon-knobs/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist'>;
}
declare module '@storybook/addon-knobs/dist/KnobManager.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/KnobManager'>;
}
declare module '@storybook/addon-knobs/dist/KnobStore.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/KnobStore'>;
}
declare module '@storybook/addon-knobs/dist/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/preset/addDecorator'>;
}
declare module '@storybook/addon-knobs/dist/preset/index' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/preset'>;
}
declare module '@storybook/addon-knobs/dist/preset/index.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/preset'>;
}
declare module '@storybook/addon-knobs/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/register'>;
}
declare module '@storybook/addon-knobs/dist/registerKnobs.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/registerKnobs'>;
}
declare module '@storybook/addon-knobs/dist/shared.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/shared'>;
}
declare module '@storybook/addon-knobs/dist/title.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/title'>;
}
declare module '@storybook/addon-knobs/dist/type-defs.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/type-defs'>;
}
declare module '@storybook/addon-knobs/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/dist/typings.d'>;
}
declare module '@storybook/addon-knobs/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/preset'>;
}
declare module '@storybook/addon-knobs/register.js' {
  declare module.exports: $Exports<'@storybook/addon-knobs/register'>;
}
