// flow-typed signature: a15a5f2d185c5cc24f796ba8658e63c3
// flow-typed version: <<STUB>>/@storybook/addon-backgrounds_v^6.1.10/flow_v0.147.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/addon-backgrounds'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/addon-backgrounds' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/addon-backgrounds/dist/components/ColorIcon' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/constants' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/containers/BackgroundSelector' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/containers/GridSelector' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/decorators' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/decorators/withBackground' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/decorators/withGrid' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/helpers' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/preset/addDecorator' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/preset/addParameter' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/register' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/types' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/preset' {
  declare module.exports: any;
}

declare module '@storybook/addon-backgrounds/register' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/addon-backgrounds/dist/components/ColorIcon.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/components/ColorIcon'>;
}
declare module '@storybook/addon-backgrounds/dist/constants.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/constants'>;
}
declare module '@storybook/addon-backgrounds/dist/containers/BackgroundSelector.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/containers/BackgroundSelector'>;
}
declare module '@storybook/addon-backgrounds/dist/containers/GridSelector.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/containers/GridSelector'>;
}
declare module '@storybook/addon-backgrounds/dist/decorators/index' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/decorators'>;
}
declare module '@storybook/addon-backgrounds/dist/decorators/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/decorators'>;
}
declare module '@storybook/addon-backgrounds/dist/decorators/withBackground.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/decorators/withBackground'>;
}
declare module '@storybook/addon-backgrounds/dist/decorators/withGrid.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/decorators/withGrid'>;
}
declare module '@storybook/addon-backgrounds/dist/helpers/index' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/helpers'>;
}
declare module '@storybook/addon-backgrounds/dist/helpers/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/helpers'>;
}
declare module '@storybook/addon-backgrounds/dist/index' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist'>;
}
declare module '@storybook/addon-backgrounds/dist/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist'>;
}
declare module '@storybook/addon-backgrounds/dist/preset/addDecorator.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/preset/addDecorator'>;
}
declare module '@storybook/addon-backgrounds/dist/preset/addParameter.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/preset/addParameter'>;
}
declare module '@storybook/addon-backgrounds/dist/preset/index' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/preset'>;
}
declare module '@storybook/addon-backgrounds/dist/preset/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/preset'>;
}
declare module '@storybook/addon-backgrounds/dist/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/register'>;
}
declare module '@storybook/addon-backgrounds/dist/types/index' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/types'>;
}
declare module '@storybook/addon-backgrounds/dist/types/index.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/types'>;
}
declare module '@storybook/addon-backgrounds/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/dist/typings.d'>;
}
declare module '@storybook/addon-backgrounds/preset.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/preset'>;
}
declare module '@storybook/addon-backgrounds/register.js' {
  declare module.exports: $Exports<'@storybook/addon-backgrounds/register'>;
}
