// flow-typed signature: da36669b8c19af1b4ce45d337c630cc0
// flow-typed version: <<STUB>>/@storybook/react_v^6.1.20/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/react/bin/build' {
  declare module.exports: any;
}

declare module '@storybook/react/bin' {
  declare module.exports: any;
}

declare module '@storybook/react/demo' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client/preview/globals' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client/preview' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client/preview/render' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client/preview/types-6-0' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/client/preview/types' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/demo/Button' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/demo/Welcome' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/build' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/cra-config' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/framework-preset-cra' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/framework-preset-react-docgen' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/framework-preset-react' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/options' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/server/types' {
  declare module.exports: any;
}

declare module '@storybook/react/dist/typings.d' {
  declare module.exports: any;
}

declare module '@storybook/react/standalone' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/react/bin/build.js' {
  declare module.exports: $Exports<'@storybook/react/bin/build'>;
}
declare module '@storybook/react/bin/index' {
  declare module.exports: $Exports<'@storybook/react/bin'>;
}
declare module '@storybook/react/bin/index.js' {
  declare module.exports: $Exports<'@storybook/react/bin'>;
}
declare module '@storybook/react/demo.js' {
  declare module.exports: $Exports<'@storybook/react/demo'>;
}
declare module '@storybook/react/dist/client/index' {
  declare module.exports: $Exports<'@storybook/react/dist/client'>;
}
declare module '@storybook/react/dist/client/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client'>;
}
declare module '@storybook/react/dist/client/preview/globals.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client/preview/globals'>;
}
declare module '@storybook/react/dist/client/preview/index' {
  declare module.exports: $Exports<'@storybook/react/dist/client/preview'>;
}
declare module '@storybook/react/dist/client/preview/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client/preview'>;
}
declare module '@storybook/react/dist/client/preview/render.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client/preview/render'>;
}
declare module '@storybook/react/dist/client/preview/types-6-0.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client/preview/types-6-0'>;
}
declare module '@storybook/react/dist/client/preview/types.js' {
  declare module.exports: $Exports<'@storybook/react/dist/client/preview/types'>;
}
declare module '@storybook/react/dist/demo/Button.js' {
  declare module.exports: $Exports<'@storybook/react/dist/demo/Button'>;
}
declare module '@storybook/react/dist/demo/Welcome.js' {
  declare module.exports: $Exports<'@storybook/react/dist/demo/Welcome'>;
}
declare module '@storybook/react/dist/server/build.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/build'>;
}
declare module '@storybook/react/dist/server/cra-config.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/cra-config'>;
}
declare module '@storybook/react/dist/server/framework-preset-cra.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/framework-preset-cra'>;
}
declare module '@storybook/react/dist/server/framework-preset-react-docgen.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/framework-preset-react-docgen'>;
}
declare module '@storybook/react/dist/server/framework-preset-react.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/framework-preset-react'>;
}
declare module '@storybook/react/dist/server/index' {
  declare module.exports: $Exports<'@storybook/react/dist/server'>;
}
declare module '@storybook/react/dist/server/index.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server'>;
}
declare module '@storybook/react/dist/server/options.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/options'>;
}
declare module '@storybook/react/dist/server/types.js' {
  declare module.exports: $Exports<'@storybook/react/dist/server/types'>;
}
declare module '@storybook/react/dist/typings.d.js' {
  declare module.exports: $Exports<'@storybook/react/dist/typings.d'>;
}
declare module '@storybook/react/standalone.js' {
  declare module.exports: $Exports<'@storybook/react/standalone'>;
}
