// flow-typed signature: 7c5e182f2dc1af91fe4dc1ad7a930f97
// flow-typed version: <<STUB>>/@storybook/storybook-deployer_v^2.8.7/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/storybook-deployer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/storybook-deployer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@storybook/storybook-deployer/src/build-monorepo-index' {
  declare module.exports: any;
}

declare module '@storybook/storybook-deployer/src/build' {
  declare module.exports: any;
}

declare module '@storybook/storybook-deployer/src/parse-args' {
  declare module.exports: any;
}

declare module '@storybook/storybook-deployer/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@storybook/storybook-deployer/src/build-monorepo-index.js' {
  declare module.exports: $Exports<'@storybook/storybook-deployer/src/build-monorepo-index'>;
}
declare module '@storybook/storybook-deployer/src/build.js' {
  declare module.exports: $Exports<'@storybook/storybook-deployer/src/build'>;
}
declare module '@storybook/storybook-deployer/src/parse-args.js' {
  declare module.exports: $Exports<'@storybook/storybook-deployer/src/parse-args'>;
}
declare module '@storybook/storybook-deployer/src/utils.js' {
  declare module.exports: $Exports<'@storybook/storybook-deployer/src/utils'>;
}
