name: Prettify documentation

on:
  pull_request:
    branches: [master]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Prettify documentation
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --write **/*.{md,mdx}
          only_changed: True
