name: Release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  release-notary:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Publish
        run: lerna publish from-git --create-release github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
